### ISSUE TITLE
tsickle gets in an infinite loop for function that use their own type in their type declartion

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#1009]
For example:

```ts
export function f(): typeof f { return f;}
```

Surprisingly TS is ok with that, so tsickle should not get into an infinite loop and emit something sensible (maybe '?' if closure doesn't support it).

This did really happen in real code - https://github.com/angular/angular/commit/e4c1c88cbc4c28f1a9d9fca4b93432b3beab620e#diff-a66758223216005c664ce98175c4164fR1191

**Comment by blickly** [comment]
I tried to repro this issue in a unit test (see linked PR), but didn't hit the crash.  Is it possible this has been fixed since March?

**Comment by brad4d** [comment]
Google internal issue http://b/142073208 created

**Comment by blickly** [comment]
This was fixed by https://github.com/angular/tsickle/pull/1092
