### ISSUE TITLE
Should goog namespace import convert goog.require?

### ISSUE THREAD

**Issue by koba04** [angular/tsickle#1017]
I'm trying to use type information between TypeScript and Closure Modules each other with `tsickle` and `clutz`.

https://github.com/koba04/typescript-in-closure

I have a problem related to the result that goog namespace import is converted to `require('goog:foo')`.

https://github.com/koba04/typescript-in-closure/pull/4#issuecomment-489312777

I guess `import foo from 'goog:foo';` should be converted to `var foo = goog.require('foo');`, which works fine with not only Closure Compiler but also DebugLoader of Closure Library.
Am I misunderstanding about this?

If so I'll work on to fix the problem.

**Comment by koba04** [comment]
This works fine by using `import foo = require('goog:foo')` instead of an import statement.
 I should have used `import foo = require('goog:foo')` because `goog.require` is evaluated on runtime and ES Modules are determined statically.

I'll close this but If you have any suggestions, please put any comments!

**Comment by evmar** [comment]
I think our intent is that we convert the imports as you suggest.
See the code here, it handles 'goog:' imports:

https://github.com/angular/tsickle/blob/master/src/googmodule.ts#L164

This is controlled by the 'googmodule' flag to tsickle, maybe you have it off?
