### ISSUE TITLE
Constructor functions get an incorrect type

### ISSUE THREAD

**Issue by wffurr** [angular/tsickle#1020]
jscompiler has [a type for a constructor function](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#function-new-type):
```javascript
/** @type {function(new():Foo, string} */
var FooMaker;
```

The analog in TypeScript depends on the context.

For a bare function (see also [the TypeScript handbook on constructor signature types](https://www.typescriptlang.org/docs/handbook/interfaces.html#difference-between-the-static-and-instance-sides-of-classes)):
```typescript
interface FooConstructor {
  new (f: string): Foo;
}
var FooMaker: FooConstructor;
```
Or for a class member:
```typescript
class C {
  makeFoo: {new(f: string): Foo};
}
```

The emitted type for the class member has several errors:
```javascript
/** @type {function(new: (!Foo), string): ?} */
C.prototype.makeFoo;
```

The expected value is:
```javascript
/** @type {function(new:Foo, string)} */
C.prototype.makeFoo = function(str) {};
```

Note that the function is assigned a value, the return type is omitted (implied by new:Foo), and the Foo isn't parenthesized and lacks a nullability annotation.

I wrote a failing test case here:  https://github.com/wffurr/tsickle/commit/36c0a10a5a14686d1ffa1974f9b6c5c0c66de525

I'm not certain what the correct output is for the bare function, but it should probably be something like:
```javascript
/** @type {function(new:Foo, string} */
var FooMaker = function(str) {}
```
I could proceed with a fix if you have some guidance to offer, or you could cherrypick the test case and build from there.

**Comment by evmar** [comment]
I commented on your test case directly.  I believe the main place to look at is
https://github.com/angular/tsickle/blob/0fae5b5dcc617787ec0c37b8309312dcbadec5c2/src/type_translator.ts#L761

and also note the special casing near
https://github.com/angular/tsickle/blob/0fae5b5dcc617787ec0c37b8309312dcbadec5c2/src/type_translator.ts#L654

I am not certain about that though, I always get a bit confused about where particular things are handled.  I might start by changing the string 'function(' in that first code to say "functionFDASFAS" and verify it's modifying the right place.

**Comment by evmar** [comment]
Looking harder, after that first link it appears we intentionally insert some extra parens, not sure whether it's right or not.  At this point you have likely thought about this harder than any of us have.

**Comment by wffurr** [comment]
The nullability annotation is what causes the jscompiler to no longer recognize the function as a constructor type.  The parens and space don't seem to matter.
