### ISSUE TITLE
@ExportDecoratedItems does not work for custom decorator

### ISSUE THREAD

**Issue by kemsky** [angular/tsickle#1027]
I'm using latest angular 8.0.0 and ngc.

Decorator:
```typescript
/**
 * @ExportDecoratedItems
 * @export
 */
export function Api(base:string = ''):Function {
    return function (target:any):any {
        return target;
    };
}
```

Service:
```typescript
@Injectable({providedIn:'root'})
@Api('accountmanager')
export class AccountManagerService extends SecureJsonService {
...
}
```
tsconfig:
```json
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "annotationsAs": "static fields",
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": false
  }
```

I've checked `isExportingDecorator` function result and it returns `true` for my decorator, but emitted code does not have my decorator in the `decorators` property, there is only `Injectable`:
```typescript
    AccountManagerService.decorators = [
        { type: Injectable, args: [{ providedIn: 'root' },] },
    ];

    AccountManagerService = __decorate([
        Api('accountmanager')
    ], AccountManagerService);
```

**Comment by evmar** [comment]
Can you describe what output you expected?  This is documented as doing a thing with Closure @export comments, not something in the generated output for decorators.

https://github.com/angular/tsickle/blob/master/README.md#exporting-decorators
