### ISSUE TITLE
Support command-line build workflows

### ISSUE THREAD

**Issue by martine** [angular/tsickle#104]
Users other than Google will probably want some sort of sickle executable that they can apply to their source to get Closure output.

Perhaps Sickle should even go as far as being responsible for executing Closure on their behalf -- so you just take your TypeScript output, give it to Sickle, and you get a minified binary out.

**Comment by martine** [comment]
Depends on https://github.com/angular/sickle/issues/46

**Comment by mprobst** [comment]
There's an npm package for Closure Compiler.

Evan Martin <notifications@github.com> schrieb am Do., 17. März 2016 um
17:58 Uhr:

**Comment by martine** [comment]
Sickle already depends on the Closure compiler node module because it runs the compiler in its e2e test!

**Comment by mprobst** [comment]
Right, I added that myself :-)

Evan Martin <notifications@github.com> schrieb am Do., 17. März 2016 um
18:12 Uhr:

**Comment by kylecordes** [comment]
Over on the TypeScript repo, @martine pointed out that this tool is used internally at Google in a way that wraps tsc.  Perhaps just exposing that capability to the outside world, or publishing a small example of using sickle even if it requires a bit of wiring in, can start to broaden the interest, use and contribution to the project.

**Comment by martine** [comment]
sickle.ts in the repo can be called like a main program, but it doesn't write its outputs anywhere: it just dumps an object to stdout.

So this is the example code:
https://github.com/angular/sickle/blob/master/src/sickle.ts#L765
where instead of using console.log on the output, it would need to write that output to a file somewhere.

**Comment by Dominator008** [comment]
Just want to add that as Closure Compiler now accepts JSON streams as inputs, it will be great if Sickle can output a JSON stream. This will facilitate integration with a Gulp-based workflow.

**Comment by martine** [comment]
@Dominator008 got a link to some docs?  What is a JSON stream?

**Comment by Dominator008** [comment]
@martin With the `--json_streams` flag, Closure Compiler accepts a JSON array of sources. Each source will be an object of the form
```json
{path: filename, src: file_contents, srcmap: srcmap_contents }
```
The best documentation for now is probably the help message from Closure Compiler's CommandLineRunner :) https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L593-L600

The NPM module google-closure-compiler provides a Gulp plugin that makes use of this flag: https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/lib/gulp/index.js#L106-L109

CCing @ChadKillingsworth who added this feature to the Compiler.

**Comment by ChadKillingsworth** [comment]
The `--json_streams` flag is an enum with values `IN`, `OUT`, and `BOTH`. Due to command length restrictions on windows builds, I found it convenient to use the flag for grunt plugins as well as gulp.

Paths should be absolute from the working directory of the compilation. This affects module path references.

The compiler doesn't compose source maps, so if you wish to have composed source maps you must compose them post-compilation. The closure-compiler-npm package has that functionality in the gulp plugin.

**Comment by ChadKillingsworth** [comment]
Also, closure-compiler does use input source maps for the purpose of displaying error messages.

**Comment by martine** [comment]
What's now landed works like this:

```sh
sickle --output bundle.js -- -p myproject [other args to tsc here]
```

That is, you tell sickle the `--output` path, then a `--`, then the args you'd normally pass to `tsc`.  Using the json streams feature of closure (thanks @ChadKillingsworth!) we don't need to write any temporary files so the final bundle.js is all sickle produces.

This seems to work in small test cases at least.

There remain questions about how to map TS modules to node modules etc.  For example, running sickle on its own code produces
```
st/sickle.js:2: ERROR - required "typescript" namespace never provided
var ts = goog.require('typescript');
         ^
```
Because we translated the `import * as ts from "typescript"` into that.

I'll leave this bug open until I file new ones on the remaining issues.

**Comment by ChadKillingsworth** [comment]
The next major feature on my list for the compiler is a named module registry and to implement the node module location algorithm. It will still be up to a pre-processing system to provide a mapping of files to module names.

Realistically it will be May before I begin work on this though.

**Comment by martine** [comment]
@jjudd found it was better to have tsickle not call the closure compiler itself, but instead produce closure-compatible JS files.  This e.g. allows mixing TypeScript and Closure-compatible JS together in projects.  This seems to basically work, so I'm closing this bug.
