### ISSUE TITLE
reorganize closureExternsBlacklist

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#106]
from @rkirov 

This list needs to be more structured (we can keep hacking on it for now). Here is what I did in clutz:

fix which files are considered "platform apis" on both sides:

lib.d.ts for TS (TSsymbols)
closure/externs:COMMON (ClosureSymbols)
modify lib.d.ts to be a strict subset of closure externs

enumerate symbols in missingPlatformSymbols = ClosureSymbols \ TSSymbols ( \ is set difference)
clutz now emits everything not in closure externs + missingPlatformSymbols.

Beyond "platform externs", I don't think the tool should be doing any white/black listing, as we can't have any visibility into what those symbols are. It won't scale to keep adding them here.

**Comment by evmar** [comment]
We now accept this as an externally-provided parameter.
