### ISSUE TITLE
Remove command-line program, change to being library-only

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#1075]
We have a bunch of bugs here that are various forms of "the command-line tsickle program doesn't do what I want".  In practice, using tsickle well requires a driver program like the Angular compiler, or maybe https://github.com/theseanl/tscc .

I think we should consider removing our command-line interface entirely and instead say to use one of these other tools.  Right now our CLI tempts people into trying it, but it doesn't really work, and we don't have resources to improve it.

**Comment by evmar** [comment]
Assigning to Martin for a decision; I can implement if you think it's right.

**Comment by evmar** [comment]
Some example bugs: #687 #742 #474

**Comment by mprobst** [comment]
I'm OK with that.

**Comment by evmar** [comment]
Do you think it's a good idea, though?

**Comment by mprobst** [comment]
Yes, I don't think there's value in `src/main.ts`; it's simply not working, and fixing it is indeed not worth it compared to pointing people to `tscc`.

**Comment by evmar** [comment]
CC @theseanl

**Comment by theseanl** [comment]
I understand the intent to focus more on the essential part of the tsickle, and I'd be happy to take the burden of improving CLI tools for tsickle.

I'm concerned that some people may want more freedom on some opinionated choices made in tscc, such as a way to provide compilation sources by means of entry modules, or the inclusion of `base.js` and `reflect.js`, and having a bare-bone tsickle cli would still be valuable in view of this. IMO it's a bit of misnomer that it didn't really work, I've been using it for a while!

**Comment by theseanl** [comment]
I'd be happy to work further on the CLI and getting more feedback. But as I understand, there are some ways to use tsickle via some Bazel rules, why not add pointers to that? It seemed that many build tools opensourced by Google is somehow involved with Bazel, so it seemed to be the "expected" way of using tsickle. I couldn't find a comprehensive documentation on using tsickle and closure compiler with Bazel and I'm eager to learn more about it.

**Comment by evmar** [comment]
@alexeagle is the bazel master.  The `rules_nodejs` (https://github.com/bazelbuild/rules_nodejs) project has our integration, but I think it doesn't wrap Closure compiler yet.

**Comment by alexeagle** [comment]
right, under Bazel we expect that tsc_wrapped will be the driver of the tsickle plugin.

I'm okay with removing the main.

**Comment by mprobst** [comment]
Alex, what's the authoritative documentation that we should link to? I'd
imagine our README.md would say "Go here for tscc, go here for the bazel
rules integration".

**Comment by alexeagle** [comment]
I don't think our documentation is sufficient, but tsickle is mentioned on https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md and that's probably the right spot, unless we add a new high-level doc about Bazel+TS+Closure
