### ISSUE TITLE
tslib __rest and __spreadArrays 

### ISSUE THREAD

**Issue by theseanl** [angular/tsickle#1084]
The latest tslib contains an additional enumerability check in `__rest` helper: https://github.com/microsoft/tslib/blob/ec58992a93e2453a9609024c4dbe3e64e0a78409/tslib.es6.js#L47 and a new helper __spreadArrays.

Can the tsickle's modified tslib be updated according to these changes? `__spreadArrays` is not relevant with the current typescript version 3.5.3, but `__rest` can be emitted for language target less than ES2018.

**Comment by evmar** [comment]
I think it's just as simple as copying the relevant code over from tslib, so please send the PR!

**Comment by theseanl** [comment]
Now resolved with db61ea2676d9ca786d35ce342ae512894c022ea0!
