### ISSUE TITLE
Rationalize handling of type/value conflicts

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#1116]
If some code declares a type/value conflict, e.g.

```ts
interface X { ... }
const X = ...;
```

Then tsickle backs off by omitting the type output.  This means nobody else can use "X" as a type. 
 (https://github.com/angular/tsickle/pull/1077 attempts to fix this, by mangling the the type name in these circumstances.  It's a pretty rare pattern though.)

However, in some circumstances we do believe that for a type/value conflict the type still exists:
- browser builtins (which are defined in lib.d.ts, but we assume the Closure externs match)
- clutz-generated types (because they are derived from Closure JS)

To summarize all the cases of conflicts and what we should do:
1. browser builtins: assume type exists
2. clutz-generated types: assume type exists
3. tsickle-generated output: either back off, or use mangled name

These three cases correspond to the functions (1) isClosureProvidedType, (2) isClutzDype, and (3) the above PR tries to catch these by adding a special header to our d.ts

I think it is never the case that we want to treat category 1 and 2 differently from each other, so this bug is about how we shouldn't have both of these functions, but rather one that covers both.  (Also, the impl of these functions is a big hack, so maybe we should instead say you're in case 1/2 any time you're *not* in case 3?)

To see this problem, add these lines to `test_files/clutz_type_value.no_externs`:
```ts
// We expect IFace to show up in the type signature.
let x: IFace;
```
It currently generates {?}.  The buggy code here only checks for category 1, not 2.  You can find said buggy code by grepping for isClosureProvidedType/isClutzDype and convincing yourself that any caller of these should really be calling both.

**Comment by evmar** [comment]
Google internal b/144186648 has a real app this breaks.

**Comment by mprobst** [comment]
Internal tracking issue at b/144255600.
