### ISSUE TITLE
Tsickle emits wrong type for rest args as union of tuple types

### ISSUE THREAD

**Issue by kjin** [angular/tsickle#1120]
This code

```ts
function foo(...args: [number]|[string, number]) {}
```

transforms to:

```js
/**
 * @param {...!Array<?>} args
 * @return {void}
 */
function foo(...args) { }
```

This suggests that each element should be an array, which is not the case. I would expect `Array<?>` to be `number` or `number|string`, but not an array of anything.

**Comment by evmar** [comment]
Those aren't array types, they are tuple types.

Even just
```
function foo(...args: [number]) {}
```
likely doesn't do what you want (it only accepts a single argument).

**Comment by nreid260** [comment]
Created internal issue b/144809311

**Comment by kjin** [comment]
@evmar Yes, that's true, I mistakenly called them array types in the title earlier but they are indeed tuple types in TypeScript. The bug still persists: if `args` is a union of tuple types, then its mapped type is currently `Array<Array<?>>`, but `Array<?>` is more appropriate.

I think the pattern of `foo` is a common way to summarize function overloads, e.g. if `foo` is some sort of number-to-string method:

```ts
function foo(arg: number);
function foo(format: string, arg: number);
function foo(...args: [number]|[string, number]) {} // one way to summarize the overloads
```

Granted this might not work well with Closure types in the first place, but right now I believe the tsickle will output an incorrect type.
