### ISSUE TITLE
Control namespace name

### ISSUE THREAD

**Issue by Lokeh** [angular/tsickle#1145]
Is there any way (or documentation about how) to control the `goog.module` namespace emitted by tsickle?

My use case: I've built a small (one file) TS library that I would like to generate Closure-compatible JS to use with ClojureScript. ClojureScript uses gcc under the hood, and understands Clojure JS just fine.

Currently, when I build my Clojure JS outputs for my library, it emits something like:

```javascript
goog.module('_Users.lilactown.Code.stm_js.src.index');
```

AFAIK, this namespace is how consumer would access my library; so I would prefer it to not include my file system structure in the name. Ideally, I would be able to control it to be something like:

```javascript
goog.module('lilactown.stm-js');
```

Is there a way to control this on a per-file / per-project basis? I could probably hack something in my build script (that I've basically copied from the demo) but I thought this might be something already supported.

**Comment by evmar** [comment]
In general, this isn't a use case we really plan around.  The intent of tsickle is to generate something that the compiler accepts but the code isn't meant to be pretty.  In particular, when generating an import from A of some module named B, I think we base the goog.require on the name of B without inspecting its contents.

However, you might be able to use pathToModuleName, which is exposed to callers;

https://github.com/angular/tsickle/search?q=pathToModuleName&unscoped_q=pathToModuleName

**Comment by Lokeh** [comment]
Ah, I see! The `pathToModule` name seems to give me a way to control this for my library, at least. Here's what I did:

```javascript
    pathToModuleName: (context, fileName) => {
      // hacky way of renaming stuff in our project to pretty namespaces
      if (fileName.endsWith("src/index.ts")) {
        return "lilactown.stm-js";
      }
      return tsickle.pathToModuleName(rootModulePath, context, fileName);
    },
 ```

I'm guessing that if I depended on any libraries where I imported `library-name/src/index.ts` I might run into some issues, but I won't worry about that for now 😅
