### ISSUE TITLE
Strip unexpected docstring annotations

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#115]
Angular2 uses docstring comments like

```js
/**
 * @Component(...)
 */
```

which Closure rejects.

I think the proper answer is a whitelist in sickle of known docstring annotations that Closure accepts (stuff like @nosideeffects etc.).

**Comment by mprobst** [comment]
You can also add more annotations to closure compiler using some flag, but
a whitelist might indeed be better than requiring every user to pass a long
list of meaningless annotations.

**Comment by martine** [comment]
Some greps produce the most common statements in google3 `*.ts` files:

@typedef
@const
@default
@remarks
@suppress
@callback
@license
@override
@Component({
@extends
@parm
@readonly
@enum
@description
@module
@since
@internal
@template
@chainable
@alias
@fileoverview
@view
@throws
@type
@deprecated
@author
@constructor
@example
@export
@ngInject
@returns
@see
@return
@param

**Comment by martine** [comment]
There are d.ts files that even use Closure annotations themselves (!)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/selenium-webdriver/selenium-webdriver.d.ts

**Comment by martine** [comment]
Here's the list of the most common ones found in non-third-party Google code.

@param
@ngInject
@Input
@export
@fileoverview
@Output
@ViewChild
@desc
@return
@returns
@type
@example
@HostBinding
@ViewChildren
@HostListener
@124441303
@VisibleForTesting
@suppress
@override
@Log

**Comment by mprobst** [comment]
I was somebody with Closure complaining about @Component (unescaped example
code).

>

**Comment by evmar** [comment]
A user encountered a compile failure due to @params in rxjs code.

I would just strip all of these but I'm worried that there are some that are load-bearing annotations (like @nocollapse on a static, which I had never seen before) that we shouldn't strip.  I really need a list of the ok ones.
