### ISSUE TITLE
Update peerDependency on Typescript to ~3.9.x

### ISSUE THREAD

**Issue by bjornharvold** [angular/tsickle#1155]
Cannot update to Angular 10 with forcing an ng update at the moment.

`ng update @angular/core @angular/cli fails`

Have to type
`ng --force update @angular/core @angular/cli`

**Comment by lauraharker** [comment]
I believe @rrdelaney is working on upgrading to TS3.9.

Created Google internal issue http://b/159923702.

**Comment by aramperes** [comment]
Please bump this ticket when a new version of `tsickle` is released. Thanks for the quick turnaround!

**Comment by rrdelaney** [comment]
New version should be published!

**Comment by aramperes** [comment]
Looking at https://registry.npmjs.org/tsickle (`versions -> 0.39.0 -> peerDependencies`), the TypeScript peerDependency is still at `~3.8.2`. Only the devDependency seems to have been updated.

**Comment by rrdelaney** [comment]
Sorry about that, should be fixed! Thanks for the PR!
