### ISSUE TITLE
Enable source maps in v8 stack traces

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#116]
Looks like this will do it:

https://github.com/evanw/node-source-map-support

**Comment by mprobst** [comment]
See also here:
https://github.com/angular/ts2dart/blob/master/lib/main.ts#L358

**Comment by mprobst** [comment]
Closure compiler now has `--apply_input_source_maps` and `--parse_inline_source_maps`, so it'd be nice to get this online, too.

**Comment by mprobst** [comment]
This was partially fixed in e4dcfecd88d4fe0fa1f5f7bef781a81d55f8c43b.
