### ISSUE TITLE
commonJsToGoogmoduleTransformer misses some `module.exports = ...` statements.

### ISSUE THREAD

**Issue by coreywoodfield** [angular/tsickle#1219]
`visitTopLevelStatement` calls `rewriteModuleExportsAssignment`, which transforms statements of the form `module.exports = foo` to `exports = foo`. However, it fails to do that same transformation if that statement is used to assign something else as well (e.g. `var bar = module.exports = foo` should get transformed to `var bar = exports = foo`, but does not)

**Comment by evmar** [comment]
Can you give an example of some input TS that produces this?

**Comment by coreywoodfield** [comment]
The following typescript code: 
```
module.exports = 4;
var x = module.exports = 5;
```
gets transformed to the following javascript:
```
goog.module('module_name');
var module = module || { id: 'module_id' };
exports = 4;
var x = module.exports = 5; // <--- this assignment to module.exports was not transformed
```

**Comment by evmar** [comment]
As far as I know, I think we only support ES module input, where you don't use `module.exports` at all...

**Comment by coreywoodfield** [comment]
Ah okay. I just noticed that the first line was transformed but the second one wasn't, which I figured was a bug. I assumed this would be supported because the code very deliberately replaces `module.exports` with `exports`, but not in all cases

**Comment by evmar** [comment]
I think we don't support commonjs in general, but only enough to massage TS's commonjs output from ES module input.  It's not an intentional omission, we just have no TS code that uses commonjs directly.
