### ISSUE TITLE
Is tsickle intended to be used with json files?

### ISSUE THREAD

**Issue by NicBright** [angular/tsickle#1226]
Hi there,

I'm currently investigating an issue that prevents us from removing TSConfig Compiler Option "removeComments: true" which has obviously been added in the past as a workaround to the following buggy behavior, of which I'm not really sure what the root cause is:

We're using ng-packagr which "mysteriously" require's tsickle here: https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/ngc/create-emit-callback.ts#L69 -- "mysteriously", because from a dependency point of view it only specifies tsickle to be a devDependency, but apparently it's required in their final package as well (in the end: doing `npm ls tsickle` I'm not able to find out why tsickle was installed in the first place ....) ... 

Regardless of ng-packagr's dependency issues, this is what we get as an error:

![image](https://user-images.githubusercontent.com/1225659/100469543-aee04500-30d6-11eb-8d56-a24b6072ed4f.png)

I then navigated to that error log:

![image](https://user-images.githubusercontent.com/1225659/100469616-d9320280-30d6-11eb-84ed-acc38f530dde.png)

Which pointed me to the place where the error occured. I was able to modify it to have a look at the "wrong" json that caused the error:

![image](https://user-images.githubusercontent.com/1225659/100469693-0ed6eb80-30d7-11eb-93fa-cbd3722aa006.png)

Which finally gave me this:

![image](https://user-images.githubusercontent.com/1225659/100470104-db489100-30d7-11eb-8a53-a77a46bb1730.png)

As you can see, tsickle modified our json file and broke it (obviously json files cannot contain comments like these).

This must have been the reason why somebody in my company added that "removeComments: true" switch in our tsconfig.json ... which is bad for other reasons. I would really like to go back to using default "removeComments: false" again, but then I'm receiving this error :-(

Can anybody help? At which point should a potential fix be started with?

**Comment by mprobst** [comment]
I think we can work around this by ignoring JSON files for transformation.

That being said, tsickle is a special case tool to transform TS files for Closure Compiler. Closure Compiler doesn't understand JSON files, so chances are you should not be using tsickle at all. I have no idea how ng-packagr works, but I faintly remember a discussion about this before; they should not depend on tsickle.
