### ISSUE TITLE
TypeScript async (__awaiter) produces illegal Closure JS

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#124]
If you declare an async function, TypeScript injects this function `__awaiter` in the result.

```
st/foo.js:1: ERROR - The body of a goog.module cannot reference this.
goog.module('st.foo.js');var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
```

This is pretty low priority because I don't think our users are using async yet.

**Comment by batuhan** [comment]
Is there an update on this? Just hit this bug.

**Comment by evmar** [comment]
I think this is the same underlying problem as
https://github.com/angular/tsickle/issues/168

There I said:
"the fix is to use --noEmitHelpers and then to provide your own, Closure-compatible implementations of those helpers"

Now that I'm thinking about it, I will file a new bug based on some new developments in this area, too; one sec.

**Comment by evmar** [comment]
I think @mprobst is working on this right now.

**Comment by evmar** [comment]
Wait actually our tslib fixes this one.
