### ISSUE TITLE
can you do a release?

### ISSUE THREAD

**Issue by jcesarmobile** [angular/tsickle#1242]
With npm 7 being default, `npm install` command fails on apps that use typescript 4 because latest version of tsickle has a peerDependency of typescript 3.
It was changed to typescript 4 on https://github.com/angular/tsickle/pull/1213, but it isn't released.

While it's possible to use `--force`  or `--legacy-peer-deps` params on `npm install` to workaround the problem, would be good if the package could be released.

**Comment by evmar** [comment]
We can make a release, but often when we hear from users in your state it's because they accidentally depend upon tsickle when they didn't mean to.  Can you confirm that you actually are using tsickle?  How?

**Comment by jcesarmobile** [comment]
I'm not, it's a peerDependency of `ng-packagr`, which is a peerDependency of `@angular-devkit/build-angular` which is the one I use. And both of them have typescript 4 as a peerDependency.

**Comment by evmar** [comment]
@alxhub Do you know why ng-packagr has this dep?

**Comment by alxhub** [comment]
@kyliau might know. It's probably legacy, from the days when `tsickle` was a hard dependency of `@angular/compiler-cli`. It hasn't been for a while, so likely the right answer is for `ng-packagr` to remove the peer dep.

**Comment by kyliau** [comment]
I don't see any reason ng-packagr still needs `tsickle`. @alan-agius4 could you please enlighten us?

**Comment by clydin** [comment]
Both `tsickle` and `ng-packgr` are optional peer dependencies.  This appears to be an npm 7 defect in that it shouldn't be attempting install either of them.

**Comment by jcesarmobile** [comment]
It a npm 7 feature, it installs peer dependencies if you don’t pass --force or --legacy-peer-deps params to the install command.

**Comment by clydin** [comment]
Yes.  Peer dependencies should be installed but optional peer dependencies should not.  Otherwise they are no longer optional peer dependencies.

**Comment by clydin** [comment]
As to the `ng-packagr` usage of `tsickle`, it is listed as an optional peer dependency for developers wishing to use the `annotateForClosureCompiler` option.  The optional peer dependency helps to ensure that a compatible version of `tsickle` is used with the Angular compiler.

**Comment by clydin** [comment]
After some additional experimentation via the `--force` option, it appears that the optional peer dependencies are not installed.  However, they are still being resolved/analyzed and `npm` is refusing to install even if they are not present.

**Comment by jcesarmobile** [comment]
`ng-packagr` removed the `tsickle` dependency, so this is no longer a problem for angular users, but will leave the issue open.

Feel free to close.

**Comment by brad4d** [comment]
I attempted to release

**Comment by brad4d** [comment]
I retried with this command:

```
bazel run :npm_package.publish --incompatible_restrict_string_escapes=false -- --registry https://wombat-dressing-room.appspot.com
```

That seemed to work up to the point that it couldn't find a publish key.
Which makes sense, because I don't have one.

**Comment by brad4d** [comment]
I'll probably need help from @evmar to finish this.

**Comment by annervisser** [comment]
@evmar Any update on this?
I am using tsickle to compile a typescript project with closure. (using tscc)
The 0.39.0 of tsickle release is currently the blocking factor in updating to typescript 4.x, a new release would allow tscc to update as well.

I am able to build & run my application with `typescript@4.3.2` by building tsickle manually at 43f59d16c90559452005107432dffa7f40fb60e0 and applying a small patch to tscc

**Comment by rohitpratapitm** [comment]
Still facing the same issue while creating a new application using angular cli and npm v**7.15.1**


@angular/cli 11.2.x // has a peerDependency of typescript <4.1
@tsickle         0.39.1  // [has a peerDependency of typescript ~3.8.2](https://github.com/angular/tsickle/blob/v0.39.1/package.json#L14)

Same issue with tsickle v 0.40.0 as well. There the peer Dependency is typescript ~4.2

Since npm v7 installs peer dependencies automatically, it is getting into version conflict issue. See error below:

````
> npm "install"

(node:15608) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: delete-me-app@0.0.0
npm ERR! Found: typescript@4.1.5
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.1.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"~3.8.2" from tsickle@0.39.0
npm ERR! node_modules/tsickle
npm ERR!   dev tsickle@"0.39.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

**Comment by mprobst** [comment]
@rohitpratapitm can you file an issue in https://github.com/angular/angular? I believe it's a bug in Angular if new applications still depend on tsickle.

**Comment by brad4d** [comment]
At this point I think it's clear that we aren't going to do any more releases.
