### ISSUE TITLE
0.41.0 installed via `npm i tsickle@0.41.0` includes has possible debug line in it?

### ISSUE THREAD

**Issue by BrianLeishman** [angular/tsickle#1275]
Not sure if this is related to the issue from yesterday, but it seem on line 61 of `tsickle.js` there's this line

```js
missingSymbol.example();
```

Which, as it looks, is a missing symbol that causes tsickle to fail. Commenting the line out fixes it. I also don't see this line in the master.

**Comment by mprobst** [comment]
Whoops. Fixed in 0.43.0.
