### ISSUE TITLE
No version supporting Typescript 4.5 publicly available

### ISSUE THREAD

**Issue by Teuvz** [angular/tsickle#1322]
Currently, version 0.45.0 of tsickle is not yet available on NPM and is causing dependency issues on recent Angular projects. Would it be possible to create the tag and publish the latest version ? Or at least version 0.44.0.

**Comment by mprobst** [comment]
Your Angular project should not depend on tsickle unless you've explicitly chosen to use tsickle (and most people shouldn't). If it does, there's some incorrect setup in your dependencies.

I can still push a release, but you should probably also fix your deps.

**Comment by randym127** [comment]
No one knows what versions go with what...

**Comment by brad4d** [comment]
I feel I should manage expectations here.

The team that created tsickle no longer expects to do any further releases of it.
If possible, you should probably stop using it.
If you must use it, you should probably create your own fork.
See also https://github.com/angular/tsickle#warning-unsupported
