### ISSUE TITLE
tsickle@0.46 references typescript version that doesnt exist

### ISSUE THREAD

**Issue by wjaspers** [angular/tsickle#1346]
Unfortunately, with the advent of `npm@8.6.0` we've been getting hit hard with peer dependency resolutions that are consistently failing.
As part of the process of upgrading packages and tuning `dependencies` and `peerDependencies`, sometimes `tsickle` appears in our angular projects.
During this process, `@angular/<project>#13.3` projects require Typescript at version `4.4.2 or better, which `tsickle` doesn't match up to.
`tsickle@0.46` is most current, but without a valid typescript version, we're dead in the water.

**Comment by mprobst** [comment]
Your Angular project should not depend on tsickle. If it does, that's a bug, and you should remove the dependency.

The latest tsickle btw requires TS 4.6.3 or matching patch level, so newer than 4.4 should be OK.
