### ISSUE TITLE
Create a tsickle-cli that depends on tsickle

### ISSUE THREAD

**Issue by martine** [angular/tsickle#137]
Tsickle does the annotation magic.  But to use it you wanna run Closure in a complicated way, so in principle we should depend on `google-closure-compiler`.  But that brings in a million other dependencies that are all unrelated to annotation.

The solution: make a tsickle-cli package that manages running things.  Users like Google-internal tsc_wrapped and Angular's builder will likely not need tsickle-cli.

**Comment by alexeagle** [comment]
we do now depend on `google-closure-compiler` so I think this is obsolete?

**Comment by martine** [comment]
The idea in this bug was that tsickle itself shouldn't depend on google-closure-compiler (since you don't need it if you're just using tsickle to transpile), but rather there should be a tsickle-cli package that uses both tsickle and the compiler.

**Comment by martine** [comment]
It seems like @jjudd fixed this in #153.
