### ISSUE TITLE
Enum values translated incorrect if using namespace

### ISSUE THREAD

**Issue by lgemeinhardt** [angular/tsickle#1375]
Tsickle translated enum values translated incorrect if using namespace.

Sample .ts file:
```
declare namespace foo {
  enum nums {
    ONE = 1,
    TWO = 2,
  }
  enum strings {
    ONE = 'ONE',
    TWO = 'TWO',
  }
}
```

Current js output:
```
/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: ...
/** @const */
var foo = {};

/** @enum {number} */
foo.nums = {
  ONE: 1,
  TWO: 1,
};

/** @enum {string} */
foo.strings = {
  ONE: '',
  TWO: '',
};
```

Expected js output:
```
/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: ...
/** @const */
var foo = {};

/** @enum {number} */
foo.nums = {
  ONE: 1,
  TWO: 2,
};

/** @enum {string} */
foo.strings = {
  ONE: 'ONE',
  TWO: 'TWO',
};
```

**Comment by frost-cy** [comment]
Created Google internal issue http://b/236797164

**Comment by lgemeinhardt** [comment]
I try to use tsickle to move some mappings from https://github.com/DefinitelyTyped/DefinitelyTyped to closure externs and afterwards using https://github.com/google/jsinterop-generator to GWT. 
My first try was the google.maps mapping (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google.maps/), because I could compare this to the given extern (https://github.com/google/closure-compiler/tree/master/contrib/externs/maps) and was concerned about the difference (assuming the values for enum numbers and strings are needed later on for the JsInterop for GWT).

**Comment by mprobst** [comment]
> assuming the values for enum numbers and strings are needed later on for
the JsInterop for GWT

Are they though? I don't know how jsinterop processes these, but given
string literal types are not a feature in Closure Compiler, I would expect
that not to matter.

**Comment by mprobst** [comment]
The code you link to isn't externs, i.e. it's not produced from a `.d.ts`.
In that code, we do care about the actual value, because it's part of the
app (and it'd  break if we left the enum values out). `.d.ts` and
***@***.***` are special because they describe code that is not part of your
app.

**Comment by lgemeinhardt** [comment]
@mprobst Thanks for the quick clarification. 
It sounds tsickle does this on purpose (even if it looks strange, that enum number values are all 1 and enum strings values are all empty and the generated externs looks different, then the official once from closure-compiler externs). 
I will check if jsinterop-generator could produce valid mappings and will close this issue afterwards.
