### ISSUE TITLE
Could you release a NPM package?

### ISSUE THREAD

**Issue by theseanl** [angular/tsickle#1380]
Currently, the latest version 0.46.0, which was published 5 months ago depends on a modified version of TS 4.5, and the version before that depends on TS 4.3, while the master branch depends on TS 4.7.
Could you please update the NPM package? It would allow [TSCC](https://github.com/theseanl/tscc) to use a newer TS features.

**Comment by mprobst** [comment]
Looking into this, but unfortunately a piece of our release process appears broken (sigh). Will update once we figured that out.

**Comment by theseanl** [comment]
Thank you!
