### ISSUE TITLE
Emit `propDecorators` for fields and setters

### ISSUE THREAD

**Issue by tbosch** [angular/tsickle#141]
E.g. the following does not emit a `propDecorators` property on the class.
```
class ClassWithDecorators {
  @PropDecorator("p1") @PropDecorator("p2") a;
  b;

  @PropDecorator("p3")
  set c(value) {
  }
```

**Comment by tbosch** [comment]
Code that might help:
```
          case ts.SyntaxKind.PropertyDeclaration:
          case ts.SyntaxKind.GetAccessor:
          case ts.SyntaxKind.SetAccessor:
            const property = <ts.PropertyDeclaration>member;
            const propertyDecorators = getDecorators(property.decorators);
            if (propertyDecorators) { ... }
```

**Comment by martine** [comment]
Looks like @alexeagle fixed this in https://github.com/angular/tsickle/commit/3c7e2fd131e5a989824a59c19c5ab9a77fe876ad .

**Comment by mprobst** [comment]
@alexeagle looks like these were minor fixes, but would you maybe want to do a post commit review of this? Do they LGTM @martine?

**Comment by martine** [comment]
Yeah I read the linked CL and it seems right to me.  Pretty straightforward.

**Comment by mprobst** [comment]
OK, then let's close this. FTR, I think it's fine to do post-submit/push code reviews in cases like this, but we should track that and still do the reviews.
