### ISSUE TITLE
Warn on variables starting with underscores

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#143]
To Closure, a variable name that starts with an underscore prevents optimization.
Tsickle should warn/error on code that uses an underscore.

**Comment by mprobst** [comment]
Oh great. Starting with an underscore is the convention for private fields
in Dart, so tons of fields in Angular 2 start with an underscore.

**Comment by martine** [comment]
I'm having difficulty coming up with a case with one of the Closure inspectors that demonstrates this problem, but I'm sure I've seen it.  See also https://github.com/Microsoft/TypeScript/issues/7345

**Comment by rkirov** [comment]
I think leading underscore is the escape hatch for 'variable renaming', which is completely different from 'property renaming'. So class fields are save, but top-level functions like `__extend` are not.

**Comment by evmar** [comment]
I cannot repro varying behavior here, and we disallow this per style already.
