### ISSUE TITLE
Decorator rewriter statics get dropped by Closure

### ISSUE THREAD

**Issue by martine** [angular/tsickle#144]
Closure models class modifications like this:

```js
/** @constructor */
function Foo() {}

/** @type {number} */
Foo.xxx = 3;
```
as a namespace, so `Foo.x` becomes `Foo$xxx` or whatever.  This means you can't e.g.

```js
function use(f) { ... f.xxx; }
use(Foo);
````

because `Foo` has no `xxx` on it.

Workaround from here:
http://stackoverflow.com/questions/12748755/how-to-have-an-array-of-classes-with-static-methods-when-using-the-closure-compi

Is to change it to:

```js
(function(obj:any) {
/** @type {number} */
obj.xxx = 3;
})(Foo);
```

Pretty gross.

**Comment by mprobst** [comment]
Wouldn't usage sites still get changed?

>

**Comment by martine** [comment]
@mprobst hm, not sure.  Rado found another workaround I think -- some attribute to put on the statics.

**Comment by rkirov** [comment]
@alexeagle got the magic incantation - @nocollapse on the static prop, like this:

```
/** @type {number} @nocollapse */
Foo.xxx = 3;
```

IMHO, this is better than the closure wrapper, as it will minify better.

**Comment by rkirov** [comment]
@mprobst with @nocollapse and property_renaming off, xxx gets consistently renamed, both in the definition and caller site.

**Comment by mprobst** [comment]
@rkirov Nice!
