### ISSUE TITLE
[bug] Tsickle & interface

### ISSUE THREAD

**Issue by vicb** [angular/tsickle#148]
```
  constructor(private _authBackend: AuthBackend,
    @Optional() @Inject(FirebaseAuthConfig) private _config?: AuthConfiguration) {
    super(kBufferSize);

    this._authBackend.onAuth((authData) => this._emitAuthData(authData));
  }
```
_(`AuthConfiguration` is an interface)_

-> tsickle ->

```
    FirebaseAuth.ctorParameters = [
        { type: auth_backend_1.AuthBackend, },
        { type: AuthConfiguration, decorators: [{ type: core_1.Optional }, { type: core_1.Inject, args: [tokens_1.FirebaseAuthConfig,] },] },
    ];
```

`type: AuthConfiguration` fails because `AuthConfiguration` is an interface. tsickle should output `type:null`

**Comment by alexeagle** [comment]
How does it help to output `type:null` instead? Don't we actually use the `ctorParameters` in the static reflector? Maybe it should be `type:any`? @tbosch

**Comment by martine** [comment]
Oops, sorry for missing this!  The problem is that the code here is an object literal so the thing after `type: ` must be a value, and an interface is not a value.  This should be an easy fix.

**Comment by tbosch** [comment]
Yes, the problem here is that `AuthConfiguration` is an interface, i.e. we
can't refer to it in a value position.
If we have an `@Inject` decorator, we don't need the `type` value anyways...

**Comment by martine** [comment]
Note: currently the decorator transfomer runs over just one source file and processes it syntactically.  To distinguish interfaces from values we need to load and typecheck the whole program, which means changing the API a bit.

**Comment by vicb** [comment]
@martine do you have an ETA for this change ?

**Comment by martine** [comment]
@vicb sorry it was a bit harder than I expected, it's at https://reviews.angular.io/D139 now.

**Comment by vicb** [comment]
Cool, thanks @martine
