### ISSUE TITLE
missing namespace on parameter types

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#149]
tsickle 0.1.3 on https://github.com/angular/angular/blob/5cd490eba2a3d3d2d0d7dae4f51df8b1ad55e80e/modules/%40angular/router-deprecated/src/directives/router_outlet.ts#L41
fails with
=====> node dist/tools/cjs-jasmine -- {@angular,benchpress}/**/*_spec.js @angular/compiler-cli/test/**/*_spec.js
/home/travis/build/angular/angular/dist/all/@angular/router-deprecated/src/directives/router_outlet.js:162
        { type: Router, },
                ^
ReferenceError: Router is not defined

**Comment by vicb** [comment]
:+1:
