### ISSUE TITLE
ES5 Class support

### ISSUE THREAD

**Issue by jjudd** [angular/tsickle#161]
Does tsickle support classes when TypeScript is configured to output ES5? I have a simple example, that I have not been able to get closure to compile. 

Here is the ts
```typescript
export class Greeter {
    constructor(public greeting: string) { }
    greet(): string {
        return this.greeting;
    }
};
```

It is tsickle'd into this
```javascript
goog.module('foo.greeter');var module = module || {id: 'foo/greeter.js'};
var Greeter = (function () {
    /**
     * @param {string} greeting
     */
    function Greeter(greeting) {
        this.greeting = greeting;
    }
    /**
     * @return {string}
     */
    Greeter.prototype.greet = function () {
        return this.greeting;
    };
    Greeter._tsickle_typeAnnotationsHelper = function () {
        /** @type {string} */
        Greeter.prototype.greeting;
    };
    return Greeter;
}());
exports.Greeter = Greeter;
;
//# sourceMappingURL=greeter.js.map
```

In another file, when I try to annotate something as a `Greeter`, the compiler errors like so `Bad type annotation. Unknown type greeterM.Greeter`

```javascript
goog.require('foo.greeter');
...
        var greeterM = goog.module.get('foo.greeter');

        /** @type {greeterM.Greeter} */
        this.greeter = new greeterM.Greeter("delicious waffles");
```

However, if I configure TypeScript to output ES6, it uses the `Class` keyword in the transpiled JavaScript and everything works.

**Comment by martine** [comment]
No, we support ES6 only.  We rely on the Closure compiler to do the ES6->ES5.

(Note that we *don't* rely on Closure's ES6 module support as it's not complete.)

**Comment by jjudd** [comment]
Good to know. Thanks. ES6 here we come.
