### ISSUE TITLE
getElementById inconsistent between TS and Closure

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#163]
document.getElementById returns an `Element` in Closure and an `HTMLElement` in TS.  (`Element` is the supertype; SVG elements are a sibling to HTML elements.)  This leads to compilation problems like:

```
WARNING - initializing variable
found   : (Element|null)
required: (HTMLElement|null)
    let /** @type {HTMLElement} */ outputEl = document.getElementById('output');
```

https://github.com/Microsoft/TypeScript/issues/3263#issuecomment-105338997 says: "However, in the case of getElementById, we made it convenient by returning HTMLElement by default, although it is different from the spec."  Sadness.

It looks like they might change something in this area in https://github.com/Microsoft/TypeScript/issues/4689 .

See also https://github.com/angular/tsickle/issues/42 .  This is maybe an argument for using our own modified standard library.

**Comment by martine** [comment]
To repro this in a test:

```js
let foo = document.getElementById('foo');
```

it produces

```js
let /** @type {HTMLElement} */ foo = document.getElementById('foo');
```

**Comment by martine** [comment]
Note that you can't work around this with coercions because of bugs like https://github.com/Microsoft/TypeScript/issues/6982 where comments are dropped.

```js
let foo = <Element>document.getElementById('foo');
```
becomes
```js
let /** @type {Element} */ foo = /** @type {Element} */(( <Element>document.getElementById('foo')));
```
becomes
```js
let /** @type {Element} */ foo = (document.getElementById('foo'));
```
And see that "Element" was dropped.

**Comment by mprobst** [comment]
Shouldn't we initially disable type checking within the TypeScript file?
It's nice to have checking for code depending on it, but we don't need the
check in the file – TS has already type checked that, right?

**Comment by martine** [comment]
In theory we're relying on types for optimization, so I'm not sure what it means if we disable type checking.  Like if you write

```js
let foo = document.getElementById('foo');
foo.barField;
```

where "barField" is in HTMLElement but not Element, I'm not sure what the Closure optimizer will do to `barField` when it thinks it's not a valid field.

**Comment by mprobst** [comment]
My unchecked understanding is that Closure Compiler will rename properties
that are never mentioned in externs, but at least without --disambiguate
options will just never rename a property that's mentioned *anywhere* in
your externs.

With it on, it's unclear, there's some stuff in Closure Compiler where it's
trying to be conservative if a sub or supertype defines a property.

**Comment by evmar** [comment]
We suppressed checkTypes.
