### ISSUE TITLE
Support developer mode

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#172]
When developing a TS+Closure project, we should support a mode where we don't do all the type-munging bits but still convert to goog.module.  Like the es5 mode we have within Google right now.

Which means you still want this code:
https://github.com/angular/tsickle/blob/abc8ef129d12490c8c68358446507a5c8e4c2173/src/main.ts#L198
but you skip lines 157 through 186 above it (which are the parts that rely on all the intermodule dependency junk). That's how we do it inside the Google build system.

I think you can just add a tsickle flag for it, like "developermode" or something.

@mprobst I think there's also something about module manifests for devmode. Should this be part of tsickle? What generates the closure deps.js in devmode?

**Comment by mprobst** [comment]
`deps.js` at least used to be created by some Python script (regexps and linked hash maps, you guessed it).

In internal tooling, compilation produces a manifest by doing a topological sort of the .ts files per compilation unit. That's somewhat informed by bazel and its compilation unit concept, so it might not apply outside of that environment.

Maybe it's easier to hook up webpack or so with support for `goog.module`? Alternatively we could open source the toposort and manifest generating, and then also a simple development server using those manifests.

**Comment by martine** [comment]
I actually don't even know how this works when you're just using plain Closure in devmode.  Maybe you don't even need a deps.js because the goog.requires order things for you?  @jjudd, perhaps you could describe your setup more?

**Comment by jjudd** [comment]
For dev (running things uncompiled) our closure js uses depswriter.py (the aforementioned python script) to generate deps.js. When you add, remove, or change names of dependencies you run a make target, which regenerates deps.js using depswriter. 

After speaking with @davityle, our plan is to do something similar for ts. When working in a single file, just use dev mode by transpiling and doing module conversion on save. Then when you change a dependency in a way that requires everything to be regenerated, run a make target that takes care of that.

Ideally, this should result in a fast dev process for ts very similar to our current dev process for js.

**Comment by martine** [comment]
With the above checked-in file, you now can run tsc with the `--noEmitHelpers` flag and then unconditionally add that file to the compilation.

**Comment by evmar** [comment]
We support ES5 emit.
