### ISSUE TITLE
tsickle fails on top level interface without declare in .d.ts 

### ISSUE THREAD

**Issue by davityle** [angular/tsickle#173]
As is documented [here](https://typescript.codeplex.com/wikipage?title=Known%20breaking%20changes%20between%200.8%20and%200.9), 'declare' is now required for top level non-interface declarations in .d.ts files. However tsickle will fail if an interface does not have the declare keyword. For example, while compiling [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jasmine/jasmine.d.ts), tsickle outputs:

```
Error at /home/tylerdavis/lucid/main/cake/app/webroot/ts/helloworld/typings/globals/jasmine/index.d.ts:32:1: A 'declare' modifier is required for a top level declaration in a .d.ts file.
Error at /home/tylerdavis/lucid/main/cake/app/webroot/ts/helloworld/typings/globals/jasmine/index.d.ts:32:19: An implementation cannot be declared in ambient contexts.
Error at /home/tylerdavis/lucid/main/cake/app/webroot/ts/helloworld/typings/globals/jasmine/index.d.ts:39:1: Statements are not allowed in ambient contexts.
```

but then compiles with no errors/warnings if I add the declare keyword on the interface at line 38 of the before mentioned file. 

However, typescript versions 1.8.10, 1.9.x, and 2.0.0 all compile the ts as is without warnings. 

I've traced the error down to [this line](https://github.com/angular/tsickle/blob/master/src/main.ts#L190) in tsickle which, interestingly, is the typescript compiler api, it is specifically `program.getSemanticDiagnostics` that is returning these errors. I tried upgrading the ts version that typescript uses to 1.8.10 and I still get the same errors then. If you feel it would be more appropriate for me to move this issue to the ts compiler I could do that however, I thought that tsickle would want to know that it was failing to compile code that typescript compiled without error.

**Comment by martine** [comment]
Workaround: currently we don't run tsickle on any d.ts files.  d.ts files are purely for TypeScript to typecheck TypeScript code, so we don't need to change them for Closure compilation.

**Comment by evmar** [comment]
I think since the workaround is understood, this is obsolete.
