### ISSUE TITLE
typedefs following another typedef are excluded

### ISSUE THREAD

**Issue by lambertjamesd** [angular/tsickle#175]
```
type TypeA = { bar: number };
type TypeB = { foo: number };
```
That only outputs the first typedef
```
/** @typedef {{bar: number}} */
var TypeA;
var TypeB;
```
Unless you break up the typedefs
```
type TypeA = { bar: number };
var test = 0;
type TypeB = { foo: number };
```
Then it emits both

**Comment by martine** [comment]
I cannot reproduce this.  I pasted your first snippet into `test_files/typedef/typedef.ts` and ran `UPDATE_GOLDENS=1 ./node_modules/.bin/gulp watch` and the resulting JS includes two `@typedef` blocks in it.

**Comment by evmar** [comment]
Ping @lambertjamesd

**Comment by evmar** [comment]
Please reopen if it's still an issue.
