### ISSUE TITLE
Use tsickle from browserify

### ISSUE THREAD

**Issue by tschoartschi** [angular/tsickle#178]
Hey!

It is actually not an issue, it is more a question but I think it could be interesting to other people too. 

I tried to integrate tsickle in my workflow. I use [gulp](https://github.com/gulpjs/gulp) with [browserify](http://browserify.org/) and [tsify](https://www.npmjs.com/package/tsify). With [tsify](https://www.npmjs.com/package/tsify) I can use an alternative typescript compiler ([more details](https://www.npmjs.com/package/tsify#options)). I tried to integrate [tsify](https://www.npmjs.com/package/tsify) with tsickle but I didn't figure out how. I'm also not quite sure if it is possible without rewriting large parts of tsickle. 

It would be great to know if I can use tsickle with my current workflow.

Thanks a lot

**Comment by evmar** [comment]
@jjudd et al are currently the closest to figuring this out.  I hope to put some time into make it easy to use once I fix a few remaining bugs (see the remaining open bug list).

**Comment by kasparsklavins** [comment]
Any progress on this?  Couldn't find a way to run tsickle from gulp.

**Comment by tschoartschi** [comment]
@kasparsklavins I didn't invested much time because @evmar wrote that @jjudd is close to figure this out. I would also be interested if there is any progress on this. It would be great if we could use tsickle like an alternative typescript compile e.g. https://github.com/TypeStrong/ntypescript

**Comment by evmar** [comment]
I have fixed tsickle to work under a browser now, it has no deps.
