### ISSUE TITLE
sickle should strip all comments

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#18]
in file_comments.ts we emit jsdoc before existing comment:

```
/** @return { string} */ // This test verifies that initial comments don't confuse offsets.
 function foo() {
     return 'foo';
 }
```

we should strip all comments, since we already don't emit comments in properties (see comments.ts golden).

**Comment by mprobst** [comment]
I think this is obsolete. It turns out emitting some comments is fine, and useful for downstream code.
