### ISSUE TITLE
Enum members are accessed via dot notation in TS, but the compiled JS requires bracket notation for the closure compiler

### ISSUE THREAD

**Issue by jjudd** [angular/tsickle#188]
We're running into an issue trying to get Angular 2 to work with advanced compilation.

Enums in TypeScript are written and accessed via dot notation like so

```TypeScript
export enum NumberFormatStyle {
  Decimal,
  Percent,
  Currency
}
...
if (style == NumberFormatStyle.Currency) {
```

However, tsickle (due to the TypeScript compiler) produces output like so
```JavaScript
(function (NumberFormatStyle) {
    NumberFormatStyle[NumberFormatStyle["Decimal"] = 0] = "Decimal";
    NumberFormatStyle[NumberFormatStyle["Percent"] = 1] = "Percent";
    NumberFormatStyle[NumberFormatStyle["Currency"] = 2] = "Currency";
})(exports.NumberFormatStyle || (exports.NumberFormatStyle = {}));
```

The bracket notation prevents closure from renaming the member in the enum. The dot notation where the member is accessed is renamed. Accordingly, you end up with something like this after compilation

`$NumberFormatStyle$$.$DECIMAL$`

where `$NumberFormatStyle$$` is something like 
```JavaScript
{
  DECIMAL: 0,
  PERCENT: 1,
  CURRENCY: 2,
  0: "DECIMAL",
  1: "PERCENT",
  2: "CURRENCY"
}
```

**Comment by evmar** [comment]
We have an enum test case here:
https://github.com/angular/tsickle/tree/master/test_files/enum
We attempt to regenerate enums such that they don't have the problematic TypeScript syntax, see enum.tsickle.ts in that directory for the code we generate and pass on to the TypeScript compiler.

There are some more comments about the enum translation here:
https://github.com/angular/tsickle/blob/34ecdf75b1ab0cf301e84296656f42453448cdd3/src/tsickle.ts#L701

Is it possible that is not firing on your input for some reason?  Maybe the "export" is confusing things?

**Comment by jjudd** [comment]
Thank you. You were right. I had a bug in how I was calling tsickle. Closing :)
