### ISSUE TITLE
Turn off typechecking of tsickle output

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#189]
Currently tsickle emits TS code that typechecks.  This is nice because the TS compiler helps us spot our mistakes.

But it has some negative consequences:
- Because tsickle's input must be typechecked, using tsickle forces your builds to typecheck your app twice.
- Some Closure patterns are very difficult to express in legal TS.
  - We use a pretty weird hack for fields (the annotations helper static method) because we can't generate idiomatic Closure constructors.
  - When tsickle introduces a new value to capture a TS type, it's hard to make use of this value across modules.

As far as I understand TypeScript, as long as the code is syntactically valid, TS will generate *something* even if it's type-invalid.  And I think that something is predictable (it's a syntactic transformation of the input).

**Comment by alexeagle** [comment]
Another option is to create a `ts.Program` with most tsickle changes included, type-check that, then make the remaining changes and emit without type-checking again. Just mentioning it to be comprehensive.

**Comment by rkirov** [comment]
In an ideal world, tscikle modifications would happen as part of the emit pipeline (that doesn't exist yet), and will not be typechecked either, so I think this is reasonable as it aligns with long term plans.

**Comment by rkirov** [comment]
In a post typechecking scenario, can we still write tests that assert the type errors happen at particular places but no other, so that we don't accidentally have the emit do something crazy and closure just accepting it and breaking code (as we have seen it do).

**Comment by evmar** [comment]
I will leave this open to implement a variant of Rado's idea.

**Comment by evmar** [comment]
I think what we can do is include the error messages (the errors we ignore, I mean) in a golden file somewhere.
