### ISSUE TITLE
Apply @abstract to classes with @abstract methods

### ISSUE THREAD

**Issue by DavidSouther** [angular/tsickle#194]
tsickle takes

```typescript
abstract class BaseSelector<T> {
  abstract getViewValue(item: T): string {}
}
```

and generates

```javascript
class BaseSelectorComponent {
  /**
   * @abstract
   * @param {?=} item
   * @return {?}
   */
  getViewValue(item) {}
}

which then warns

```
.../commerce/channels/presentation/experimentation/utils/selector/base_selector.js:94: WARNING - Abstract methods can only appear in abstract classes. Please declare the class as @abstract
    getViewValue(item) { }
```

**Comment by rkirov** [comment]
will be fixed with https://reviews.angular.io/D245

**Comment by evmar** [comment]
Fixed in https://github.com/angular/tsickle/commit/b96aa3fc07153695e6c71c23351210be5fa387d5
