### ISSUE TITLE
Newly cloned copy fails with TS2339 on ts.NodeFlags

### ISSUE THREAD

**Issue by hess-g** [angular/tsickle#200]
Just cloned the repo, on two different machines (mac & linux), and got the same result during the run of `npm i`. When the reinstall step runs, the ts compile fails:

src/tsickle.ts(59,39): error TS2339: Property 'Private' does not exist on type 'typeof NodeFlags'.
[11:12:46] 
src/tsickle.ts(59,39): error TS2339: Property 'Private' does not exist on type 'typeof NodeFlags'.

Running tsc by itself throws errors on any line that references a property of NodeFlags in src/tsickle.ts.

**Comment by evmar** [comment]
I just tried to reproduce on my laptop and instead got:

```
-> running reinstall

>> written 10 files:

    - chai/chai.d.ts
    - glob/glob.d.ts
    - google-closure-compiler/google-closure-compiler.d.ts
    - minimatch/minimatch.d.ts
    - minimist/minimist.d.ts
    - mkdirp/mkdirp.d.ts
    - mocha/mocha.d.ts
    - node/node.d.ts
    - source-map-support/source-map-support.d.ts
    - source-map/source-map.d.ts
[08:28:52] Using gulpfile ~/projects/tsickle/gulpfile.js
[08:28:52] Starting 'compile'...
error TS2318: Cannot find global type 'Array'.
[08:28:53] error TS2318: Cannot find global type 'Array'.
```

**Comment by evmar** [comment]
```
$ npm ls | grep typescript
├─┬ gulp-typescript@2.10.0
│ ├── typescript@1.7.3
└── typescript@2.1.0-dev.20160909
```

**Comment by evmar** [comment]
I did `rm -rf typings node_modules` followed by `npm i` and now I also encounter the `Private` problem.

**Comment by evmar** [comment]
It appears the API changed upstream recently, perhaps with the merge of the 'transforms' branch.
I think the problem we have is we need to pin which version of TypeScript we're using more carefully.  @rkirov which version do we want?

**Comment by hess-g** [comment]
The latest versions that are getting pulled in from a clean clone/install:

$ npm ls | grep typescript
├──┬ gulp-typescript@2.13.6
│ └── typescript@1.8.10
└──  typescript@2.1.0-dev.20160909

**Comment by rkirov** [comment]
We want "2.1.0-dev.20160827", current package.json claims `"typescript": "^2.1.0-dev.20160827"` but we should probably pin it (using npm shrinkwrap or just removing '^').
