### ISSUE TITLE
Private name error with using Enum while compiler option "declaration" is true

### ISSUE THREAD

**Issue by rictic** [angular/tsickle#203]
tsickle v0.1.7

`src/foo.ts`
```typescript
export interface NodeTree {
  enumVal?: Enum;
}

export enum Enum { }
```

`tsconfig.json`
```json
{
    "compilerOptions": {
        "declaration": true
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

Yields the error message:

`Error at src/foo.ts:7:13: Property 'enumVal' of exported interface has or is using private name 'Enum'.`

This is the error that would be emitted by `tsc` if `Enum` was not exported. I suspect that tsickle isn't supported with the `declaration` compiler option?

**Comment by evmar** [comment]
Can you give the command line you're running?  I tried to repro this locally and didn't see it.

**Comment by rictic** [comment]
Just `./node_modules/.bin/tsickle` with no args. Will put together a repro repo.

**Comment by evmar** [comment]
Ah I was running tsc!  No repo necessary, completely forgot what repo I was on here.  :)

**Comment by evmar** [comment]
Actually, I still can't repro this.  Super confused.

**Comment by rictic** [comment]
Arg, clearing out my node_modules and reinstalling fixed it. Looks like I had `typescript-2.1.0-dev.20160912` installed locally. Can confirm that it builds clean with v2.02.

Sorry for the noise!
