### ISSUE TITLE
`namespace never provided` error from ES2015 imports in closure code

### ISSUE THREAD

**Issue by rictic** [angular/tsickle#204]
I've got some closure code that uses es2015 modules that I'd like to convert piecemeal to typescript.

`src/index.ts`

``` typescript
export class Greeter {
  greeting = 'hello';
}
```

`src/uses-from-closure.js`

``` javascript
import * as index from './index';

console.log(`${new indexGreeter().greeting} from a closure module`);
```

closure compiler is giving this error:

```
[14:51:31] gulp-google-closure-compiler: /src/uses-from-closure.js:1: ERROR - required "module$$src$index" namespace never provided
import * as index from './index';
^
```

I'm probably running off in the wrong direction, guidance appreciated!

**Comment by rictic** [comment]
Oh, and repro at https://github.com/rictic/tsickle-play/tree/module-import

**Comment by evmar** [comment]
We don't have much experience with ES6 modules in Closure because the Closure team recommends against using them (and say to use goog.module instead). tsickle munges its output to use goog.module so this can only work if the ES6 module import is also somehow compatible with that.  It may be the case that Closure internally uses goog.module underneath its ES6 module transpilation.

You might look at what JS is generated from index.ts to see what module name it ends up using.

**Comment by rictic** [comment]
So at the top of index.js I see:

```javascript
goog.module('.Users.rictic.open.tsickle-play.src.index');
var module = module || {id: '/Users/rictic/open/tsickle-play/src/index.js'};
```

I guess I'd need to generate the corresponding goog.require calls? Or is there a way that I could set a workspace prefix to strip out everything up to `src`?

Taking a different tact, it seems like if tsickle had a full ES6 output mode (no generated `goog.module`, `module`, or `exports`) that appears to work fine for my tests so far.

**Comment by evmar** [comment]
It's possible one of the patches in https://github.com/angular/angular/issues/8550#issuecomment-240823155 is necessary to make this work right.  I haven't had a chance to look through them, been slammed with Google internal stuff. :~(

**Comment by rictic** [comment]
So, poking around with it, would a PR like https://github.com/rictic/tsickle/commit/5c1db546cc3560fe5877c20e3207d3472dee34af be welcomed?

It adds a new flag `--nativeModules` (bikeshedding welcome), and when it's given tsickle doesn't mess with modules, and just follows the `modules` tsc option. After a little poking around it seems to just solve things for my use case, producing:

`index.js`
```javascript
export class Greeter {
    constructor() {
        this.greeting = 'hello';
    }
    static _tsickle_typeAnnotationsHelper() {
        /** @type {string} */
        Greeter.prototype.greeting;
    }
}
```

**Comment by evmar** [comment]
The change looks good, but I'm not quite sure how it compiles with Closure.  Do you then use Closure's ES6 module support?

**Comment by rictic** [comment]
Yeah. We've got an [existing open source project](https://github.com/webcomponents/shadycss) that's been using es6 modules with jscompiler. We've had to file a bug or two but it seems to be working pretty well at the moment.

Any preference or advice for testing this change? Maybe have goldens both with and without this setting?

**Comment by evmar** [comment]
Hm, we have a testing precedent where the directory name can contain a ".untyped" to flip a flag, so maybe add a ".nativeModules" test or something?  Grep for the former to find it, it's pretty hacky.

**Comment by evmar** [comment]
I think we're not planning to support ES modules, given that you cannot concat them in devmode.
