### ISSUE TITLE
Handle optional arguments before required

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#209]
``` js
function foo(x = true, y: boolean) {}
```

This is legal TS but Closure warns that optional args must be at the end.  We should identify that x is non-optional due to y being required and generate a signature that doesn't rely on optional.

**Comment by mprobst** [comment]
Just marking them non-optional is sadly not sufficient – JSCompiler understands parameters with ES6 default values to be optional (`function f(x = 1, y) {}`) and complains for those. I think we'll have to make this configurable in JSCompiler.

**Comment by evmar** [comment]
Another idea is to fix this in TS, since the original code is nonsense anyway.

A third approach is to make tsickle reject it.

**Comment by evmar** [comment]
I searched on the TS bug tracker for something about this but failed; maybe you could try (maybe you'll use different keywords?)?

**Comment by evmar** [comment]
If JSCompiler always complains on `function f(x = 1, y) {}` then it's a bug in JSCompiler.

**Comment by mprobst** [comment]
@evmar it always gives a warning. It turns out some projects turn all warnings into errors, and you were not able to disable this particular warning. Sent them a CL to allow disabling that warning.

**Comment by rkirov** [comment]
someone just broken internally, because the warning is promoted to error in some setups.

**Comment by alexeagle** [comment]
I agree it seems like an upstream issue.
https://github.com/google/closure-compiler/issues/2314

I think Martin meant that we should send a CL, not that he already sent one. I'll look.

**Comment by alexeagle** [comment]
was fixed in 52701c12db53969c549c1e19d6001418f43e3cc2
