### ISSUE TITLE
Debugger in vscode fails with "Attribute 'program' does not exist"

### ISSUE THREAD

**Issue by hess-g** [angular/tsickle#214]
Running the debugger in VSCode results in the following error:
"Attribute 'program' does not exist ([workspace_root]/node_modules/gulp-mocha/node_modules/mocha/bin/_mocha).
(root path is correctly expanded)

Change to: 
"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha"
and the debugger runs as expected.

Repro'd in freshly cloned project.

**Comment by evmar** [comment]
Weird, this used to work and "npm ls" shows that mocha is inside gulp-mocha:
```
├─┬ gulp-mocha@2.2.0
│ ├─┬ mocha@2.5.3
```
but it's clearly where you say it is.  I clearly don't understand npm.

**Comment by hess-g** [comment]
And an interesting oddity - You have to run "gulp test" at least once on a newly cloned repo, and then the debugger works with this new path. Note that it never worked with the old path, at least not for me.

**Comment by hess-g** [comment]
The npm ls shows dependencies. npm makes some judgement calls at install time as to whether a particular dependency needs to be physically installed or not. In this repos case, mocha is getting installed at the root packages level, and therefore is already present for gulp-mocha to use. I've tried to find definitive docs on the algorithm, but they didn't come up on a cursory look.

**Comment by hess-g** [comment]
Fixed by #215.
