### ISSUE TITLE
Method overload check needs to use hasOwnProperty

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#216]
https://github.com/angular/tsickle/blob/6bdd1eaba35a7aed655f7296aaafaa751391de8c/src/tsickle.ts#L922

This does the wrong thing on methods named `valueOf` .

@hess-g

**Comment by hess-g** [comment]
Ack. Fix in progress.

**Comment by evmar** [comment]
I got it, one sec

**Comment by hess-g** [comment]
Standing down. Thanks. I took the target=es5 in tsconfig.json a little too literally.
