### ISSUE TITLE
Angular extends builtin types in externs that we don't have externs for

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#220]
Angular extends NumberConstructor and PromiseConstructor:
https://github.com/angular/angular/blob/44da4984f900c2d6dfe582f4417332cae88cff94/modules/es6-subset.d.ts#L47

When generating externs for that file, Tsickle looks at NumberConstructor and sees that it's already been defined elsewhere, so it skips the definition.  But that "elsewhere" is in the TypeScript builtin d.ts, which we don't generate externs for.  The result is:

```
ERROR - variable NumberConstructor is undeclared
NumberConstructor.prototype.isInteger = function(number) {};
^
```

In the Closure es6 externs it looks like they define these properties on `Number`, not `NumberConstructor` (the latter doesn't exist in any Closure externs).

Another way of looking at this bug is that it's caused by divergence between TS d.ts and Closure externs for some builtin types.

**Comment by evmar** [comment]
@alexeagle it looks like you created this file.  Do you have any thoughts on whether it will continue to exist?  I might need to do some gross workarounds.

**Comment by alexeagle** [comment]
I can pick this up again.

**Comment by evmar** [comment]
The Angular issue is https://github.com/angular/angular/issues/5242 .  I'm gonna close this in favor of that.  Within Google the workaround is to not generate externs for this file.
