### ISSUE TITLE
Add a comment each time tsickle modifies the source in a weird way

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#222]
It'd be neat if we had a predictable doc-comment format for all tsickle modifications.  For example we sometimes rename function arguments or introduce new methods and so on.  We ought to tag these with some @tsickle docstring so they're easy to spot.

Tsickle output isn't intended to be human-readable but in practice you end up needing to read it sometimes to debug things.

**Comment by hess-g** [comment]
+1 to this. I'll add any additional possible changes required when I get through the parameter name|type|return changes that are required (if any) for overloads.

**Comment by evmar** [comment]
I still think we should do this, but we don't need a bug about it.
