### ISSUE TITLE
Tsickle generates invalid externs on [Symbols]

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#223]
``` js
interface Symbol {
  [Symbol.toStringTag]: 'Symbol';
}
```

produces invalid externs.

**Comment by hess-g** [comment]
Is there an import required prior to this snippet? I get "Cannot find name 'Symbol'" if I just add this to .ts file.
![image](https://cloud.githubusercontent.com/assets/12832244/18748185/1913bcbe-809f-11e6-9e12-75b4144472f5.png)

**Comment by evmar** [comment]
Reduced it too far, oops!  It looks like Symbol comes from the ES6 typings; in blaze we now bring them in with deps, not sure how to bring them in in the tsickle unit tests.  Hmm.
