### ISSUE TITLE
Linting on current master/HEAD fails on clang-format 1.0.45 

### ISSUE THREAD

**Issue by hess-g** [angular/tsickle#225]
package.json had clang-format ^1.0.43, so dev without cleaning node_modules left it at 1.0.44.

Multiline getter function format is being enforced. This is failing travis tests on PRs, and fails on a freshly cloned repo. Example:

![image](https://cloud.githubusercontent.com/assets/12832244/18752483/819d22e6-80b0-11e6-81f5-1cf6fd8e819b.png)

**Comment by hess-g** [comment]
clang-format latest update is 1.0.45; this test passed in .44.

**Comment by evmar** [comment]
I wonder if the broader fix is to pin the clang-format version to a
specific version, rather than saying 1.0.45 "or above".

**Comment by hess-g** [comment]
Well, I guess it depends on whether you want to always have the latest rules in place, or get stuck on a stale version and have to manually update. The bigger problem (general to npm) is doing periodic clean `npm i` so that you pick up the latest "greater than" versions of everything. I added #227 with output from `david`. Perhaps we could just integrate that into the test flow, so that the existence of newer versions was at least highlighted. Then pinning to a specific version of something would make more sense.

**Comment by evmar** [comment]
Normally it should be safe to update minor versions.  I think
clang-format's versioning is just weird.  Given that it will break us any
time it updates, it's fine to pin it to a specific version and update
manually -- we'll need to rebaseline any time we update anyway.

**Comment by mprobst** [comment]
Well, clang-format's API has never changed with these updates, it's just
the formatting it does that changes. I think we kind of over-test here, the
correct way to lint formatting would be to make sure that the new/changed
lines format correctly with the latest clang-format. But we don't really
have infrastructure in place to do that :-(

**Comment by hess-g** [comment]
And this wasn't new/changed lines, it was existing files at HEAD that then fell out of compliance with the newer formatting rules. This would have been caught a little earlier if there was a periodic (nightly? twice-daily?) travis build kicked off automatically against head . Could be interesting to set that up. Separately, it could be a good maintainer practice to periodically run david on a fresh clone, update everything, and note what breaks. I'm doing that now on #227; PR coming later this AM.

**Comment by mprobst** [comment]
Obsolete?
