### ISSUE TITLE
dep version update options (as of 22 Sep 2016)

### ISSUE THREAD

**Issue by hess-g** [angular/tsickle#227]
Current output from [david](https://david-dm.org/angular/tsickle?view=list)

dependencies:
![image](https://cloud.githubusercontent.com/assets/12832244/18754762/ceabb1c2-80b7-11e6-940a-5face8cf1cdd.png)

devDependencies:
![image](https://cloud.githubusercontent.com/assets/12832244/18754767/d2dd633a-80b7-11e6-88a5-884f51dea08b.png)

**Comment by hess-g** [comment]
All of the out of date deps listed above can be updated, with the exception of closure. Attempting to update to the latest (2016911.0.0) yields the following errors on `gulp test`:
```
test_files/jsdoc_types/jsdoc_types.js:29: ERROR - Bad type annotation. Unknown type module$contents$test_files$jsdoc_types$jsdoc_types_RenamedClassTwo
let /** @type {RenamedClassTwo} */ useLocalClassRenamedTwo = new module2_3.ClassTwo();
               ^
test_files/jsdoc_types/jsdoc_types.js:31: ERROR - Bad type annotation. Unknown type module$contents$test_files$jsdoc_types$jsdoc_types_Interface
let /** @type {Interface} */ useLocalInterface = null;
               ^
test_files/jsdoc_types/jsdoc_types.js:32: ERROR - Bad type annotation. Unknown type module$contents$test_files$jsdoc_types$jsdoc_types_ClassWithParams
let /** @type {ClassWithParams<number>} */ useClassWithParams = null;
               ^
3 error(s), 0 warning(s)
```

**Comment by hess-g** [comment]
tslint is currently at a stable 3.15.1. On `npm i`, a warning about unmet peer dependencies is shown, since we are using a dev version of typescript. This is a warning only; tslint latest is installed and works just fine.

**Comment by evmar** [comment]
Looks like everything's updated except for Closure.  I opened a new bug for that.
