### ISSUE TITLE
Warn when properties are accessed through ['literal']

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#23]
Typescript allows property access with square brackets and string literal to access regular properties (ref https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.13)

so the following is valid TS

``` typescript
class A {
  foo: string;
}

var a: A;
var b = a['foo'];
```

but this will fail spectacularly post minification with closure.

**Comment by martine** [comment]
This feature is quite weird.  If you create an intermediate variable (`let foo = 'foo';`) you cannot index into `A` with it (like `A[foo]`) -- it only allows string literals.

**Comment by mprobst** [comment]
Does it output a quoted access, or a non quoted? If it compiles into non
quoted, it'd actually be fine.

Evan Martin <notifications@github.com> schrieb am Fr., 18. März 2016, 09:23:

**Comment by martine** [comment]
It outputs quoted.

**Comment by martine** [comment]
Got a CL ready that checks this.  I am pretty scared I'm accidentally warning on some other, legal thing, so I think I want to put this behind a temporary flag.

**Comment by martine** [comment]
Another antipattern I spotted in the same vein:

```js
let data: {[key: string]: string} = {
  foo: "bar",
};
```

I think you need to quote `foo` to prevent it from being renamed.

**Comment by evmar** [comment]
If you have an `any`, perhaps we should require to use quoted accessors?

**Comment by mprobst** [comment]
Depends on the expected use of any, I guess? But sounds reasonable, if you
want actual properties, you can still cast to the actual type. We'd have to
see what the impact on a large code base would be.

**Comment by rkirov** [comment]
Randomly stumbled on this bug, through our documentation. Current status is that this is handled by 'https://tsetse.info/property-renaming-safe'
