### ISSUE TITLE
Consider using 'make' to build

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#231]
Since it's Friday I thought I'd cook up a makefile-based replacement for gulp.

https://github.com/angular/tsickle/compare/make?expand=1

It's nice to not need to install a zillion npm packages.  And it's also nice to understand what the build is doing by watching it execute commands.  I dunno if it's worth switching to though.

**Comment by b-strauss** [comment]
I don't know how up-to-date this issue is. But I would like to point out that using 'make' would make it more complicated to test on Windows.

**Comment by evmar** [comment]
Yeah, you are right.  Thanks for the reminder.  I will just abandon my branch.
