### ISSUE TITLE
'npm i' fails

### ISSUE THREAD

**Issue by MatrixFrog** [angular/tsickle#234]
Maybe what I'm doing wrong is obvious to experienced npm users. I just cloned the repo, cd'd to it, and ran `npm i`:

[npm-debug.log.txt](https://github.com/angular/tsickle/files/509758/npm-debug.log.txt)

tsickle$ npm i
npm WARN package.json tsickle@0.1.7 No bin file found at build/src/main.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN peerDependencies The peer dependency typescript@>=1.7.3 included from tslint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> tsickle@0.1.7 prepublish /usr/local/google/src/tsickle
> gulp compile

[16:41:33] Using gulpfile /usr/local/google/src/tsickle/gulpfile.js
[16:41:33] Starting 'compile'...
[16:41:35] Finished 'compile' after 2.49 s
npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/usr/local/google/home/tbreisacher/.nvm/versions/node/v4.4.7/bin/node" "/usr/local/google/home/tbreisacher/.nvm/versions/node/v4.4.7/bin/npm" "i"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@2.1.0-dev.20160827 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.15.1 wants typescript@>=1.7.3
npm ERR! peerinvalid Peer gulp-typescript@3.0.2 wants typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/google/src/tsickle/npm-debug.log

**Comment by evmar** [comment]
I am terrible at node stuff but my understanding is that you also need to "npm i typescript".  (It's a "peer dependency" I guess.)

**Comment by MatrixFrog** [comment]
tsickle$ npm i typescript
npm ERR! Linux 3.13.0-95-generic
npm ERR! argv "/usr/local/google/home/tbreisacher/.nvm/versions/node/v4.4.7/bin/node" "/usr/local/google/home/tbreisacher/.nvm/versions/node/v4.4.7/bin/npm" "i" "typescript"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@2.0.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.15.1 wants typescript@>=1.7.3
npm ERR! peerinvalid Peer gulp-typescript@3.0.2 wants typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/google/src/tsickle/npm-debug.log

**Comment by evmar** [comment]
Ah I think the TS 2.0 release broke things.  Let me fix, one sec.

**Comment by evmar** [comment]
https://github.com/angular/tsickle/pull/235

**Comment by evmar** [comment]
Try syncing, `rm -rf node_modules`, and `npm i` again.
