### ISSUE TITLE
Tsickle doesn't have drop-in compatibility with tsc

### ISSUE THREAD

**Issue by berickson1** [angular/tsickle#242]
I have a typescript react-native project and am trying to integrate tsickle.

I have a stripped down example of the project at https://github.com/berickson1/ReactNativeTS/tree/tsickle

Running `npm build`  results in a bunch of errors that don't occur when using the typescript compiler directly. (change 'build' script to call 'tsc' instead of 'tsickle')

I've tried a whole bunch of different things and can't seem to make tsickle compile my code

Errors:

Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:1:8: Import declaration conflicts with local declaration of 'React'
Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:2:14: Cannot find name 'NeverTypeCheckMe'.
Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:2:33: Block-scoped variable 'React' used before its declaration.
Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:3:10: Import declaration conflicts with local declaration of 'View'
Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:3:16: Import declaration conflicts with local declaration of 'Text'
Error at /src/ReactNativeTS/src/components/HelloWorld/index.tsx:4:13: Cannot find name 'NeverTypeCheckMe'.

**Comment by evmar** [comment]
This was just fixed, https://github.com/angular/tsickle/commit/2b323fc8e12a97f82a4dcc7178c625029f61e290
Can you try git version and let us know?

**Comment by berickson1** [comment]
That fixes the errors listed above and makes my sample project compile.  It still breaks on my real project.

I'm importing @types/whatwg-fetch to get the definition for fetch into Window.  I get the following errors:

Error at MyClient.ts:5:39: Cannot find name 'Response'.
Error at MyClient.ts:24:24: Cannot find name 'RequestInit'.
Error at MyClient.ts:30:28: Cannot find name 'fetch'.


```
import * as _ from 'lodash';
import xml2js from 'xml2js';

export default class MyClient {
    // Foo
    static getDataOne(endpoint: string): Promise<Object> {
        return this._makeRequest(endpoint);
    }

    static getDataTwo(endpoint: string): Promise<Object> {
        return this._makeRequest(endpoint);
    }

    static getDataThree(endpoint: string): Promise<Object> {
        return this._makeRequest(endpoint);
    }

    static sendOne(endpoint: string): Promise<Object> {
        // Foo
        return this._makeRequest(endpoint);
    }

    private static async _makeRequest<T>(url: string): Promise<T> {
        const options: RequestInit = {
            method: 'GET',
            headers: {
                'Authorization': 'AuthData'
            }
        }
        const data = await fetch(url, options);

        const text = await data.text();
        return new Promise<T>((resolve, reject) => {
            xml2js.parseString(text, { explicitArray: false }, (err, result) => {
                if (result) {
                    resolve(result);
                }
                if (err) {
                    reject(err);
                }
            })
        });
    }
}
```

**Comment by evmar** [comment]
Can you provide the command line that successfully builds your project, the command line that fails, and the tsconfig.json?

**Comment by berickson1** [comment]
Check out https://github.com/berickson1/ReactNativeTS/tree/tsickle2
Make sure to maually npm link in the latest git tsickel

Running 'npm run build' runs tsickle
Running 'npm run buildts' runs tsc compiler

tsickle can't find fetch
tsc compiler is happy
