### ISSUE TITLE
Angular 2 compilation works with tsc and ngc but not tsickle

### ISSUE THREAD

**Issue by RoxKilly** [angular/tsickle#244]
I'm new to build tools in general, so I'm probably making a silly error. Ask for more info and I'll provide.

I have an `Angular 2` application written in `typsecript 2`. I can use `tsc` to compile it without problem. I'm now trying to optimize:
```
Typescript >> Ahead-of-Time compiler (ngc) >> tsickle >> google-closure-compiler-js
```
My `dev/main.ts` (bootstrap file for my Angular 2 app):
```
1| //import dependencies (core-js, zone.js, reflect-metadata)
2| import 'core-js';
3| import 'reflect-metadata';
4| import 'zone.js';
5| // AHEAD-OF-TIME COMPILATION
6| import {platformBrowser} from '@angular/platform-browser';
7| import {AppModuleNgFactory} from '../aot/dev/app/app.module.ngfactory' //generated code
8| platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
After I've run `ngc` (successfully), I'm not sure how to properly use `tsickle`. I've tried:
```
"node_modules/.bin/tsickle" -- -p ./
```
> Error at /dev/main.ts:6:9: Import declaration conflicts with local declaration of 'platformBrowser'
Error at /dev/main.ts:7:24: Cannot find name 'NeverTypeCheckMe'.
Error at /dev/main.ts:7:43: Block-scoped variable 'platformBrowser' used before its declaration.
Error at /dev/main.ts:8:9: Import declaration conflicts with local declaration of 'AppModuleNgFactory'
Error at /dev/main.ts:9:27: Cannot find name 'NeverTypeCheckMe'.
Error at /dev/main.ts:9:46: Block-scoped variable 'AppModuleNgFactory' used before its declaration.

What's causing these errors? There is no local declaration, so how can it conflict with imports?

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "./dist",
    "baseUrl": "."
  },
  "compileOnSave": false,
  "files": ["./dev/main.ts","./dev/app/custom.typings.d.ts"]
}
```

**Comment by evmar** [comment]
This was just fixed, 2b323fc
Can you try the git version and let us know?

**Comment by RoxKilly** [comment]
@evmar I'd be happy to. Can you tell me how or link to a useful guide? As I said in the OP I'm new to build tools (eager to learn) so I've only ever installed using `npm install tool --save-dev`

I thought maybe I could just download files from here and replace everything in `node_modules/tsickle` but there is no beta release on [the release page](https://github.com/angular/tsickle/releases).

I see a `Download zip` option on the project profile page. If that's what I should get, please tell me which branch to try

**Comment by RoxKilly** [comment]
I replaced the contents of `node_modules/tsickle` with everything in the downloaded zip of the master branch.  When I run `tsickle`, I get:

> Error: Cannot find module 'node_modules\tsickle\build\src\main.js'

The file in question -- `main.js` -- does not exist. As i pointed out in my last post, the `build/` directory is missing altogether from the master branch.  I tried to transpile the contents of `node_modules/tsickle/src` but received a lot of errors, 

Please tell how I can get the build files to test as you requested, or give a download link.

**Comment by RoxKilly** [comment]
I was able to get the contents of `build/` and `node_modules/` directories by:

1. Cloning this repository
2. Running `npm install`
3. Running gulp task `compile`

I then copied the two directories and replaced the matching dirs in my project:
- node_modules/tsickle/build
- node_modules/tsickle/node_modules

Once I succeeded, The compilation completed without raising any error.
