### ISSUE TITLE
tsickle transpiles Angular 2 app, but closure compiler cannot process result

### ISSUE THREAD

**Issue by RoxKilly** [angular/tsickle#245]
I have an `Angular 2` typescript project. Here is the bootstrap file:
**main.ts**

```
import {platformBrowser} from '@angular/platform-browser';
import {AppModuleNgFactory} from '../aot/dev/app/app.module.ngfactory' //generated code
import {enableProdMode} from '@angular/core';
enableProdMode();
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory).catch(e=>console.error(e));
```

I used `Angular 2`'s Ahead-of-Time compiler to generate `ngfactory.ts` files.  I then ran `tsickle` to transform my files into Google Closure Compiler compatible JS. This completed without difficulty:

```
"node_modules/.bin/tsickle" -- -p ./
```

Here is the result:
**main.js**

```
goog.module('C_.websites.learn.angular2.dev.main');var module = module || {id: 'C:/websites/learn/angular2/dev/main.js'};
import { platformBrowser } from '@angular/platform-browser';
var platformBrowser = platformBrowser; /* local alias for Closure JSDoc */
import { AppModuleNgFactory } from '../aot/dev/app/app.module.ngfactory';
var AppModuleNgFactory = AppModuleNgFactory; /* local alias for Closure JSDoc */ //generated code
import { enableProdMode } from '@angular/core';
var enableProdMode = enableProdMode; /* local alias for Closure JSDoc */
enableProdMode();
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory).catch(function (e) { return console.error(e); });
```

Finally, I tried to use [`google-closure-compiler-js`](https://github.com/google/closure-compiler-js/blob/master/README.md) to create a gulp task that bundles all JS into one file.
**gulpfile.js**

```
const closureCompiler = require('google-closure-compiler-js').gulp();
gulp.task('closure-compiler', function() {
    return gulp.src('./dev/main.js')
        .pipe(closureCompiler({
            compilationLevel: 'SIMPLE',
            warningLevel: 'VERBOSE',
            outputWrapper: '(function(){\n%output%\n}).call(this)',
            jsOutputFile: 'build.js',
            createSourceMap: false
        }))
        .pipe(gulp.dest(appProd));
});
```

The task fails immediately with many errors. Here is a sample:

> dev\main.js:3 (JSC_REFERENCE_BEFORE_DECLARE)
> Variable referenced before declaration: module$contents$C_$websites$learn$angular2$dev$main_platformBrowser
> 
> dev\main.js:5 (JSC_REFERENCE_BEFORE_DECLARE)
> Variable referenced before declaration: module$contents$C_$websites$learn$angular2$dev$main_AppModuleNgFactory
> 
> dev\main.js:7 (JSC_REFERENCE_BEFORE_DECLARE)
> Variable referenced before declaration: module$contents$C_$websites$learn$angular2$dev$main_enableProdMode
> 
> dev\main.js:10 (JSC_POSSIBLE_INEXISTENT_PROPERTY)
> Property bootstrapModuleFactory never defined on ?
> 
> dev\main.js:3 (JSC_INTERNAL_ERROR_UNEXPECTED_TOKEN)
> Internal Error: TypeCheck doesn''t know how to hanle IMPORT
> 
> dev\main.js:3 (JSC_INTERNAL_ERROR_UNEXPECTED_TOKEN)
> Internal Error: TypeCheck doesn''t know how to handle IMPORT_SPECS
> ...

I'm using the latest source cloned from github as of Oct 10, 2016, along with `"google-closure-compiler-js": "^20160916.0.0"`.  Am I missing a step?

**Comment by RoxKilly** [comment]
Someone involved with the `google-closure-compiler` project explained that the [closure compiler cannot resolve](http://stackoverflow.com/questions/39971384/angular-2-transpiled-with-tsickle-cant-be-processed-by-google-closure-compiler?noredirect=1#comment67242047_39971384) those import statements in my `main.js` above.

My understanding of `tsickle` is that it produces code ready to be processed by closure compiler (as mentioned in [this Angular video](https://www.youtube.com/watch?v=_VnV7R4Ncwc) from 23:15 to 24:15. Am I missing a step?

**Comment by alexeagle** [comment]
Sorry, you are possibly the first user outside of Google or Lucidchart to try to put these pieces together. There are some sharp, undocumented edges and no official support or examples for doing it.

One likely problem here is that tsickle needs commonjs require() statements to turn them into `goog.require` so you need your `tsconfig.json` to have `--module=commonjs`

**Comment by RoxKilly** [comment]
@alexeagle  thanks. I think I'm better off waiting for the tool to mature

**Comment by evmar** [comment]
Obsolete.
