### ISSUE TITLE
Move __decorate calls to the end of the compiled file

### ISSUE THREAD

**Issue by tomsdev** [angular/tsickle#275]
The code below breaks the compilation (but runs well without Tsickle). The problem happens only when __decorate calls are generated (when using a decorator for example). If a class A reference a class B and vice versa then the __decorate call try to use class B before it was declared.

My proposed solution is to move all the __decorate calls to the end of the file (after all the classes have been declared) instead of after each class declaration.

TypeScript source:
```
function sampleDecorator() {
  return (target: any, propertyKey: string) => { };
}

class A {
  @sampleDecorator()
  foo(b: B) {}
}

class B {
  @sampleDecorator()
  bar(a: A) {}
}
```

Tsickle generated code:
```
class A {
    /**
     * @param {?} b
     * @return {?}
     */
    foo(b) { }
}
__decorate([
    sampleDecorator(), 
    __metadata('design:type', Function), 
    __metadata('design:paramtypes', [B]), 
    __metadata('design:returntype', void 0)
], A.prototype, "foo", null);
class B {
    /**
     * @param {?} a
     * @return {?}
     */
    bar(a) { }
}
__decorate([
    sampleDecorator(), 
    __metadata('design:type', Function), 
    __metadata('design:paramtypes', [A]), 
    __metadata('design:returntype', void 0)
], B.prototype, "bar", null);
```

**Comment by mprobst** [comment]
This works for one file, but will break if you have classes that are
referenced across multiple modules. I think the only real way to fix this
is to change the decorators to accept what we call a "forwardRef" in
Angular, i.e. take an arrow function that returns the referenced type, so
it can be evaluated later: "() => A" and "() => B" in this example. That
requires a change in the decorator's definiton to handle such closures
though.

**Comment by evmar** [comment]
I think we will revisit decorators once TS upstream revisits them.
