### ISSUE TITLE
Module Imports That Only Use Typing Information Removed from Closure Input

### ISSUE THREAD

**Issue by TiernanGarsys** [angular/tsickle#277]
While working on a Typescript component, I imported a module for the purpose of referencing its exported interfaces in my code's type annotations. When I attempted to compile this code, however, I ran into a number of issues where the Closure compiler failed to recognize the fields contained within these interfaces. After discussing with others, it appears the likely issue is that the module import is dropped when generating the Closure JS (as only type information is used from the file), and so the Closure compiler does not know what to do with it.

I've managed to work around this via two different suggestions

1.) Export a dummy variable from the imported module, and import it in the client code, so that the module isn't dropped in the TS > Closure conversion.
2.) Declare the field using the imported type as "Type | undefined", and then wrap all uses of the field in a check that the field is not undefined. I am not totally sure why this works.

Either of these seems to work independently.

**Comment by evmar** [comment]
We have now fixed this -- we emit `goog.requireType()` on type-only imports and Closure understands it.
