### ISSUE TITLE
rest parameter needs to appear in type annotation

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#280]
compiling rxjs with closure compiler fails:
```
third_party/javascript/node_modules/rxjs/v5_0_0_rc_2/src/operator/zip.js:12:
Originally at:
third_party/javascript/node_modules/rxjs/v5_0_0_rc_2/src/operator/zip.ts:37: ERROR - Missing "..." in type annotation for rest parameter.
```

because:
```
/**
 * @param {?} args
 * @return {?}
 */
function withLatestFrom(...args) {
    let /** @type {?} */ project;
    if (typeof args[args.length - 1] === 'function') {
        project = args.pop();
    }
    const /** @type {?} */ observables = (args);
    return this.lift(new WithLatestFromOperator(observables, project));
}
```

**Comment by evmar** [comment]
tsickle has support for annotating these parameters:
https://github.com/angular/tsickle/blob/3571f6ff4482e78303470d0d31edc43fb7933ac8/src/tsickle.ts#L191

but only in typed mode.

I suspect we need to slowly move tsickle's "untyped" mode to still put some type info in the params; this is also the problem in #274 and #272.

**Comment by alexeagle** [comment]
So maybe the slow migration to "typed" mode could simply be that we turn on one language feature at a time unconditionally? I could send a PR to produce the type annotation just for this varargs case, which is blocking me.
Then I see how lucky I get with a global presubmit?

**Comment by evmar** [comment]
Yes, that seems about right.  Skimming the code I can't quite spot the place to change this, but it will be some check for `.untyped` that early exits.

**Comment by evmar** [comment]
We have a test that covers this nearly exactly -- a rest param in untyped mode.  It generates this code:

```js
/**
 * @param {...?} a
 * @return {?}
 */
function TestSplat3(...a) {}
```

**Comment by evmar** [comment]
...ohhhh, but this is related to how we handle overloads, never mind.  Got it.

**Comment by evmar** [comment]
```js
export function withLatestFrom<T, R>(this: Observable<T>, ...observables: Array<ObservableInput<any> | ((...values: Array<any>) => R)>): Observable<R>;
export function withLatestFrom<T, R>(this: Observable<T>, array: ObservableInput<any>[]): Observable<R>;
export function withLatestFrom<T, R>(this: Observable<T>, array: ObservableInput<any>[], project: (...values: Array<any>) => R): Observable<R>;
export function withLatestFrom<T, R>(this: Observable<T>, ...args: Array<ObservableInput<any> | ((...values: Array<any>) => R)>): Observable<R> {
```

I have no idea what Closure type we even *want* to give to this function!

**Comment by evmar** [comment]
OK I have gone in a bunch of circles here, but finally reduced it to just this:

```js
function TestThisAndRest(this: string, ...params: any[]) {}
```

The problematic tsickle code is:
```js
      // Iterate through both the AST parameter list and the type's parameter
      // list, as some information is only available in the former.
      for (let i = 0; i < sig.parameters.length; i++) {
        let paramNode = fnDecl.parameters[i];
        let paramSym = sig.parameters[i];
```

These two arrays are not in sync in the case of `this` types, so we get confused and generate the wrong type.

See also #274.

**Comment by evmar** [comment]
Note: in looking into this bug I discovered that tsickle completely ignores overloaded functions (it just types the function that has the body) but that is orthogonal to the issue discussed here.
