### ISSUE TITLE
Rewrite Tsickle to use TypeScript v2.1 transforms

### ISSUE THREAD

**Issue by mhevery** [angular/tsickle#285]
Currently Tsickle does not use TypeScript v2.1 transforms API. The consequence is that `ngc` has to parse the type information twice. Once for the original source code, and then again when `tsickle` pulls annotations into static fields. The consequence of this is slower runtime performance.

**Comment by evmar** [comment]
Did they expose the transforms API to external users?  Last I heard this was an internal-only API.

**Comment by mhevery** [comment]
My understanding from discussing with @chuckjaz is that it will be available in v2.1.

**Comment by mprobst** [comment]
@chuckjaz do you have a pointer to docs on it?

**Comment by evmar** [comment]
I just checked the TS source and the transforms stuff is still marked @internal.

https://github.com/Microsoft/TypeScript/blob/012159b25db2b0aa77690d984ee4c35bd7ef2b56/src/compiler/transformer.ts#L14

**Comment by evmar** [comment]
Depends on #295 first.

**Comment by evmar** [comment]
Last news on this is that they anticipate exposing transforms in the next few weeks, but it'll be in a later TS release.  We can wait.

**Comment by shlomiassaf** [comment]
Seems like 1 more thing left for this transformer API.

See [this comment](https://github.com/Microsoft/TypeScript/pull/11561#issuecomment-273984567)

**Comment by tycho01** [comment]
As I understand it their alternative PR for this has been [merged](https://github.com/Microsoft/TypeScript/pull/13940) by now. Hope that could unblock this for those AoT lambdas! @chuckjaz @mhevery

**Comment by evmar** [comment]
We need to migrate tsickle to TS 2.3 for this new API.  Historically that's taken a small amount of work to adjust to API changes but I haven't looked yet at how hard it will be.

**Comment by tycho01** [comment]
With the TS upgrade down (#471) I guess this is unblocked now.

**Comment by evmar** [comment]
Fixed.
