### ISSUE TITLE
Optional fields with any type not handled correctly 

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#287]
Currently tscikle translates 

```ts
interface I {
  a?: any
}
```
to 

```javascript
/** @record */
function I(){};

/** @type {?} */
I.prototype.a;
```

That is a problem because the following code passes TS, but errors in closure:
``` let x: I = {}``` translated to:
```
/** @type {I} */
var x = {};
```

For closure, tsickle should output:

```
/** @type {?|undefined} */
I.prototype.a;
```

Admittedly, one might expect '? | T' to be always the same as '?', so this might be a closure bug? 

//cc @dpurp

**Comment by dpurp** [comment]
Not sure why I didn't think of this before, but It looks like explicitly adding `|undefind` in the type works.  

Example:

```typescript
interface MyInterface {
  anyData: any|undefined;
}
