### ISSUE TITLE
getDocumentationComment no longer returns @Annotation for annotations

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#313]
We rely on sym.getDocumentationComment() to get the JSDoc on decorators to determine that they are annotations.  In TS 2.1 it's now the case that getDocumentationComment() does not return the text of JSDoc tags.  So the @Annotation is dropped.

I traced the code and found inside the compiler:
```js
        return map(getJSDocs(node), doc => doc.comment);
```
where doc.comment is empty; we need doc.tags.

I looked at the API for a while and didn't see an easy way to get at the JSDoc we need.  We might need to change this code to use tsickle's own jsdoc parser.

Blocks #295.

**Comment by evmar** [comment]
CC @alexeagle @chuckjaz have you ran into anything related to this in ngc?

**Comment by alexeagle** [comment]
No, I haven't run into that before.

**Comment by evmar** [comment]
I commented on this old bug which would help here:
https://github.com/Microsoft/TypeScript/issues/7393
