### ISSUE TITLE
Delete util.ts

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#320]
This file appears to be back-compat for node 4, but we no longer need to support node 4 I think.
(I think the Google environment was the laggard but it was fixed.)

**Comment by thewillhuang** [comment]
would supporting AWS lambda for typescript related node projects be a good enough support case?

**Comment by evmar** [comment]
@thewillhuang are you currently using tsickle in this manner?  Can you talk more about what you're doing?

**Comment by evmar** [comment]
Done.
