### ISSUE TITLE
Upgrading tsickle for angular causes JSDoc to be too escapy

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#325]
upgrading from tsickle@0.2.2 to 0.2.3 causes undesirable escaping in Angular's JSDoc

eg.
```
/**
 * Construct {\@link CompileDirectiveMetadata} from {\@link ComponentTypeMetadata} and a selector.
 * @param {?} typeReference
 * @param {?} compMeta
 * @return {?}
 */
```

we shouldn't need to escape `@link`

Also the `@stable` annotation is completely dropped.

blocks https://github.com/angular/angular/pull/13471
/cc @IgorMinar

**Comment by evmar** [comment]
Do we rely on the JSDoc emitted by tsickle?  It mangles a bunch of other
things too.  It's generating gross code to get your code to be accepted by
Closure.

The test case that the JSDoc change was fixing code was this:
/**
 * Here's an example of how to use this function:
 *   @Reflect
 *   function example() { blah blah }
 */
function Reflect() {}

**Comment by alexeagle** [comment]
Yeah I'm working through the history and I understand the change.
Do you have a pointer to the error that closure causes when it sees `@Reflect`?

What we want to do for Angular is to publish ES2015 that is usable by both humans and closure compiler. Stripping out which APIs are stable makes it harder for non-TS developers to use that distro. Maybe we can just escape `\@stable`? It remains intact in .d.ts files so TS developers get the right docs.

**Comment by evmar** [comment]
Closure dies on any @foo annotation that it doesn't understand.  You can probably reproduce the error in go/jscomp-full or whatever.

tsickle generates a bunch of junk in the code, like this _tsickle_typeAnnotationsHelper() method and all the decorator annotation expanded stuff.  I think you cannot really satisfy both humans and Closure at the same time.

**Comment by alexeagle** [comment]
It's a warning:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%252F**%250A%2520*%2520This%2520comment%2520has%2520code%2520that%2520needs%2520to%2520be%2520escaped%2520to%2520pass%2520Closure%2520checking.%250A%2520*%250A%2520*%2520%2520%2520%2540Reflect%250A%2520*%2520%2520%2520function%2520example()%2520%257B%257D%250A%2520*%2520%2520%2520%2540Reflect.metadata(foo%252C%2520bar)%250A%2520*%2520%2520%2520function%2520example2()%2520%257B%257D%250A%2520*%2520%2540return%2520%257Bvoid%257D%250A%2520*%252F%250Afunction%2520JSDocWithBadTag()%2520%257B%2520%257D%250A
```
Number of warnings: 2

JSC_BAD_JSDOC_ANNOTATION: Parse error. illegal use of unknown JSDoc tag "Reflect"; ignoring it at line 5 character 5
 *   @Reflect
     ^
JSC_BAD_JSDOC_ANNOTATION: Parse error. illegal use of unknown JSDoc tag "Reflect"; ignoring it at line 7 character 5
 *   @Reflect.metadata(foo, bar)
     ^
```

I see options:
1) make this behavior configurable in tsickle, and don't do the escaping in angular. External users shouldn't care about closure warnings, ideally we should make closure shut up and minify the best it can.
2) escape the `@stable` annotation rather than drop it, so the tsickle-mangled ES6 is more palatable as an Angular distro

The former is more principled - we want to push on closure to be just a minifier externally. But for now the second seems more practical to avoid piles of warnings that the Ionic team needs to go through as our early adopters.

**Comment by evmar** [comment]
Inside g3, which things are warnings and errors is typically configured by various different teams in different ways, so avoiding them completely makes sense there.

My main worry about (1) is that many tags have effects on Closure code, and we *must* strip those tags or Closure might miscompile it.  (E.g. if you tag something @private but use it in some way that Closure doesn't like it might refuse to compile the code.)  The full list is here: 

There's more discussion about dropping JSDoc here:
https://github.com/angular/tsickle/blob/395db4f40f2ecff3066ea0e8e640f5aecfcafaa5/src/jsdoc.ts#L156

So I guess with that in mind, (2) is maybe a better solution.

But I still think we shouldn't distribute source that is tsickled if possible. It's meant to be an internal compilation detail.  In the past we've considered stripping *all* comments except the ones we emit.  (For another example, it changes the semantics of TypeScript enums, so I think you cannot use tsickle code and non-tsickle code on the same enums in the same project.)  But you know more about the ionic situation than I do.

**Comment by alexeagle** [comment]
Another option: prefix all output files with
```
/**
 * @fileoverview
 * @suppress{nonStandardJsDocs}
 */
```
