### ISSUE TITLE
Keep all imports (even type-only imports)

### ISSUE THREAD

**Issue by stephenfarrar** [angular/tsickle#328]
Currently, tsickle only writes goog.require() for symbols that are actually used in the code.
Imports that are only used for types are discarded.

```
declare module "bar" {
  class x {
    func(): void;
  }
}

import * as bar from "bar";

let zz: bar.x;
zz.func();

// uncomment me
//let z = new bar.x();
```

**Comment by evmar** [comment]
The reason we care about this is that module A does `export declare interface A {}` and module B then uses the `A` type somewhere.

If, when we preprocess A, we insert a var declaration (which is necessary to declare the type for Closure anyway), then when we compile A+B together, TS will keep the import.

**Comment by mprobst** [comment]
We now emit `goog.forwardDeclare` for type only imports.
