### ISSUE TITLE
Why no `--outFile` option?

### ISSUE THREAD

**Issue by pcj** [angular/tsickle#339]
tsc can concatenate output to a single predictable output filename.  Is there equivalent for tsickle?

**Comment by evmar** [comment]
tsickle should support all the tsc flags.  See `tsickle --help`; you pass tsickle flags, then `--`, then tsc flags.  If that doesn't work let me know!

**Comment by evmar** [comment]
...with that said, actually I'm not sure that Closure Compiler supports having all its input in a single file, so I'm not sure `--outFile` will actually do what you want.

**Comment by mprobst** [comment]
Closure's goog.module semantics need separate files, I think.

**Comment by pcj** [comment]
`tsickle` will error out when given `--outFile`, and this explains why.  

I'm trying to tie `tsickle` up with rules_closure, and wanted to get a single output file.  I'll have to think about how to predict all the output files for a given `tsickle` run and shuttle those into a `closure_js_binary` rule.

Thanks!

**Comment by evmar** [comment]
Please CC me on any changes in this area and I can provide advice.

**Comment by pcj** [comment]
@evmar Thanks
