### ISSUE TITLE
Support sourcemaps in TypeScript sources

### ISSUE THREAD

**Issue by tbosch** [angular/tsickle#345]
The upcoming Angular release will generate sourcemaps from template files into the `.ngfactory.ts` files. These sourcemaps then need to be combined with other sourcemaps produced by TypeScript, Tsickle, ...

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/14013 for the tracking issue.

Note that this can be implemented in parallel with the issue above.

**Comment by mprobst** [comment]
I think this is more of an issue with TypeScript itself, isn't it?

**Comment by tbosch** [comment]
Yes.
But we need this for Angular 4 and we already have a source-map merging feature in tsickle (using `source-map`), so adding incoming source maps shouldn't be hard (I talked to @LucasSloan before...). So would be nice to add this as a short term fix...

**Comment by mprobst** [comment]
Can you cross-reference an issue against TypeScript itself?

**Comment by LucasSloan** [comment]
Typescript issue: https://github.com/Microsoft/TypeScript/issues/13944

**Comment by LucasSloan** [comment]
Fixed by #364
