### ISSUE TITLE
Symbols shadowing Closure Compiler builtin Array

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#349]
```ts
import * as Array from 'some/thing';

const x: number[];
```

Ends up as:

```js
const Array = ...;
/** @type {Array<number>} */
const x;
```

**Comment by evmar** [comment]
If we had full control over the emit pipeline (i.e. transforms) we could probably rename Array in this case to some mangled name.  But for now maybe the best we can do is reject this code.

**Comment by mprobst** [comment]
tsickle now emits all imports behind a module prefix.
