### ISSUE TITLE
abstract getters broken

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#350]
Right now tsickle converts
```
abstract class PlatformRef {
  abstract get destroyed(): boolean;
}
```
into
```
/**
 * @abstract
 */
class PlatformRef {
    /**
     * @abstract
     * @return {?}
     */
    destroyed() { }
}
```
(the `get` keyword was dropped)

This causes an implementation class which does have the `get:destroyed` to not match the supertype
```
input0:12: WARNING - property foo on abstract class PlatformRef is not implemented by type _PlatformRef
```

As a workaround we'll add `@suppress {checkTypes}` to the subclass declaration in Angular.

Note that if tsickle output with the `get`, we still get a closure warning:
`input0:9: WARNING - Misplaced @abstract annotation. only functions or non-static methods can be abstract
get   foo() {}`

**Comment by alexeagle** [comment]
It seems like closure is missing the ES6 feature of getters combined with `@abstract`? Known issue @MatrixFrog ?

**Comment by evmar** [comment]
@MatrixFrog 🎉
