### ISSUE TITLE
translating TypeScript's "this" types to Closures @this

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#351]
When one writes in TS:

```typescript
function(this: Foo, a: Bar) {...}
```

tsickle can produce

```javascript
/**
 * @param {Bar} a
 * @this {Foo}
 */
function(a) {...}
```

**Comment by evmar** [comment]
We do this here:
https://github.com/angular/tsickle/blob/a23a0ee16289ebec748cb92e8852c18533bc73f2/test_files/functions/functions.ts#L16

Maybe you encountered tsickle_untyped mode?

**Comment by rkirov** [comment]
ops, I missed that one.
