### ISSUE TITLE
Convert dot access to quoted access, rather than pass externs

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#359]
Comment here:
https://github.com/angular/angular/issues/8550#issuecomment-277753909

rightly points out that tsickle's extern generation causes some missed opportunities to rename a field. I imagine we could instead use the `declare interface` marker to tell tsickle that some property access should be re-written as quoted access instead.

**Comment by mprobst** [comment]
I'm not sure I understand this entirely. If you have data that's actually external to your application (e.g. from JSON, or foreign APIs), we should use `declare interface` and generate externs. The optimization mentioned in that comment, collapsing property access chains a la `foo.bar.baz` to `foo_bar_baz`, is of course not valid for actually external APIs such as JSON data. @thelgevold, can you clarify?

As @b-strauss demonstrated, at least in some situations Closure can alias externs vs non-externs field correctly and rename only one of them (though that optimization can be a bit dangerous if your program has incomplete type information).

@b-strauss brings up another issue, that the externs are currently not namespaced to the file they are generated from. That's #352, we'll have to mangle the names at the declaration site and then alias them locally, but that's not too tricky.

**Comment by thelgevold** [comment]
@mprobst @mprobst  After thinking about this a bit more I agree with you.

Api data is external to the app and externs is the way to go.

I was initially under the impression that exports in the form of obj.['firstName'] would be collapsed by closure into a short form alias. The shorter alias could then potentially be used internally in cases where you have multiple references to the same, potentially long name. (e.g. a function where the same property is referenced multiple times)

From the documentation:

```
Exporting allows better compression than externs. Closure Compiler never renames symbols declared in externs, no matter how many times they appear in your code. This means that a single extern declaration can create many long names in your compiled file. Exporting, in contrast, only includes the full name of the exported symbol once. This one instance of the full name sets up an alias, so that the symbol can be shortened everywhere else it appears.
```

After running a few experiments I have not been able to see this behavior though. In my example I did not see long property refs replaced with an alias, at least not in a way that could benefit this use case.

My comment can probably be disregarded at this point :-) Sorry for the confusion....

**Comment by b-strauss** [comment]
@thelgevold have you tried `goog.exportProperty` or `obj['prop']`?

`obj['prop']` is basically the lazy man's externs. They should be identical.

I am not so sure about `goog.exportProperty` because I barely used it. It may be that the compiler does some special stuff, when it sees `goog.exportProperty`.

**Comment by thelgevold** [comment]
@b-strauss I did my experiments using `obj['prop']`, but I haven't tried `goog.exportProperty`. I will take a look at that later to see if there is a difference.

**Comment by mprobst** [comment]
@b-strauss `obj['prop']` has the disadvantage that the result of the expression is untyped, so it overall reduces type availability.

Anyway, let's close this issue and head over to #352 if there are more questions :-)

**Comment by b-strauss** [comment]
@mprobst yes indeed. I would argue that no one should ever use `obj['prop']` when using closure. :D

**Comment by thelgevold** [comment]
Not trying to revive this debate :-)
But... I got a bit curious about this and reached out to the Closure team to see if there might be any merit to this idea at all in general. Logged an issue here: https://github.com/google/closure-compiler/issues/2285

Looks like they are at least willing to entertain this as an enhancement in the future.
