### ISSUE TITLE
odd pattern throws off tsickle

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#363]
The following code:

child.ts
```typescript
// helper functions to create an overloaded function type.
export declare function _nodeCheckFn(
    view: ViewData, nodeIndex: number, argStyle: ArgumentType.Dynamic, values: any[]): any;
export declare function _nodeCheckFn(
        view: ViewData, nodeIndex: number, argStyle: ArgumentType.Inline, v0?: any, v1?: any,
        v2?: any, v3?: any, v4?: any, v5?: any, v6?: any, v7?: any, v8?: any, v9?: any):
        any;

export type NodeCheckFn = typeof _nodeCheckFn;
```
parent.ts
```javascript
export * from './child';
```

results in post tsickle

```javascript
var types_1 = goog.require('child');
exports._nodeCheckFn = types_1._nodeCheckFn;
```

Not sure if this is an error in the closurizer pass or in the export star rewritter.

/cc @mhevery

**Comment by evmar** [comment]
What output do you expect?  That looks roughly right to me (?)

**Comment by rkirov** [comment]
Forgot to add './child' does not mention '_nodeCheckFn' at all. Now that I think about it that is the real issue and this has nothing to do with the export * rewritter.

**Comment by mprobst** [comment]
Is this potentially fixed at head? I changed this recently to generate exports for declared variables, classes, interfaces, but also functions in #348.

**Comment by mprobst** [comment]
Let's call this fixed unless it occurs again.
