### ISSUE TITLE
writeFile creates lower-case filenames on Mac

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#365]
Tsickle now converts to canonicalFileName when writing files, here:
https://github.com/angular/tsickle/blob/aae914dc74721f9a62792e9559f70a29669d2245/src/tsickle_compiler_host.ts#L144
I think this behavior was copied from the compilerHost in google3.

This means that when using tsickle on Mac (eg. running `@angular/tsc-wrapped` on rxjs in the new integration test), the outputs for `Observable.ts` are `observable.js`, `observable.d.ts`, and `Observable.js.map` (note how the `.map` file is special-cased in that tsickle code)

This will break any Angular users developing on Macs.

**Comment by alexeagle** [comment]
technically, Mac filesystem is case-insensitive so writing lower-case filenames *ought* to work. My issue is that closure compiler doesn't do the right thing (and other tools might not also) so we should write files that preserve the casing of the inputs (as `tsc` does)

**Comment by evmar** [comment]
Note that getCanonicalFileName in tsickle is accidentally doing two things because it's overloading something in ts.CompilerHost -- it's called by the ts compiler (to make file names case-insensitive) and it also removes blaze-bin from paths.  We want the latter in tsickle but not the former, but we should give that a different name.

**Comment by LucasSloan** [comment]
Ok, that looks like an easy fix, I need to normalize the file name for the source maps, but totally unnecessary for the output file name.

**Comment by evmar** [comment]
I tried to fix this once but the handling of paths in tsickle is a big mess.  We shouldn't implement getCanonicalFilename at all.
