### ISSUE TITLE
getCanonicalFileName does not produce consistent value for use in decoratorDownlevelSourceMaps on Windows

### ISSUE THREAD

**Issue by EricABC** [angular/tsickle#371]
Version 0.21.2, TS 2.1.6, Win10

The maps [here](https://github.com/angular/tsickle/blob/5599c188f05d03f46d67673b0ab6927d9445e524/src/tsickle_compiler_host.ts#L99-L100) rely on getCanonicalFileName for the key.  On my machine they get set with '/' for paths, but get looked up with '\\', causing a toJSON to be called on undefined [here](https://github.com/angular/tsickle/blob/5599c188f05d03f46d67673b0ab6927d9445e524/src/tsickle_compiler_host.ts#L169).

Calling getCanonicalFileName changes casing, but does not change the slash.

**Comment by evmar** [comment]
@LucasSloan 

I think we shouldn't use getCanonicalFileName at all in this code (it's designed for fudging with path case etc.), but I think it's mixed up in our g3 implementation with overloads the meaning of getCanonicalFilename.
