### ISSUE TITLE
index imports may use the 'main' field from package.json

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#376]
We have a feature that re-writes import/export locations to explicitly give a path to a file (eg. foo -> foo/index)
However, in the case of loading from node_modules, the actual path may not be index.js, for example

`import * as ts from 'typescript'`
should be re-written as
`import * as ts from 'typescript/lib/typescript'`

found by @chuckjaz

**Comment by b-strauss** [comment]
Related #252

**Comment by cebor** [comment]
Any updates?

**Comment by gautamsi** [comment]
workaround?

**Comment by alexeagle** [comment]
We are going to remove the index re-writing feature altogether, because closure compiler supports commonjs module loading now.

You can just set the option to false: https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L49

**Comment by dherges** [comment]
@alexeagle Do you mean `convertIndexImportShorthand: false`?

**Comment by alexeagle** [comment]
Yes, I should have linked at a SHA. Still working to remove that feature.

**Comment by evmar** [comment]
Obsolete.
