### ISSUE TITLE
Handle `declare module 'foo`' in externs

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#393]
Code can do

```
declare module "foo" {
  var bar: string;
}
```

We need `bar` to appear in some externs file to prevent it from being renamed.  But it's not global, so the correct place for it isn't obvious!

I tried fixing this already in https://github.com/angular/tsickle/commit/f99e086fc5c7b59ce57e931be8260f815f8019f1 .
What I did was just declare all names in a fake namespace, like
```
/** @type {?} */
tsickle_declare_module.foo.bar;
```
where "foo" is the module name and "bar" the value (see above example).

But it turns out that doesn't actually work; people declare modules with lots of funny names such as "../../Observable": https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/switchMapTo.ts

**Comment by evmar** [comment]
Observation: we don't care about using the module name in the fake name ("foo" in this example) because the "foo" does not ever appear in the output code.

But we cannot just stick all the variables into one namespace.  If we did, code like
```
declare module "foo" {
  var bar;
}
declare module "foo2" {
  var bar;
}
```
would produce conflicting definitions of `bar`.

**Comment by evmar** [comment]
Example of problematic code:
https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/switchMapTo.ts

**Comment by LucasSloan** [comment]
Do we care about readability of the externs file?  If not, we could just hash the module name.  If so, could we just add a comment to the externs file explaining what the origin module name was?

**Comment by evmar** [comment]
Hashing is a good idea!  Let me see what I can cook up.

**Comment by mprobst** [comment]
You could just do `moduleName.replace(/[^A-Za-z0-9]/g, '_')`, and then append a hash for the potential conflict? But this will have the ability for the user to create conflicts in any case.

An alternative idea is to just generate variables in the top level namespace in the externs, and rely on the `@suppress {duplicate}`.

**Comment by evmar** [comment]
I think even with @suppress {duplicate} you get an error for two types for the same name.
I went with the /[^A-Z]/ approach.
