### ISSUE TITLE
TypeScript / tsc drops comments, removes Closure-style casts

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#411]
tsickle emits Closure style casts, i.e. JSDoc comments like this:

```ts
x = /** @type {foo} */ (y);
```

tsc drops these, and emits:

```js
x = (y);
```

This happens in many syntactical positions.

**Comment by mprobst** [comment]
From @evmar 

Idea: introduce the Closure version of
  function coerce<T>(x: any): T { return X; }
and then use that?

Might be pretty gross depending on how many casts we insert.
 
Idea #2, pattern t5:
```
var a;

/** t1 */ x;

/** t2 */ var x;

x = /** t3 */ a;

x = /** t4 */ (a);

x = ((/** t5 */ a) => a)(a);
```

Idea #3 is of course fixing it upstream but I dunno how hard that is.  I tried before and it seemed fairly hard but I didn't understand the code very well.

**Comment by evmar** [comment]
Related upstream bugs:

- the main one https://github.com/Microsoft/TypeScript/issues/6982
- the one about how jsdoc is confusing https://github.com/Microsoft/TypeScript/issues/9975

**Comment by evmar** [comment]
Note: someone tried to patch this before (in one of the above bugs) and their patch was dropped because the transforms branch changed everything.  But this bug made it through the transforms branch!

**Comment by tbosch** [comment]
Note that while working on the transfromer version of tsickle (see https://github.com/angular/tsickle/pull/516), I found that TypeScript does allow to emit comments in these places if they are added by a transformer (as a synthetic comment).

However, this breaks in some places in G3:
- Closure warns when using this in expressions in ES6 string interpolations
- Closure fails when doing the following:
  * "ERROR - Violation: References to "this" that are typed as "unknown" are not allowed. See http://go/closure-js-conformance#unknownThis"
```
export let ExtensibleError: ExtensibleErrorCtor = function(this: Error) {
  this.message = 'test'
} as any
```

**Comment by evmar** [comment]
Fixed.
