### ISSUE TITLE
goog.module  cannot reference this

### ISSUE THREAD

**Issue by orenmizr** [angular/tsickle#412]
tsickle + closure issue: many have used the workaround with emit helpers flag but did not see anyone addressing this. 

```
build/Persistence.js:54: ERROR - The body of a goog.module cannot reference this.
var __extends = (this && this.__extends) || (function () {
                 ^^^^

build/Persistence.js:54: ERROR - The body of a goog.module cannot reference this.
var __extends = (this && this.__extends) || (function () {
```

**Comment by evmar** [comment]
What is Persistence.js?

**Comment by orenmizr** [comment]
tsickleOutput. 

meaning one file. tsickle wrapped it in Google module

**Comment by evmar** [comment]
Sorry, I'm having difficulty understanding your bug report.  :)

Can you write it in the form "I gave the input X, tsickle produced the output Y, which is wrong for reason Z".

**Comment by mprobst** [comment]
Wild guess: your output includes the typescript helpers, and you need to
not emit that but use the slightly adopted version in this repo?

Evan Martin <notifications@github.com> schrieb am Di., 28. Feb. 2017 um
21:00 Uhr:

**Comment by orenmizr** [comment]
I gave it one typescript file with no modules. ran with tsickle. got that file anotated and wrapped in Google.module. 

closure tried to do do his compression and errored on the this I had pasted.

it is a somewhat known issue that people including me use the emit helpers to work around it.

**Comment by evmar** [comment]
Fixed.
