### ISSUE TITLE
Clarify tsickle CLI vs @angular-cli-wrapped

### ISSUE THREAD

**Issue by kylecordes** [angular/tsickle#416]
This is a request to clarify the documentation, for something that is possibly obvious to people working with this tool every day, but not at all obvious from the outside.

It is not clear under what conditions in cases the tsickle CLI can be used, versus the (marked as internal) `@angular/tsc-wrapped`.

Experimentally: `@angular/tsc-wrapped` can be handed a `-p` parameter pointing to a `tsconfig.json` file. But tsickle itself requires that `-p` point to a directory, In which it can find a tsconfig file. But this is surely some kind of trivial difference, not the important difference.

It also appears that perhaps tsickle alone is just tsickle, while -wrapped had several other types of processing as well?

Further, the tsickle help offers a flag `--untyped`, which might or might not be an alias for tsconfig angularCompilerOptions.annotateForClosureCompiler? Or possibly vice versa, the latter is a verbose alias for the former?

In any event, a short clarification from someone in the know would help very much. Even just an answer here would be great, I would be happy to make a PR to format it nicely in the README and so on.

**Comment by kylecordes** [comment]
Another wrinkle:

It appears that tsickle alone, as run by its CLI, requires `"module": "common",` but via `@angular/cli-wrapper` it accepts (and produces annotate output) with `"module": "es2015"`.

**Comment by evmar** [comment]
We (tsickle devs) actually don't know much about angular-cli-wrapped.  I assume that is an Angular wrapper around tsickle's functionality, but I don't expect them to particularly align in their command line or configuration interfaces.
