### ISSUE TITLE
tsickle output for "export class Box{}" is wrong, triggers Closure internal error

### ISSUE THREAD

**Issue by kylecordes** [angular/tsickle#417]
I'm not sure the right place to report this. In looking to get a very simple case up and running, along the way I had such a case which causes a Closure Compiler INTERNAL COMPILER ERROR.

Reproduction repo:

https://github.com/kylecordes/tsickle-fiddling/tree/tsickle-417

I'm not sure if this should be solved here by making tsickle emit different code, or over on Closure by making it tolerate whatever code arrives without an internal error.

```
WARNING - File has both goog.module and ES6 modules: tsickle-output/Box.js

0 error(s), 1 warning(s)
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

insertion point must be a statement: CLASS 1 [length: 142] [source_file: tsickle-output/Apple.js]
  Node(CLASS): tsickle-output/Apple.js:1:103
goog.module('tsickle_output.Apple'); exports = {}; var module = {id: 'tsickle-output/Apple.js'};export class Apple {
  Parent(EXPORT): tsickle-output/Apple.js:1:96
goog.module('tsickle_output.Apple'); exports = {}; var module = {id: 'tsickle-output/Apple.js'};export class Apple {

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:752)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:722)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:692)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1890)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.
```

**Comment by evmar** [comment]
These sorts of errors are unfortunately common.  The warning at the top could be related.  Can you dump the input .ts file and generated .js file somewhere (pastebin or on the bug)?

**Comment by kylecordes** [comment]
Source:

https://github.com/kylecordes/tsickle-fiddling/tree/tsickle-417/src

Tsickle output;

https://github.com/kylecordes/tsickle-fiddling/tree/tsickle-417/tsickle-output

Also in that repo, same branch, exact settings being used.

(The warning got my attention also; but so far I don't yet understand the necessary tsickle settings (mostly those in tsconfig - there seems to be only one command line setting) that might affect whether it adds the goog module system and whether it removes any TS/ES6 module markers in the process.)

**Comment by kylecordes** [comment]
I've simplified down to about the minimum possible case. Here's the typescript:

```
export class Box {

}
```

Here is the tsickle output:

```
goog.module('tsickle_output.Box'); exports = {}; var module = {id: 'tsickle-output/Box.js'};export class Box {
}
//# sourceMappingURL=Box.js.map
```

I don't know enough about all of these tools to understand whether the tsickle output is reasonable for this input.

**Comment by b-strauss** [comment]
Looks like the tsickle output is wrong. The `export class Box` should not be there. That is what closure warns about.

**Comment by kylecordes** [comment]
@b-strauss I updated the title of this issue accordingly. I am not yet a guru of tsickle, but ages ago in school I worked on compilers and such, with some pointers in the right direction there is a chance I may be able to fix it.

Although this output is erroneous, it seems to me that such short erroneous input should not cause Closure to die with an internal error. Should I enter an issue over there for this problem?

**Comment by b-strauss** [comment]
This is a tsickle problem, not closure. Closure forbids ES6 imports/exports inside goog.module files. goog.module has its own export syntax.

see https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide

The proper output should be something like:
```
exports.Box = ...
```

**Comment by mprobst** [comment]
@kylecordes is your output maybe set to ES6 and ES6 modules, instead of CommonJS (which is what tsickle needs to rewrite)?

**Comment by kylecordes** [comment]
@b-strauss Oh yes, I've used the goog.___  before, and I'm reasonably familiar. The context before is not writing code directly, but rather I was working with ClojureScript, whose compiler emits JavaScript properly annotated for Closure to produce efficient output. (Insert standard joke here about naming things is the hardest problem in computer science...)

@mprobst I see, will adjust and try again. I had assumed that, since Closure has recently gained the ability to work with ES2015 modules, that this would apply also to tsickle.

**Comment by kylecordes** [comment]
@mprobst Yes, module:commonjs avoids this bad output.

Rather than just close this as-is, would you accept a PR that describes this in the README?

Should Closure Compiler get a bug report, asking for a non-internal-error on such erroneous input?

**Comment by mprobst** [comment]
I think our driver/main method should check your module output mode and
fail if you don't use --module commonjs. I'd be happy about a PR for that!

**Comment by kylecordes** [comment]
@mprobst will do!

**Comment by kylecordes** [comment]
@mprobst https://github.com/angular/tsickle/pull/419

**Comment by evmar** [comment]
I filed the crash upstream at https://github.com/google/closure-compiler/issues/2358 , though the workaround is obvious.

**Comment by evmar** [comment]
Thanks for fixing it!
