### ISSUE TITLE
TS 2.2 causes static methods to get removed by the closure compiler

### ISSUE THREAD

**Issue by rubenlg** [angular/tsickle#427]
File a.ts:
```typescript
export class A {
  static print() {
    console.log('A');
  }
}
```

File b.ts:
```typescript
import {A} from './a';
A.print();
```

File tsconfig.json:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"
    },
    "include": ["*.ts"]
}
```

Output of running tsickle + closure:
```javascript
$ tsickle 
$ closure-compiler -O ADVANCED *.js
var a={};Object.defineProperty(a,"__esModule",{value:!0});a.a=function(){};Object.defineProperty({},"__esModule",{value:!0});a.a.b();
```

That code fails because `a.a.b()` is not defined (`b` should be the static method `print`, which is gone).

**Comment by rubenlg** [comment]
In case it is relevant, I installed tsickle earlier today with npm, and I'm using the closure compiler version v20170218.

The problem seems to be `Object.defineProperty(exports, "__esModule", { value: true });`. If I remove that line from the transpiled javascript, then the static method gets emitted by closure and the code runs as expected.

**Comment by evmar** [comment]
This bug suggests this might be a breaking change in TS 2.2:
https://github.com/Microsoft/TypeScript/issues/14351

Can you try TS 2.1 and let me know if it works?  We haven't yet updated to 2.2.

**Comment by rubenlg** [comment]
Thanks for the quick reply! I just tested TS 2.1 and it does work. I was using TS 2.2 since that's what you get when you do:
  npm install tsickle typescript

It might be worth a warning on the frontpage that this doesn't work yet with TS 2.2.

**Comment by evmar** [comment]
Sorry about this.  You are apparently the first person to encounter this.  We typically update to the current TS version within a few weeks of the release so we don't call out which version we support anywhere.  Maybe we can specify this in our package.json somewhere?

**Comment by mprobst** [comment]
Maybe there's some "ts.version" that we could check at runtime?

**Comment by evmar** [comment]
I attempted to reproduce this in a tsickle test case via 

```
export default class Foo {
  static bar() { return 3; }
}
```

(using "default" because that triggers this `__esmodule` thing in ts2.1) and it compiled fine (newlines added for readability):

```
module$contents$test_files$export_default$default_Foo=function(){};
module$contents$test_files$export_default$default_Foo.bar=function(){return 3};
Object.defineProperty(module$exports$test_files$export_default$default,"__esModule",{value:!0});
```

Weird.  I can still strip the `defineProperty`, but I'm sad I can't reproduce the error in a test.

**Comment by rubenlg** [comment]
Thanks!

**Comment by evmar** [comment]
Regarding TS2.2, we're going to move the master branch of tsickle to require TS2.2 (and have the "2.1" branch around for TS2.1 users).  Alex has a change coming imminently...

**Comment by rubenlg** [comment]
@evmar I can still repro this bug with tsickle 0.21.6 and typscript 2.3.1.

**Comment by evmar** [comment]
Hm, maybe it regressed again in TS 2.3?  Can you describe how it fails?

**Comment by rubenlg** [comment]
Exactly the same way, you have the repro steps on the first post in this thread. I just run through the same example and get the same behavior.

**Comment by rubenlg** [comment]
Does it make sense to reopen this issue or should I file a separate one?

**Comment by evmar** [comment]
Whoops, thought you already had reopened.  :)

**Comment by rubenlg** [comment]
I don't have permission 0:-)

**Comment by rubenlg** [comment]
I was checking the source code of 0.21.6 as installed by npm, and it seems it doesn't include your change in #454, which explains why I keep seeing the same behavior. Perhaps I should wait for another release?

**Comment by alexeagle** [comment]
We should release 0.23.0 following our convention of using the compatible
TS major/minor in our version scheme

**Comment by alexeagle** [comment]
0.23.3 is on NPM, which should include all the code on master.
Please let us know if there's still something wrong, sorry for all the release woes...

**Comment by rubenlg** [comment]
I can confirm it works great, thanks!
