### ISSUE TITLE
golden file tests fail with mismatching line endings on Windows

### ISSUE THREAD

**Issue by b-strauss** [angular/tsickle#436]
There are `\n`s all over the codebase. This leads to most of the failed golden tests on windows.

I will add an OS check and, if we are on windows, normalize the line endings.

**Comment by b-strauss** [comment]
This is more complex than I anticipated... Currently we have the following situation on Windows:

Tsickle loads .ts files from the Windows filesystem. These files contain Windows line endings `\r\n`. It then writes custom code on top of these with `\n` as seen [here](https://github.com/angular/tsickle/blob/b6c345af3e4bf236ce4dc0c0b440daeab4bd8a62/src/tsickle.ts#L562). The result is an output string that has both types of line endings. This breaks the golden tests, because the tests compare the reference files, loaded from the Windows filesystem (`\r\n`), with the rewritten Tsickle output that has mixed line endings (input files `\r\n` plus rewritten code with `\n`) by equality.

I first tried to replace the line endings in the generated output string with the current platforms line endings from node.js ([`os.EOL`](https://nodejs.org/api/os.html#os_os_eol)). Unfortunately JavaScript's RegExp has no support for lookbehind, which would be needed to not break usercode `\n`s. There are workarounds that involve reversing the string, but these lead to new problems with unicode characters.

The second thing I tried, was to replace all hardcoded `\n` with `os.EOL`. This actually worked on most golden tests (yay). But now all other tests failed because the input of these tests does not come from files but from inline template strings, and per ES6 specification multiline template strings have `\n` line endings on all platforms ☹️.

**Conclusion**
Should Tsickle generate output with the line endings of the platform it is currently running on? I think it should. I think emitting `os.EOL` instead of hardcoded `\n` is the right thing. What about inline template strings? I see two solutions, converting them to separate files or converting them to oldschool strings with `os.EOL`.

Any advice?

cc @evmar @mprobst

**Comment by evmar** [comment]
The tsickle output is not really intended to be human-readable, it's just a temporary file that is then fed to another compiler.  With that in mind it seems harmless to me to always use \n endings.

If you are seeing \r\n in the tsickle golden files I think there's a git setting related to whether to introduce \r\n into files that don't have it.

**Comment by b-strauss** [comment]
Would it be reasonable to replace the line endings after loading the golden files on Windows?

**Comment by mprobst** [comment]
What about adding `goldenFileContents.replace(/\r\n/g, /\n/)` (or so) to
the test suite?

**Comment by b-strauss** [comment]
@mprobst yes that's what I meant. That should work.
