### ISSUE TITLE
How to remove output polyfills-> Symbol,  "ES3 does not support getters and setters"

### ISSUE THREAD

**Issue by orenmizr** [angular/tsickle#437]
they make the files bigger 

TSCONFIG
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "build",
    "sourceMap": true,
    "importHelpers": false,
    "noEmitHelpers": false,
    "noEmitOnError": false,
    "noImplicitAny": false,
    "pretty": true,
    "charset": "UTF-8",
    "experimentalDecorators": true,
    "moduleResolution": "node"
  },
  "include": [
    "./src/**/*.ts",
    "./src/definitions.d.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

```
 "java -jar ./node_modules/google-closure-compiler/compiler.jar --compilation_level ADVANCED --dependency_mode LOOSE --entry_point build.App --language_in ES6 --language_out ES5 --js build/*.js --js_output_file ./dist/output.min.js  --externs ./build/externs.js",
```

OUTPUT PREFIX
```
var f;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function n(){n=function(){};m.Symbol||(m.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function p(){n();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return q(this)}});p=function(){}}function q(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){p();a={next:a};a[m.Symbol.iterator]=function(){return this};return a}var r={};Object.defineProperty(r,"__esModule",{value:!0});function u(){}

```

**Comment by orenmizr** [comment]
@evmar plz

**Comment by mprobst** [comment]
If you get the error `ES3 does not support getters and setters`, you need to set your output language to ES5. If you need to drop polyfills from the output, there's a JSCompiler option for that, check its docs.

**Comment by mprobst** [comment]
Check the generated JavaScript sources, and see what `goog.module`s are
defined in them. You likely have an incorrect base path set.

**Comment by orenmizr** [comment]
@mprobst there is still a valid input file - it is just bloated. 

a) if you're correct, shouldn't it have failed ? 

b) i am not the first to report on this.  didn't really understand the cause- https://github.com/ampproject/amphtml/issues/4933

**Comment by mprobst** [comment]
@orenmizr I'm just conjecturing from your issue title.

Regardless, this is not a good forum for general user support, and even so, your issue seems to be with Closure Compiler. We should document this better, but at this point `tsickle` cannot really be used unless you're very familiar with Closure Compiler. We'll work on improving that, but for the time being we don't have the bandwidth for support here. Sorry :-/

**Comment by orenmizr** [comment]
i've reported some issuess with tsickle before. i admit that this one seem more like a closure polyfill issue. i hoped someone who worked closely with both packages would point me to the right direction. 

i appreciate your assistance in any case.
