### ISSUE TITLE
Tsickle fails to emit multi-line docs on Windows

### ISSUE THREAD

**Issue by b-strauss** [angular/tsickle#440]
We have four remaining tests on Windows that fail. Three of them fail because of multi-line comments:

- golden tests comments
- golden tests interface
- golden tests jsdoc

I suspect line endings again.

Example (screenshot for color format):

![errors](https://cloud.githubusercontent.com/assets/6588177/24123576/6250ae88-0dc0-11e7-95e7-83ad9bfac301.png)

**Comment by evmar** [comment]
The way this works is we grab jsdoc when we see it, parse it, and reserialize it back out.  This looks like the parse is failing.

Perhaps somewhere around here:
https://github.com/angular/tsickle/blob/2b5ae780696002b49b3fabd8125424ea778e4f3a/src/jsdoc.ts#L159

**Comment by b-strauss** [comment]
The problem is the regular expression at line 158. The `m` flag in that regexp only works with `\n`. I think before I mess with that the simpler solution would be to just use the good old `comment = comment.replace(/\r\n/g, '\n');` at the beginning of the function.

What do you think?

**Comment by evmar** [comment]
Sounds good.  I am surprised that /m doesn't match crlf but so it goes.

**Comment by b-strauss** [comment]
Curiously enough it does match, but for whatever reason it nukes the `\n` part of crlf.

Broken:
```
// before
'* multi-line jsdoc comment without\r\n   * type annotation.'

// after
'multi-line jsdoc comment without\rtype annotation.'
```

Correct:
```
// Before
'* multi-line jsdoc comment without\n   * type annotation.'

// After
'multi-line jsdoc comment without\ntype annotation.'
```
