### ISSUE TITLE
Support template types

### ISSUE THREAD

**Issue by gkdn** [angular/tsickle#445]
See #369 for context.

**Comment by mprobst** [comment]
Do you have a repro? I've recently changed code, AFAIU we should support template args now.

**Comment by gkdn** [comment]
I think @tadeegan ran tsickle on [react.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/index.d.ts)  2-3 weeks earlier where we observed this.

**Comment by mprobst** [comment]
That'd be roughly within the time window when I fixed the underlying
problem. I'd appreciate if you could try to repro with the latest version.

**Comment by evmar** [comment]
We appear to have a template test in
https://github.com/angular/tsickle/blob/master/test_files/type/type.ts
and I see the @template T in the JS output.
