### ISSUE TITLE
add CI tests on Windows environment

### ISSUE THREAD

**Issue by b-strauss** [angular/tsickle#446]
With #443 fixed we pass all tests on Windows now. I'd like to suggest using [AppVeyor](https://www.appveyor.com/) as additional CI step. This would make sure tests on Windows stay green. :-)

For reference: https://github.com/angular/angular-cli/blob/master/.appveyor.yml

**Comment by alexeagle** [comment]
Do you have time to open a PR to do that? What about configuring the appveyor integration?

**Comment by b-strauss** [comment]
@alexeagle I added a config file in #460.

**Comment by b-strauss** [comment]
closed by #460, #472
