### ISSUE TITLE
Index import rewriting broken

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#458]
Two scenarios:
package.json has a main field which points to another spot.

`node_modules/foo/package.json`:
```
"main": "dist/index.js",
"typings": "dist/index.d.ts",
```
`user.ts`:
```
import * as f from 'foo';
```

rewrites as 
```
import * as f from 'foo/index';
```
it should instead be 
```
import * as f from 'foo/dist/index';
```

Also, 
```
import {a} from './';
```
with an index.ts in the same directory produces
```
import {a} from './/';
```

/cc @frozenpandaz

**Comment by evmar** [comment]
It appears we special-case /index here:
https://github.com/angular/tsickle/blob/dfc6c9bc89f58e73ccf8166ca62d8dbfda6e066e/src/tsickle.ts#L858

I think instead we should maybe just use the fully resolved module in the import line (?)

**Comment by alexeagle** [comment]
Really strange, I had a WIP fix for this sometime in the past, but I don't
know what happened to it or why the need for it disappeared. I'm partway
through a fix again (but in general, reversing the TS pathmapping is a
challenge)
