### ISSUE TITLE
tsickle's declarations get dropped with preceding comment

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#468]
Given this code:

```ts
/** some comment */
let x: X;
```

tsickle fails to emit the `/** @type {...} */` comment since a recent TS upgrade.

Probably something about comments being (not) merged?

**Comment by evmar** [comment]
I looked into this one before.  It's something about the way we handle comments on the VariableDeclarationStatement (the "let [...];") vs the VariableDeclarations (the [...], which can contain multiple x=1, y=2 in it).  Somehow they end up with the same comment node or something.

**Comment by evmar** [comment]
Also only started happening in TS2.2.

Note that for
```js
/** foo */
let x = 3, y = 4;
```

we want to insert type annotations on both x and y and somehow not touch the other comment, but then I'm not sure what should happen when you only declare a single variable.  E.g. I dunno what Closure does in:

```js
/** @type {a} */
let x = 3, y = 'a';
```

**Comment by evmar** [comment]
Obsolete.
