### ISSUE TITLE
appveyor hooks are not running

### ISSUE THREAD

**Issue by b-strauss** [angular/tsickle#480]
The last few commits don't notify appveyor. #478 #477 @alexeagle

**Comment by alexeagle** [comment]
sigh, remember we saw that on the original PR but I hoped it was just not warmed up yet...

**Comment by alexeagle** [comment]
@StephenFluin I think I need some admin mojo to view the webhooks, when you get a minute...

**Comment by StephenFluin** [comment]
@alexeagle I don't think I have the permissions to do this or see the webhooks.

**Comment by alexeagle** [comment]
@evmar you are an admin on this repo, can you fix this up?

**Comment by mprobst** [comment]
Do we already have an appveyor project? I'm happy to hook this up, but I guess I shouldn't create a new project? Can somebody share that with me somehow?

**Comment by b-strauss** [comment]
AFAIK @alexeagle used his own account for appveyor. The appveyor account is directly linked to the github account. I'm not sure how it works for github organization accounts.

The angular-cli team has it's own account:
https://ci.appveyor.com/project/AngularCLI/angular-cli

**Comment by b-strauss** [comment]
I'm afraid to ask. Is anyone on the angular/tsickle team interested to fix this? Last time I checked tsickle was full of failing tests on Windows, which is frustrating because there was a point in time in which I had all Windows errors fixed. 🙁

**Comment by evmar** [comment]
We're pretty short on resources as-is.  I think once we think tsickle is ready for public consumption (that is, it works well on at least one platform) we'll care more about making Windows work.  Currently nobody on the team tests on Windows so your fixes are welcome.

**Comment by alexeagle** [comment]
The good news is I'm working to fix Windows CI problems.
The bad news is I'm fixing them in bazel, and tsickle uses bazel now, so we
are even further from a green appveyor build.

**Comment by b-strauss** [comment]
@alexeagle so once you're done with that we would need to update the appveyor file to kickstart bazel, right?

**Comment by alexeagle** [comment]
I'm not sure how we'll run bazel under appveyor yet, we'll also have to
install it. But Angular needs this too, so I think we'll be forced to
figure it out soon.

**Comment by b-strauss** [comment]
We could install bazel with chocolatey (
https://chocolatey.org/packages/bazel). Chocolatey is a Windows package
manager and it's already pre installed on appveyor (
https://www.appveyor.com/blog/2014/11/06/appveyor-with-a-hint-of-chocolatey/
).

Alex Eagle <notifications@github.com> schrieb am Do., 26. Okt. 2017, 18:59:

> I'm not sure how we'll run bazel under appveyor yet, we'll also have to
> install it. But Angular needs this too, so I think we'll be forced to
> figure it out soon.
>

**Comment by alexeagle** [comment]
Yeah that sounds right, now is the time:
https://blog.bazel.build/2017/10/16/windows-retrospect.html

As soon as rules_typescript works on Windows, do you have some time to try
hooking this up on appveyor again? Sorry for all the churn!

**Comment by b-strauss** [comment]
Just ping me here. I may or may not have time. :)

**Comment by alexeagle** [comment]
FYI @filipesilva

**Comment by filipesilva** [comment]
The tracking issue on rules_typescript is https://github.com/bazelbuild/rules_typescript/issues/56. I'll work on it soon.

**Comment by b-strauss** [comment]
@alexeagle Now that https://github.com/bazelbuild/rules_typescript/issues/56 is closed, can this be tackled again?

**Comment by mprobst** [comment]
I think this is obsolete.

**Comment by b-strauss** [comment]
@mprobst Do the tests run on a Windows system in circle-ci?

**Comment by mprobst** [comment]
I don't think so. But honestly, now that Angular isn't using tsickle
anymore for the most part, testing on Windows doesn't seem worth the effort.

**Comment by b-strauss** [comment]
I think this tool is very useful for any TypeScript project. I would still be interested to make this work on Windows, with the help of a contributor.

Anyway the Appveyor hooks have not been running for more than two years. The `.appveyor.yml` file is old cruft and should be deleted.
