### ISSUE TITLE
Transform decorators into static methods and getters rather than static properties

### ISSUE THREAD

**Issue by IgorMinar** [angular/tsickle#486]
Currently we downlevel decorators to static properties that reference a function, if we change the transformation to produce static methods and static getters, we'd make the class once downleveled to ES5 by typescript eligible for dead code elimination by uglify via the `/*@__PURE__*/`.

While the current es5 output contains assignment to the constructor function outside of the IIFE produced by typescript when downleveling the class, the new version would contain all the code encapsulated inside of the IIFE, which once the IIFE is marked with `/*@__PURE__*/` annotation makes the whole class eligible for dead code elimination by uglify.

Without this change, the downleveled classes, even if marked with the pure annotations are retained because of the references from outside of the IIFE.

Example source code:

```ts
@Pipe({
  name: 'my-pipe'
})
class MyVerySpecialPipe {
  constructor(appRef: ApplicationRef) {}
  transform() { return "BOBOBO"};
}
```

after decorator stripping as implemented today:

```ts
class MyVerySpecialPipe {
  constructor(appRef: ApplicationRef) {}
  transform() { return "BOBOBO"};
  static decorators = [{ type: Pipe, args: [{ name: 'my-pipe'}]]
  static ctorParameters = () => [{ type: ApplicationRef}];
}
```

which after downleveling to es5 by typescript results in:

```js
var MyVerySpecialPipe = (function () {
    function MyVerySpecialPipe(appRef) {
    }
    MyVerySpecialPipe.prototype.transform = function () { return "BOBOBO"; };
    ;
    return MyVerySpecialPipe;
}());
MyVerySpecialPipe.decorators = [{ type: Pipe, args: [{ name: 'my-pipe' }] }];
MyVerySpecialPipe.ctorParameters = function () { return [{ type: ApplicationRef }]; };
```

If we were to downlevel decorators to static methods and static getters, the final es5 output would be very different:

after decorator stripping:

```ts
class MyVerySpecialPipe {
  constructor(appRef: ApplicationRef) {}
  transform() { return "BOBOBO"};
  static get decorators() { return [{ type: Pipe, args: [{ name: 'my-pipe' }]}]};
  static ctorParameters() { return [{ type: ApplicationRef }] }
}
```

after es5 down-leveling:

```js
var MyVerySpecialPipe = (function () {
    function MyVerySpecialPipe(appRef) {
    }
    MyVerySpecialPipe.prototype.transform = function () { return "BOBOBO"; };
    ;
    Object.defineProperty(MyVerySpecialPipe, "decorators", {
        get: function () { return [{ type: Pipe, args: [{ name: 'my-pipe' }] }]; },
        enumerable: true,
        configurable: true
    });
    ;
    MyVerySpecialPipe.ctorParameters = function () { return [{ type: ApplicationRef }]; };
    return MyVerySpecialPipe;
}());
```

This change is backwards compatible from the point of runtime, so it should be easy to get it out. However all the existing code downleveled by tsickle will need to be recompiled and republished.

**Comment by mprobst** [comment]
This generally sounds reasonable - however in the past, Closure had issues optimizing getters and setters (as opposed to plain properties). There's also a code size increase potential due to the required `Object.defineProperty` boiler plate.

@rkirov or @alexeagle, maybe you can take a look?

**Comment by evmar** [comment]
It looks like this would also delay the computation of decorators.  Would this have implications for the forwardRef() business?

**Comment by alexeagle** [comment]
@tbosch how does this interact with your proposal to write inline codegen?

**Comment by IgorMinar** [comment]
@mprobst wrt the size increase - this should not be a problem because we strip the metadata from prod builds anyway, except for some very limited usecases. If this does turn out to be a problem, we can always change the code in Angular to expect decorators to be a method rather than a property/getter, which would reduce the downleveled output

@evmar this change will either have no impact on `forwardRef` or will reduce the need for it, which is a good thing.

@alexeagle I don't expect that this would have an impact on the inline codegen because by the time we are doing inline codegen, we will most likely not need the decorators to survive transpilation at all, since with inline codegen the metadata will not be needed at runtime.

**Comment by rkirov** [comment]
We using the tsickle decorator transformation on ES6 emit with closure internally not ES5 emit. How should the proposed transformation look like with ES6?

**Comment by tbosch** [comment]
> this should not be a problem because we strip the metadata from prod builds anyway, except for some very limited usecases
Why do we need this change then?

**Comment by tbosch** [comment]
And who / which tool will mark the IIFE with /*@__PURE__*/ annotation? That tool could also strip these properties altogether, which would be even better...

**Comment by tbosch** [comment]
Just checked, TS 2.3 sets static properties / methods inside of the IFFE, see [this playground link](https://www.typescriptlang.org/play/#src=class%20MyVerySpecialPipe%20%7B%0A%20%20constructor(appRef%3A%20ApplicationRef)%20%7B%7D%0A%20%20transform()%20%7B%20return%20%22BOBOBO%22%7D%3B%0A%20%20static%20get%20decorators()%20%7B%20return%20%5B%7B%20type%3A%20Pipe%2C%20args%3A%20%5B%7B%20name%3A%20'my-pipe'%20%7D%5D%5D%7D%3B%0A%20%20static%20ctorParameters()%20%7B%20return%20%5B%7B%20type%3A%20ApplicationRef%20%7D%5D%20%7D%0A%7D).

**Comment by rkirov** [comment]
We are on 2.2, but again we only downlevel decorators in ES6 output mode, which we feed into closure.

**Comment by IgorMinar** [comment]
@rkirov es2015 output is the same as TS but without types. I omitted the types in the snippet above.

@tbosch we need the change because we still need to ship the metadata in the code distributed via npm so that the code is compatible with the JIT mode.

I'm working with @hansl to incorporate PURE annotation insertion and metadata stripping in the cli. For various interop reasons, cli is the only suitable place where this can happen today. This might change in the future, especially if we drop the need for JIT mode.

**Comment by IgorMinar** [comment]
@tbosch your playground link shows that what I'm proposing works as expected. the current state is reflected in [this playground demo](https://www.typescriptlang.org/play/#src=class%20MyVerySpecialPipe%20%7B%0A%20%20constructor(appRef%3A%20ApplicationRef)%20%7B%7D%0A%20%20transform()%20%7B%20return%20%22BOBOBO%22%7D%3B%0A%20%20static%20get%20decorators()%20%7B%20return%20%5B%7B%20type%3A%20Pipe%2C%20args%3A%20%5B%7B%20name%3A%20'my-pipe'%20%7D%5D%5D%7D%3B%0A%20%20static%20ctorParameters()%20%7B%20return%20%5B%7B%20type%3A%20ApplicationRef%20%7D%5D%20%7D%0A%7D)

**Comment by IgorMinar** [comment]
I talked to @tbosch and we agreed that while this would help move the decorators into IIFEs, we should actually be even more aggressive about removing decorators via [ngo](https://github.com/alxhub/ngo) or a similar tool. I'll try to implement that and if successful, we won't need to change tsickle at all. I'll keep you posted.

**Comment by fkolar** [comment]
@IgorMinar / @tbosch What is the final decision?  Are you going to keep both:

```
static decorators = [{ type: Pipe, args: [{ name: 'my-pipe'}]]
 static ctorParameters = () => [{ type: ApplicationRef}];
```

I am asking since I have usecases (primary when you need to assemble UI dynamically on the fly) that require some metadata. We remove _decorators_ (when building app using _angular-cli_  ngtools/**/loader.js )  before it goes to rollup. I though at least this could be my solution. Having some of the metadata as static fields so they can be used in runtime both for cases like mine and similar  even for those who have some custom decorators.

Thanks,
-FK

**Comment by IgorMinar** [comment]
we already worked around this problem in @angular-devkit/build-optimizer so no change is necessary.
