### ISSUE TITLE
tsickle throws when using type "object" and --typed

### ISSUE THREAD

**Issue by rubenlg** [angular/tsickle#489]
Repro case:
```typescript
function foo(): object {
  return {x: 5};
}
```

```shell
tsickle --typed
/usr/lib/node_modules/tsickle/build/src/type-translator.js:262
                throw new Error("unknown type flags: " + type.flags);
                ^

Error: unknown type flags: 16777216
    at TypeTranslator.translate (/usr/lib/node_modules/tsickle/build/src/type-translator.js:262:23)
    at /usr/lib/node_modules/tsickle/build/src/type-translator.js:267:64
    at Array.map (native)
    at TypeTranslator.translateUnion (/usr/lib/node_modules/tsickle/build/src/type-translator.js:267:32)
    at TypeTranslator.translate (/usr/lib/node_modules/tsickle/build/src/type-translator.js:243:29)
    at Annotator.ClosureRewriter.typeToClosure (/usr/lib/node_modules/tsickle/build/src/tsickle.js:405:48)
    at Annotator.ClosureRewriter.emitFunctionType (/usr/lib/node_modules/tsickle/build/src/tsickle.js:232:42)
    at Annotator.maybeProcess (/usr/lib/node_modules/tsickle/build/src/tsickle.js:667:22)
    at Annotator.Rewriter.visit (/usr/lib/node_modules/tsickle/build/src/rewriter.js:52:19)
    at /usr/lib/node_modules/tsickle/build/src/rewriter.js:84:19
```
16777216 is `ts.TypeFlags.NonPrimitive`, and is the flag for the `object`type.

**Comment by evmar** [comment]
Ah, they added `object` to the language after that code was written!

I guess the fix would be somewhere around here:
https://github.com/angular/tsickle/blob/d791060f90ffd5191bb33d4581cab84ea7aa91ae/src/type-translator.ts#L260
(The cases there might be matching the order in the enum in the TS API.)

I guess we can translate `object` as `{?}` or maybe `Object`?
https://github.com/google/closure-compiler/wiki/A-word-about-the-type-Object

**Comment by rubenlg** [comment]
That switch runs on a masked value that drops everything after `ts.TypeFlags.IndexedAccess`. I guess that was done in order to ignore the internal type flags that used to come after `IndexedAccess`. However, `NonPrimitive` comes after a bunch of these internal type flags.
That mask could be updated to be `currentMask | ts.TypeFlags.NonPrimitive`? (seems a bit hacky)

Regarding the translation, typescript has subtle differences between `object` and `Object`. The former means just non-primitive, while the latter is an interface with a few methods (`toString`, `valueOf`, etc). However, in practice they don't seem to have any difference, you can still call `toString` on an `object`. So I guess that it can also map to `Object`.

**Comment by evmar** [comment]
You might try just updating lastFlag to the last flag that is not specially marked in the TS docs.  This API into TS is pretty janky -- "usually" a type has only one flag set, but sometimes it has multiple and it changes across versions -- so in practice we can only rely on the test suite to catch mistakes.

Usually the TS type system is more subtle than the Closure one, so we often lose things in the translation. The main question to worry about here is "what is the best type we have in Closure to model this".  I think that might just be Object though.  I don't have any better idea.

**Comment by evmar** [comment]
Fixed.
