### ISSUE TITLE
Example of running from gulp? 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [angular/tsickle#496]
Integrating with gulp builds would be great. Does tsickle have the ability to interop with Node/vinyl streams?

**Comment by alexeagle** [comment]
Sorry, we don't have anything like that right now. Would make a good community contribution.

I'll work on integrating it with http://bazel.build sometime in the next few months though. That might at least give some example code to make it easier.

**Comment by ysfjwd** [comment]
mind if i ask, what does [this piece](https://github.com/angular/tsickle/blob/master/src/main.ts#L205) of code do? this outputs streams?

if this is a stream, writing a gulp plugin shouldn't be difficult.

//ysfjwd

**Comment by evmar** [comment]
jsfiles is a map from filename to file contents:
https://github.com/angular/tsickle/blob/46c8afadd99c03739e8b45ce623f6a98bb2dda5b/src/main.ts#L167

**Comment by evmar** [comment]
We're unlikely to do this, and instead leave it to a downstream project like https://github.com/theseanl/tscc .
