### ISSUE TITLE
Misplaced type annotation

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#497]
https://github.com/alexeagle/angular/blob/e1552b1745bf1eeb6f46b214c896605020ec67fd/packages/core/src/view/view.ts#L493
```
throw expressionChangedAfterItHasBeenCheckedError(
        Services.createDebugContext(view, nodeDef.index), `Query ${nodeDef.query!.id} not dirty`,
        `Query ${nodeDef.query!.id} dirty`, (view.state & ViewState.BeforeFirstCheck) !== 0);
```
=>
```
throw errors_1.expressionChangedAfterItHasBeenCheckedError(types_1.Services.createDebugContext(view, nodeDef.index), `Query ${ /** @type {?} */((nodeDef.query)).id} not dirty`, `Query ${ /** @type {?} */((nodeDef.query)).id} dirty`, (view.state & 1 /* BeforeFirstCheck */) !== 0);
```

third_party/javascript/angular2/rc/packages/core/src/view/view.closure.js:595: 
Originally at:
../../../third_party/javascript/angular2/rc/packages/core/src/view/view.ts:489: ERROR - Misplaced type annotation. Type annotations are not allowed here. Are you missing parentheses?

**Comment by mprobst** [comment]
I filed that upstream, it's a JSCompiler bug.

**Comment by evmar** [comment]
Obsolete?

**Comment by mprobst** [comment]
Fixed on the Closure side, it no longer error on this.
