### ISSUE TITLE
Generate structurally typed interfaces for classes (?)

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#5]
TypeScript uses structural type compatibility throughout, e.g.:

``` ts
class Foo { bar: string; }
class Baz { bam: string; }
var f: Foo = new Baz(); // legal as all properties match
```

In Closure, that's only allowed for [structural interfaces](https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler). While undocumented, according to the code this should be triggered by:

``` js
/** @interface @record */
my.StructuralInterface = function() {};
```

It should be possible to translate _all_ TypeScript types to structural interfaces (for `interface`) or pairs of `interface` and `class` for classes:

``` ts
interface MyIf {}
class MyClass {}
```

would generate:

``` js
/** @interface @record */
function MyIf() {};
/** @interface @record */
function MyClass_StructuralInterface() {};
/** @constructor @implements {MyClass_StructuralInterface} */
function MyClass() {};
```

Whether it's more convenient/safer/easier to implement to either invent a new name for the interface, or to invent a new name for the class, and either change the name in all type-positions, or change the name in all value-positions, is unclear at this point, both would probably work.

**Comment by evmar** [comment]
I think we've decided to not do this.
