### ISSUE TITLE
add `discard_type` flag to tsickle

### ISSUE THREAD

**Issue by mhevery** [angular/tsickle#511]
Given:
```TypeScript
interface Door { }

class DoorBell { }

class House {
  door: Door;
  doorBell: DoorBell;
}
```

There are two ways for tsickle to produce closure compatible code. It can chose to preserve type information or it can chose to label everything effectively `any` (`?`).

Preserving full type information would result in:

```TypeScript
/**
 * @record
 */
export function Door() {}
export interface Door {}

export class DoorBell {}

export class House {}

function House_tsickle_Closure_declarations() {
  /** @type {door} */ House.prototype.door;
  /** @type {DoorBell} */ House.prototype.doorBell;
}
```

Not preserving the type information would result in:
```TypeScript
export interface Door {}

export class DoorBell {}

export class House {}

function House_tsickle_Closure_declarations() {
  /** @type {?} */ House.prototype.door;
  /** @type {?} */ House.prototype.doorBell;
}
```

The big differences are:

1. Always produce `any` (`?`) in the type position in closure comment `/** @type {?} */. 
2. Interfaces do not need to be reified into runtime. (This is safe since we know that interfaces can only be in type position and we know that we will always produce `any` (`?`) in type position)

NOTE: the reason why we have to always produce `any` (`?`), is because tsickle does not have access to the resolved type information, i.e. it does not know if a particular symbol is visible or not to closure, hence it must assume that all symbols are not visible. 

## Implementation

This would be implemented as a flag to tsickle which would control wether tsickle should retain type information for closure or wether it should be discarded.

**Comment by mprobst** [comment]
This is still under discussion on mailing list.

**Comment by evmar** [comment]
I think this is `tsickle_typed` no?  I think we don't need this anymore.
