### ISSUE TITLE
Document how to compile async typescript code with closure compiler

### ISSUE THREAD

**Issue by samccone** [angular/tsickle#517]
I found this process slightly complex to get working, I am opening this issue as a starting point to one, act as documentation for those looking to do this, and two, to potentially point out some rough patches that tsickle can smooth over.

#### Critical fields in tsconfig :warning: 

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "This prevents typescript from downleveling generators so closure compiler can do it",
        "target": "es2017",
        "noEmitHelpers": "This prevents typescript helpers from being inserted which breaks closure compiler",
        "noEmitHelpers": true
    },
}
```

#### tsickle command :hammer: 

tsickle is just a wrapper around tsc, this will compile your project using your tsconfig and generate an externs file which we will use when we closure compile

```bash
tsickle --externs=externs.js -- -p .
```

#### tsickle compile command :eagle: 

Next we are going to pass our compiled index.js file from tsickle into closure compiler.

```bash
cat index.js | java -jar ./node_modules/google-closure-compiler/compiler.jar --language_in=ECMASCRIPT6 --language_out=ECMASCRIPT5 --externs=externs.js --compilation_level ADVANCED_OPTIMIZATIONS --rewrite_polyfills=false
```

\o/

**Comment by evmar** [comment]
We definitely should doc this.

Here are the flags we use for tsickle code:
https://github.com/bazelbuild/rules_typescript/blob/804c5dac1e615e83c8d05e987228dce1470f45a2/internal/common/tsconfig.bzl#L102
I think we intentionally don't target es2017 because Closure doesn't know about es2017's ** operator.
I think downlevelIteration is the important flag.

We should extract this into README.md or some sort of USAGE.md doc.

**Comment by orenmizr** [comment]
@samccone if you working on a non angular project and you get this this to work - please share your configs here

**Comment by samccone** [comment]
@orenmizr I am working on multiple non-angular projects, and it works great!

**Comment by orenmizr** [comment]
i'm on a medium size codebase - on which version of tsickle are you own ?

**Comment by brendankenny** [comment]
> I think we intentionally don't target es2017 because Closure doesn't know about es2017's ** operator.

FWIW, `--language_in=ECMASCRIPT7` (and higher) adds support for `**`

**Comment by brendankenny** [comment]
oops, that changed. I guess you need `ECMASCRIPT_2016` (or later) for that

**Comment by orenmizr** [comment]
@samccone your help will be seriously appreciated - 
no matter what i options i use i alwasys get this error: 

build/app/App.js:68: ERROR - Required namespace "build.A.B" never defined.
var NavAB_1 = goog.require('build.A.B'); ((name changed to A & B))


**import example**
```
import { Container } from "../ioc/Container";
```
**tsconfig**
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "This prevents typescript from downleveling generators so closure compiler can do it",
    "target": "es2017",
    "noEmitHelpers": "This prevents typescript helpers from being inserted which breaks closure compiler",
    "noEmitHelpers": true,
    "outDir": "build"
  },
  "include": [
    "src/**/*",
    "definitions/ambient.d.ts",
    "definitions/def.d.ts"
  ]
}
```

**Comment by evmar** [comment]
I leave this to someone to document in the form of a PR.
