### ISSUE TITLE
tsickle fails to override re-exports when the symbol is imported

### ISSUE THREAD

**Issue by bowenni** [angular/tsickle#519]
This exports `bar` as `foo` and doesn't export `foo` from `a.ts`
```TypeScript
export * from './a'; // a.ts exports only foo
const bar = 1;
export {bar as foo};
```

This exports `bar` as `foo` and also exports `foo` from `a.ts`
```TypeScript
import {foo} from './a';
export * from './a'; // a.ts exports only foo
const bar = 1;
export {bar as foo};
```

**Comment by mprobst** [comment]
Whoops, didn't see you self assigned this before starting to hack on this. I hope you hadn't started on this. Can you review my code?

**Comment by bowenni** [comment]
Sorry I'm late for the code review. Thanks for fixing it.
