### ISSUE TITLE
tsickle only reports errors from the last parsed file

### ISSUE THREAD

**Issue by tbosch** [angular/tsickle#523]
Tsickle replaces the value of the `diagnostics` property on every call to `getSourceFile` (see [the line](https://github.com/angular/tsickle/blob/master/src/tsickle_compiler_host.ts#L323) `this.diagnostics = diagnostics` in `TsickleCompilerHost`). This is problematic as a call to `ts.createProgram` with a `TsickleCompilerHost` will call `getSourceFile` multiple times, and therefore only keep the diagnostics of the last parsed file.

**Comment by tbosch** [comment]
I created cl/160120180 to show which targets would break when fixing this.

**Comment by mprobst** [comment]
CC @LucasSloan.
