### ISSUE TITLE
enums in modules can't be typed

### ISSUE THREAD

**Issue by martine** [angular/tsickle#55]
```javascript
module Foo { enum Bar { ...
```
eventually produces something like
```javascript
(function (Foo) {
    /** @typedef {number} */
    var Bar;
```
But you apparently can't (?) put a @typedef within a scope like that, it has to be top level (?).

**Comment by mprobst** [comment]
Is it high priority to support "module"? We outlaw it in the style guide,
so it'd only come in through third party code...

>

**Comment by martine** [comment]
(To answer Martin's question publicly, we encounter a module in a google-internal app.)

**Comment by martine** [comment]
I worked around this in the Google-internal app by moving the relevant code to a d.ts file (which we don't Sickle-process), but this bug stands.

**Comment by martine** [comment]
Moved part 2 to issue #74.

**Comment by martine** [comment]
I fixed enums to not use a TS enum.
