### ISSUE TITLE
transformer mode doesn't handle export namespace properly

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#556]
repro:

```ts
export namespace foo {
  export class Bar {}
}
```

With transformers, TypeScript doesn't seem to pick up that `foo` is exported and emits just `foo` in the namespace wrapping functions.

**Comment by evmar** [comment]
Possibly obsolete?

**Comment by mprobst** [comment]
Yeah. We still don't handle namespaces well for Closure, but that's a separate bug.
