### ISSUE TITLE
returning an arrow function triggers ASI

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#57]
``` javascript
function foo() {
    return (x: string) => 3;
}
```

produces

``` javascript
/**
 */
function foo() {
    return 
/**
 * @param { string} x
 */
(x: string) => 3;
}
```

Because we inserted the newline after the return, it triggers ASI and you get

```
error TS7027: Unreachable code detected.
```

**Comment by martine** [comment]
For some reason this doesn't trigger when you return a function literal (non-arrow function).  I wonder if we fail to annotate types there intentionally?

**Comment by martine** [comment]
I tried removing the whitespace around the comment, e.g.

```javascript
return /**
...
*/ (x: string) => 3;
```

but that still fails.

**Comment by martine** [comment]
Idea 1: don't annotate arrow functions.  I don't think normal Closure users would annotate them anyway.

Hypothetical problem with that idea.  If you had code like the following:
```javascript
addCallback((obj: ComplexObject) => obj.foo());
```
and that was the only user of obj.foo, if we dropped the type of obj it may be the case that Closure will fail to mangle the obj.foo properly.

**Comment by rkirov** [comment]
+1 for turning off jsdoc in this case, given that at this stage we are targeting outputting untyped.

Also note that closure can do type-inference at if addCallback is declared of type `@param {function(ComplexObject): void}`.

**Comment by martine** [comment]
Rado suggested in the PR:

For typed mode I think we have to fix this proper, how about adding extra parens?

```javascript
function foo() {
    return (
/**
 * @param { string} x
 */
(x: string) => 3
);}
```

It does trigger the double emit bug, but at least it preserves the meaning of the original code.

**Comment by evmar** [comment]
We now add parens.
