### ISSUE TITLE
Incorrect output from tsickle for public readonly parameters with inline docs and a default value

### ISSUE THREAD

**Issue by takamori** [angular/tsickle#571]
The following code
```
class Foo {
  constructor(
      /** a parameter! */
      readonly hi = 'world') {}
}
```

will result in the following code as part of its output
```
var Foo = (function () {
    function Foo(
        /** a parameter! */
        hi) {
        if (hi === void 0) { hi = 'world'; }
        this.hi = hi;
    }
    return Foo;
}());
```

which is reported as an error from the Closure compiler.
```
WARNING - Bad type annotation. Unknown type a
        /** a parameter! */
            ^
```

The error does not occur if I don't use an inline jsdoc and declare the parameter above instead.

**Comment by alur** [comment]
Another workaround for this seems to be the explicitly specify "public" in front of the readonly.

**Comment by evmar** [comment]
I think we special-cased public/private before 'readonly' was a TS feature, with kind of a hack -- we just always strip comments before 'public', and then special-cased class emit otherwise.
https://github.com/angular/tsickle/blob/e426bec035785edfcdd60ed9845842de3369b3ba/src/tsickle.ts#L819

**Comment by evmar** [comment]
We now put the doc down by the field name, but not on the ctor param.

**Comment by mprobst** [comment]
This now emits:

```
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes,constantProperty,extraRequire,missingOverride,missingReturn,unusedPrivateMembers,uselessCode} checked by tsc
 */
goog.module("google3.javascript.typescript.playground.input");
var module = module || { id: "google3/javascript/typescript/playground/input.ts" };
module = module;
exports = {};
class Foo {
    /**
     * @param {string=} hi
     */
    constructor(hi = 'world') {
        this.hi = hi;
    }
}
if (false) {
    /**
     * a parameter!
     * @type {string}
     */
    Foo.prototype.hi;
}
 
```
