### ISSUE TITLE
switch to JS Google Closure Compiler

### ISSUE THREAD

**Issue by mattbishop** [angular/tsickle#583]
Google has a JS-only version of GCC that would be applicable to this project. Using the JS version would eliminate the need for a JVM.

https://github.com/google/closure-compiler-js

https://www.npmjs.com/package/google-closure-compiler-js

**Comment by evmar** [comment]
We don't ourselves (except in the test suite) depend on Closure compiler -- we just produce Closure-compatible JS.  So I think this bug doesn't apply here, but I'm not sure.

**Comment by mattbishop** [comment]
Interesting. I see a dev dependency in package.json but I'll mess about a bit and see if it does fire up a JVM along the way

**Comment by evmar** [comment]
"dev dependency" means a dependency only when you develop tsickle, which is the test suite thing I mentioned.

**Comment by alexeagle** [comment]
Also, the JS version of closure compiler is buggy and not at feature-parity with the Java version. For example, it doesn't support unicode file contents in JS (because it uses Google Web Toolkit Java-to-Javascript transpiler).
