### ISSUE TITLE
related issues in source-map/source-map-resolve

### ISSUE THREAD

**Issue by timbell** [angular/tsickle#626]
Hi,

Just wanted to make sure you are aware of this [issue](https://github.com/mozilla/source-map/issues/250) in the source-map project so you can update your version reference once fixed.

There's also a related [issue](https://github.com/lydell/source-map-resolve/issues/10) in source-map-resolve.

The combination of these issues + the use of rollup and rollup-plugin-sourcemaps ends up with rollup failing silently and producing no output, which is somewhat perturbing!

**Comment by mprobst** [comment]
Thanks for notifying us @timbell, I'll make sure to update once you fixed the original issue.
