### ISSUE TITLE
Don't wrap import() expression

### ISSUE THREAD

**Issue by Delagen** [angular/tsickle#632]
Source:
```
export function moduleLoadCallback() {
    return import(/* webpackChunkName: "a" */ "./a.module")
        .then(function (module) { return module.A; });
}
```
TS Out:
```
export function moduleLoadCallback() {
    return import(/* webpackChunkName: "a" */ "./a.module")
        .then(function (module) { return module.A; });
}
```
TsickleOut:
```
export function moduleLoadCallback() {
    return (import)(/* webpackChunkName: "a" */ "./a.module")
        .then(function (module) { return module.A; });
}
```
https://github.com/webpack/webpack/issues/5859

**Comment by Delagen** [comment]
https://github.com/webpack/webpack/issues/5859#issuecomment-338143872

**Comment by evmar** [comment]
I don't expect Closure compiler works well with dynamic imports anyway -- you'd need to somehow split your app into chunks and get renaming right.  Can you describe what you're trying to do?

**Comment by Delagen** [comment]
Webpack using it for chunk splitting natively, TS 2.4 supports it. So what the problem?

**Comment by Delagen** [comment]
With @angular/compiler-cli@4.x it was working.

**Comment by evmar** [comment]
You are filing a bug in the tracker for the tool used to integrate TypeScript and Closure compiler, so I'm not sure how webpack is relevant.

**Comment by Delagen** [comment]
Read https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html
import is a keyword and it part of ECMAScript, so it MUST stay keyword

**Comment by evmar** [comment]
I don't expect Closure compiler works well with dynamic imports anyway -- you'd need to somehow split your app into chunks and get renaming right. Can you describe what you're trying to do?

**Comment by Delagen** [comment]
I use import expressions as code splitting base for angular lazy loading. 
```
export function moduleLoadChildrenCallback(): Promise<Type<any>> {
	return import(/* webpackChunkName: "module" */"./view/module/some.module")
		.then((module) => module.SomeModule);
}

...
loadChildren:    moduleLoadChildrenCallback
...


```

For now: I simply exclude these files from tsickle processing.

**Comment by Delagen** [comment]
And it works well till ngc 5.0

**Comment by mprobst** [comment]
@alexeagle are we running Angular user code through tsickle?

**Comment by Delagen** [comment]
@mprobst angular/compiler-cli uses tsickle for generating ngfactory for modules
https://github.com/angular/angular/blob/master/packages/compiler-cli/src/main.ts#L75

**Comment by alexeagle** [comment]
there are a couple options in `angularCompilerOptions` that govern it.
`annotateForClosureCompiler` adds the JSDoc, and defaults to false
`annotationsAs` runs the decorator downleveling, and defaults to `static fields` which is the closure-compiler-compatible behavior.

@Delagen which of these options are enabled in your compilation?

**Comment by Delagen** [comment]
```
"angularCompilerOptions": {
		"genDir": "./generated",
		"skipMetadataEmit": true
	},
```

**Comment by Delagen** [comment]
As I see in https://github.com/angular/angular/blob/master/packages/compiler-cli/src/main.ts#L43
I would prefer to compiler-cli to be able to emit only typescript code (not compiled), but I cannot do it with any options

**Comment by alexeagle** [comment]
angular 5 no longer produces generated .ts code, it is all compiled in one pass. this is because we now use a better architecture with TypeScript transformers. There is no option to go back to .ts codegen.

It sounds like using `annotationsAs: "decorators"` might be a workaround for you?

I agree that tsickle processing shouldn't wrap the import keyword in parens.

**Comment by Delagen** [comment]
Angular use now import() for lazy load so this seems fixed now
