### ISSUE TITLE
Tsickle generates duplicate file-level comments

### ISSUE THREAD

**Issue by voithos** [angular/tsickle#637]
Given a TypeScript file like the following:

```
/** Blahblah */

import '...';
import {...} from '...';
```

Tsickle generates:

```
goog.module('...');
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
/** Blahblah */

/** Blahblah */
var tsickle_module_0_ = ...
```

Notice that the file-level comment gets duplicated. Interestingly, if the comment included a JSDoc annotation, and was more like `/** @someAnnotation */`, the output still includes duplication but it also seems to merge some of the comments:

```
goog.module('...');
/**
 * @someAnnotation
 * @suppress {checkTypes} checked by tsc
 */

/** @someAnnotation */
var tsickle_module_0_ = ...
```

**Comment by mprobst** [comment]
This has been fixed I think.
