### ISSUE TITLE
Unknown type flag 320 error when Enums are used as an argument type

### ISSUE THREAD

**Issue by seanl-adg** [angular/tsickle#644]
I've been using tsickle for projects which have zero or few third-party dependencies, and this issue have been blocking usage `--typed` option.

**How to reproduce:**

```
const enum Enum {
    item
}

class MyClass {
    myMethod(arg:Enum):Enum {
        return arg;
    } 
}
```
I am using tsickle 0.25.0 and typescript 2.5.3 from npm. When I run `tsickle --typed` in a command line, I get the following error, and the transpilation fails:
```
Error: unknown type flags 320 on {type flags:0x140 NumberLiteral EnumLiteral symbol.name:"item"}
```
whereas, the normal `tsc` works without issues.

**Comment by mprobst** [comment]
What version of TypeScript and tsickle are you using? This sounds a bit
like a version mismatch. We used to have this issue, but iirc fixed it with
this code here:
https://github.com/angular/tsickle/blob/6887367e69673160ef76d6a011b5d3d9d1217ad2/src/tsickle.ts#L1423

**Comment by seanl-adg** [comment]
Hi, the above issue is reproduced with tsickle version 0.25.0 and typescript version 2.5.3 on my environment.

**Comment by mprobst** [comment]
Odd. The code printing that error is, in the latest version, immediately preceded by code checking for the `EnumLiteral`.

Can you check the translated code in `type-translator.js` in your `node_modules` folder? Look for the string `unknown type flags` in the file, and check what's immediately preceding that?

**Comment by seanl-adg** [comment]
My bad, I was mistaken aboit the tsickle's version. The issue is resolved after re-installing the latest version, thanks!
