### ISSUE TITLE
Install Renovate

### ISSUE THREAD

**Issue by rarkins** [angular/tsickle#673]
Transferring the discussion from https://github.com/angular/angular/issues/21023#issuecomment-351823851

As suggested by @alexeagle, I've made available a [Forking Renovate](https://github.com/apps/forking-renovate) App which requires only read-only code permissions for OSS projects, as it submits its PRs from its own fork of each repository.

It's been tested on [the Renovate source repository](https://github.com/renovateapp/renovate) itself, as well as [a fork of this tsickle repository](https://github.com/renovate-tests/tsickle). It started with the [Pin Dependencies](https://github.com/renovate-tests/tsickle/pull/2) PR to lock down exact versions and then proceeded to raise [12 update PRs](https://github.com/renovate-tests/tsickle/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Arenovate-bot+) once that was complete.

**Comment by alexeagle** [comment]
No objection from the tsickle team for using renovate.

I tried to enable it just now, but the install button on the Forking Renovate app only offers to install on my own personal repos, not those under the angular org. Is that something you can fix on your side?

**Comment by rarkins** [comment]
I'm pretty sure there's no setting on my side that is limiting installations only to personal repositories. The only control similar is making it "Internal" but that would block you completely if selected:

![image](https://user-images.githubusercontent.com/6311784/34287944-aed5776c-e6ea-11e7-9b26-1c4412bb7bf4.png)

Are you able to check if you are able to install any other apps on the angular org right now? e.g. not going through with the install but at least to the same step you're blocked at now? If that works then I'll raise an issue with GitHub on behalf of the app.

**Comment by alexeagle** [comment]
Everyone else's apps come from this marketplace and have a different
startup flow where they talk payment first
eg. https://github.com/marketplace/accesslint

where is another app that's like yours?

**Comment by rarkins** [comment]
Yes, Marketplace is for apps who have negotiated a kind of distribution agreement with GitHub. If you don't charge then you are not eligible for Marketplace, as I understand it.

GitHub seem to have made it really hard to find free "apps" anymore. Even https://github.com/apps redirects to Marketplace, i.e. paid-only.

Anyway, I browsed through https://github.com/works-with until I found something similar - https://github.com/apps/ImgBot

When I click on it, it gives me the option to install into the renovateapp organisation using or my personal account:

![image](https://user-images.githubusercontent.com/6311784/34288570-4b32f4c4-e6ee-11e7-9754-c282daf32250.png)

**Comment by alexeagle** [comment]
Nope, for me it skips past that option, no idea why??

![aoeuaoeu](https://user-images.githubusercontent.com/47395/34302622-8eeadcde-e6e6-11e7-8de0-319b3e0d5a4d.png)

![aoeuaoeu2](https://user-images.githubusercontent.com/47395/34302625-962f7dc4-e6e6-11e7-8b0e-6bc3cc0bf461.png)

**Comment by rarkins** [comment]
I’ve found GitHub’s support@ email address to be pretty responsive. Maybe ask them if extra permissions are required or it’s a bug? I’m probably the *owner* of the renovateapp org so not a good comparison.

**Comment by alexeagle** [comment]
I just sent them a request to help

**Comment by alexeagle** [comment]
Ah, interesting, it's because I'm not an owner of any orgs, it skips a screen entirely. I did it with @IgorMinar on his machine and there was an intermediate screen where you select an org.

This is enabled now, and assuming we like it, we'll do this for angular/angular next - that will be big visibility for renovate - be ready :)
