### ISSUE TITLE
Possible bad output for function type that has "this"

### ISSUE THREAD

**Issue by YoungCatChen** [angular/tsickle#686]
This typescript snippet:

```
function foo(): ((this: string) => string)|undefined {
  return undefined;
}
```

is passed to tsickle, which generates this javascript snippet:

```
/** @fileoverview... */
goog.module('a');var module = module || {id: 'a.js'};/**
 * @return {function(this: (string), ): string}
 */
function foo() {
    return undefined;
}
//# sourceMappingURL=a.js.map%
```

With the function type `function(this: (string), )` a trailing comma is placed before the ")". The closure compiler is having a problem to compile it.

Could you please let me know if it's a valid issue and how we can work around it? Thanks!

**Comment by evmar** [comment]
This is definitely a bug.  You might be able to work around it via a type alias, like

```
type F = ((this: string) => string);
function foo(): F|undefined { ... }
```

**Comment by YoungCatChen** [comment]
Thanks for confirming the bug!

Unfortunately isolating the type doesn't really work; it just changes the place of the bug:

```
/** @typedef {function(this: (string), ): string} */
var F;
```

**Comment by YoungCatChen** [comment]
Thanks Martin!
