### ISSUE TITLE
Closure Compiler already support ES6 completely

### ISSUE THREAD

**Issue by jsNDA** [angular/tsickle#724]
Your project is awesome, but google closure compiler already supports ES6 completely. You no longer need to write a JSDOC for compilation.
[https://github.com/google/closure-compiler/wiki/ECMAScript6](Status of ES6 support in Closure Compiler)

**Comment by evmar** [comment]
Can you be more specific about the issue you're reporting?  Not sure I followed.

**Comment by mprobst** [comment]
Closing old issues, please reopen if still current.
