### ISSUE TITLE
support for @this in functions

### ISSUE THREAD

**Issue by ribrdb** [angular/tsickle#775]
I'm getting this error:
`Error: cannot merge differing tags: [{"tagName":"this","optional":false,"type":"S"},{"tagName":"param","optional":false,"parameterName":"a","type":"(null|string|!ArrayLike<T>)"}]`
I think it came from this TS declaration:
`function forEach<T = any, S = any>(
        this: S, a: ArrayLike<T>| null | string,
        b: ((a: T, b: number, c: any) => any) | null, c: S): any;`

**Comment by evmar** [comment]
Is it possible you have overloads of `forEach`?  I stared at the code a bit and that is my best guess.

**Comment by mprobst** [comment]
I think the problem is that TypeScript surreptitiously reports the `this`
parameter as an implicit parameter #0 preceding all others. tsickle then
presumably mixes up the this parameter at #0 with another overload that has
an actual parameter at #0.

**Comment by ribrdb** [comment]
Oh, i didn't notice that. Yes, I have:
```
    function forEach<T = any, S = any>(
        this: S, a: ArrayLike<T>| null | string,
        b: ((a: T, b: number, c: any) => any) | null, c: S): any;
    function forEach<T = any>(
        a: ArrayLike<T>| null | string,
        b: ((a: T, b: number, c: any) => any) | null): any;
```

**Comment by evmar** [comment]
Yep, Martin and I were guessing at the same thing.

See the code around here:
  https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L257
I think maybe the fix is to not treat @this as a parameter in the following logic, if you wanted to try to fix this.

**Comment by ribrdb** [comment]
Well I'm less concerned if the problem has to do with the overrides. If I need to I can just get rid of that override, especially since the TS code can just use arrow closures instead of passing in the context object.
I'm more concerned with figuring out why bazel is running my closure-library.d.ts through tsickle in the first place.

**Comment by evmar** [comment]
@alexeagle knows this stuff.  I think our bazel<->clutz stuff isn't public yet, under the assumption that most people aren't using closure library.

**Comment by alexeagle** [comment]
Right, I'm not planning to integrate clutz under Bazel. The Bazel `ts_library` rule does use tsickle on its production mode `*.closure.js` outputs, assuming that closure compiler is one possible optimizer you might want to use.

**Comment by ribrdb** [comment]
I've gotten clutz working for me at https://github.com/ribrdb/rules_closure/tree/ts
I didn't know what to do with the depgraph stuff so I'm just running it in incremental mode. Mostly it works but there's some things that don't get the right declarations. For those I've been fixing them manually and doing:
ts_library(srcs=["my-foo.d.ts"], runtime_deps=[":foo"])
Looking at the source again, I guess that needs to be ts_declaration to avoid running my-foo.d.ts through tsickle.

**Comment by alexeagle** [comment]
Ryan, can you tell me more about your use case? Do you have an existing
closure JS codebase and use Closure Compiler on it, but migrating the
middle of the graph to TypeScript? I only knew that Google and Lucidchart
were doing that.

**Comment by ribrdb** [comment]
I'm not sure what you mean by "middle". But yeah, I have a Closure JS codebase compiled with rules_closure. I'm trying to migrate all our js code to typescript. So every ts_library depends on the closure library, and some also depend on protobufs or soy templates.

**Comment by alexeagle** [comment]
So you only need clutz to provide typescript typings for the standard
closure library and your protobufs? Those two use cases don't necessitate
using clutz to generate the typings. There are static typings available for
the closure libarry (eg. https://github.com/teppeis/closure-library.d.ts  -
I thought there was one on DefinitelyTyped too) and
github.com/dcode/protobufjs has a typings generator from .proto files.
So far I've been avoiding introducing the complexity of clutz into the
Bazel toolchain.

**Comment by ribrdb** [comment]
Also closure templates.
The clutz part is pretty small. I could easily keep that in our internal stuff, but it seemed to me like it could be useful to others:
 - I see people asking about closure_js_proto_library in rules_typescript. (maybe dcodeIO/ProtoBuf.js would be better for this though)
 - Someone writing closure js code could generate .d.ts files to get better intellisense in an ide. Maybe no one needs this either.

**Comment by alexeagle** [comment]
my assumption has been that closure library and closure-typed JS both have so little adoption (outside of Google) that it's not worth the complexity.
I'll work on the example of doing protobufs in rules_typescript which should help illuminate a working path

**Comment by evmar** [comment]
It sounds like the original issue reported has a workaround, and the latter discussion could maybe go into a new bug if there was something specifically actionable.
