### ISSUE TITLE
Latest version (0.27.3) is broken

### ISSUE THREAD

**Issue by rosen-vladimirov** [angular/tsickle#781]
Hey guys,
The latest version seems broken - the src directory contains only `.ts` files, so trying to install the package fails at the link step (as the package.json defines creation of bin link to src/main.js).
This also breaks the installation of `@angular/compiler-cli`.

**Comment by matiskiba** [comment]
also experiencing the same. broke my build

**Comment by cfremgen** [comment]
Any known workaround? Hardcode to prior version in package.json?

**Comment by hurstliverez** [comment]
@cfremgen yes, for now i installed tsickle@0.27.2 in devDependencies and that works

**Comment by o33ik** [comment]
I also have a trouble with build

npm ERR! path /Users/bodya/Documents/coding/work/mathhelp/public/angular/node_modules/tsickle/src/main.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/bodya/Documents/coding/work/mathhelp/public/angular/node_modules/tsickle/src/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by mprobst** [comment]
Fixing in https://github.com/angular/tsickle/pull/782.

**Comment by cfremgen** [comment]
npm install tsickle@0.27.2 --save

May have to wipe node_modules folder first.

**Comment by SamMade** [comment]
they just patched to 0.27.5 so it should be working now

**Comment by maciejtreder** [comment]
On my end I needed also to update package.json, to match exact version:

```"tsickle": "0.27.2"```

**Comment by alan-agius4** [comment]
Confirmed it is solved in v0.27.5

**Comment by blakecallens** [comment]
"I felt a disturbance in the force, as if thousands of web developers all screamed 'what the fuck?!'"

**Comment by mprobst** [comment]
@blakecallens yeah, sorry.

The tsickle package is depended upon in a non-hermetic way in some places (either in your npm config itself, or via bazel), so any updates go straight to folks instead of requiring an explicit upgrade. It's a known issue, we'll need to fix that.

**Comment by evmar** [comment]
I thought the whole deal with semver is that 0.x means "every change is potentially breaking", which means apps shouldn't blindly be picking up new 0.x.y versions.

**Comment by dwieeb** [comment]
@evmar https://github.com/angular/angular/blob/master/packages/compiler-cli/package.json#L14

```
> semver.satisfies('0.1.0', '^0.1.0')
true
> semver.satisfies('0.2.0', '^0.1.0')
false
```

Under `0.x.y` versions, `x` ("minor" changes) are potentially breaking, `y` ("patch" changes) are not.

**Comment by evmar** [comment]
As far as I understood it, the rules about what .x.y mean only apply when the first digit is >0.
https://semver.org/#spec-item-4 and the next few bullets.

**Comment by alexeagle** [comment]
It's true that we broke it according to semver.
However, anyone affected by this should consider using a lock file so that any change to your dependencies happens when you make a change, not as an interrupt.

**Comment by evmar** [comment]
No, I'm saying the opposite: we did the right thing per semver, and I don't understand why it broke anyone.

**Comment by alan-agius4** [comment]
Well, for npm semver though 0.27.3 is compatible with `^0.27.2` and with
`~0.27.2`.

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by alan-agius4** [comment]
Well, for npm semver though 0.27.3 is compatible with `^0.27.2` and with `~0.27.2`.

https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

> it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.
