### ISSUE TITLE
Clutz compatibility emit (module$..., type =, const ...) is syntactically incorrect

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#789]
tsickle emits a re-export line for compatibility with Clutz:

```ts
export declare type x = number;
declare global {
	namespace ಠ_ಠ.clutz {
		const module$contents$test_files$basic$declaration$basic_x: typeof x;
	}
	namespace ಠ_ಠ.clutz.module$exports$test_files$basic$declaration$basic {
		const x: typeof module$contents$test_files$basic$declaration$basic_x;
	}
}
```

This works for all exported values, but is broken for non-values (type, interface), because `typeof` does not work on them.

Exporting them as aliases works for both values and types:

```ts
export declare type x = number;
declare global {
	namespace ಠ_ಠ.clutz {
		export {x as module$contents$test_files$basic$declaration$basic_x};
	}
	namespace ಠ_ಠ.clutz.module$exports$test_files$basic$declaration$basic {
		// still needed to avoid a circular reference for x, as there is no ::global::x or similar.
		export {module$contents$test_files$basic$declaration$basic_x as x};
	}
}
```

**Comment by rkirov** [comment]
Yes, this is a natural followup to https://github.com/angular/clutz/commit/cc9c9e6c8ca704aa05b5a3ec6e15ddf73d0c9a23 , which ironically is also blocked on tsickle emitting incorrect types coming from clutz.

**Comment by mprobst** [comment]
I believe we've at least partially implemented this already? See https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L230.

**Comment by evmar** [comment]
Gonna call it fixed then.
