### ISSUE TITLE
Don't forward declare if `googmodule` is false

### ISSUE THREAD

**Issue by choumx** [angular/tsickle#797]
Don't emit goog.forwardDeclare if goog.module conversion is disabled.

This is useful for JS projects that use (1) Closure Compiler and (2) ES6 modules (not Closure modules) that wish to incrementally start including TS files while preserving existing toolchain. 

TODOs per discussion with @mprobst:
- [ ] If `googmodule` is false, short circuit emittance of `getForwardDeclareText()`
- [ ] Add golden file tests for this use case

Context: #758

**Comment by evmar** [comment]
We no longer goog.forwardDeclare, we goog.requireType.  That probably means the same thing for this bug, but I think it then ends up being a dup of #1061, please correct me if I'm wrong!
