### ISSUE TITLE
Placing a comment in a single statement arrow function triggers ASI

### ISSUE THREAD

**Issue by interrobrian** [angular/tsickle#802]
tsickle produces incorrect JavaScript when it encounters a single statement arrow function with a line comment between the arrow and the statement. This bug prevents the body of the arrow function from executing. For example, this:
```
const foo = () =>
  // Print "bar"
  console.log("bar");
```
produces:
```
/**
 * @fileoverview added by tsickle
 * @suppress {checkTypes} checked by tsc
 */
goog.module('_..index');var module = module || {id: 'index.js'};var /** @type {function(): void} */ foo = function () {
    // Print "bar"
    return 
    // Print "bar"
    console.log("bar");
};
```
Note that the comment was duplicated, and the duplication was placed on a line between `return` and the actual body of the function, triggering JavaScript ASI and exiting the function prematurely.

The following `tsconfig.json` was used with no additional `tsickle` options:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "experimentalDecorators": true
  }
}
```

May be related to [this issue](https://github.com/angular/tsickle/issues/57).

**Comment by mprobst** [comment]
Also fixes https://github.com/angular/angular/issues/23829.
