### ISSUE TITLE
Properly externing methods and properties for a global App [Question]

### ISSUE THREAD

**Issue by orenmizr** [angular/tsickle#819]
Hi, this is a "How To" question since i could not find in the docs. 
i'd like  **App** variable to be my global and it's **compress** prop and **monitor** method to be available as public apis (should not be compressed or eliminated by closure) 

i am guessing that my App.d.ts should have some kind of declare. 

/* App.ts */
```
import { Utils } from "./Utils";
// import { IContext } from "./IContext";

interface IDisposer {
    dispose(): void;
}

interface IMonitorApi {
    monitor():void;
}

interface IApp extends IDisposer, IMonitorApi {
    stop(): void;
}

export class App implements IApp { 
    public context: IContext;
    public compress: string;
    monitor() {
        console.log('monitor!');
        console.log(Utils.monitorVersion)
    }
    dispose() {
        console.log('dispose!');
    }
    stop(){
        console.log('stop!')
    }
}
```

**Comment by evmar** [comment]
Sorry for not responding.  I think this is a Closure question and it's discussed here

https://developers.google.com/closure/compiler/docs/api-tutorial3#dangers
