### ISSUE TITLE
tsickle may generate invalid type for Required<T> in TS 2.8

### ISSUE THREAD

**Issue by YoungCatChen** [angular/tsickle#822]
```typescript
export interface X {}
export interface Y extends Required<X> {}
```

is converted to

```js
/**
 * @record
 */
function X() { }
exports.X = X;
function X_tsickle_Closure_declarations() {
}
/**
 * @record
 * @extends {Required}
 */
function Y() { }
exports.Y = Y;
function Y_tsickle_Closure_declarations() {
}
```

where `@extends {Required}` looks suspicious. I think the Closure Compiler may not have a type named `Required`.

Is this a bug or did I misconfigured anything?

Thank you in advance.

**Comment by evmar** [comment]
For types found the TypeScript standard library, tsickle assumes there's a matching Closure definition.  This is true of stuff like Document or HTMLElement but for weirder types like these we have this file:
https://github.com/angular/tsickle/blob/master/src/closure_externs.js

**Comment by YoungCatChen** [comment]
As closure compiler doesn't support type parameter in its typing system, (does it?) I think extra care may have to be taken in these cases as well as cases like Partial<T>, Readonly<T>, etc. that are documented in http://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types and were introduced since ts 2.1.

For example, if 

```ts
export interface X { foo?: number; }
export interface Y extends Required<X> {}
```

then the output should be like

```js
/** @record */
function X() { }
function X_tsickle_Closure_declarations() { /** @type {(undefined|number)} */ X.prototype.foo; }
/** @record */
function X_Required() { }
function X_Required_..._declarations() { /** @type {number} */ X_Required.prototype.foo; }
/** @record @extends {X_Required} */
function Y() { }
function Y_tsickle_Closure_declarations() { }
```

where an extra interface was added because of the use of `Required<X>`. The interface may named like `X_Required`; it should duplicate `X`'s properties, striping off all `undefined` type.

But that requires tsickle to understand some typescript semantics and it may or may not be the best way to translate this. As I'm not familiar with tsickle's code, let me leave the decision to you and your team and hope a plan and implementation will come soon.

**Comment by evmar** [comment]
I was wondering about how this worked normally because I know plenty of Google code already uses these types.  I looked into this a bit more and I think maybe you're hitting a special extra bug.

Required<T> is actually a type alias, and I think for type aliases we actually emit the code after alias expansion (see example input/output https://github.com/angular/tsickle/tree/master/test_files/generic_type_alias ).

In your case the problem is that you 'extends' a type alias, which in Closure I suspect requires a named type (like "interface").  Fixing this totally is probably pretty annoying.

**Comment by YoungCatChen** [comment]
I'm a google employee actually :) I'm xuexuan@.

I came across this issue because the `X` thingy above is a proto3 type through `js_typedef()` build rule. I wanted my own `Y` type to have all the fields solid (no undefined).

As I looked into other Google code that uses `Partial<T>` or `Required<T>`, I got what you said about `type`s and `interface`s. I made similar change in my project:

```ts
export type Y = Required<X>;
// or //
export type Y = Required<X> & { foo: SomeStrickerType };
```

and then the build passed. It's not ideal, of course, because the output was:

```js
/** @typedef {?} */
var Y;
exports.Y = Y;
```

Hopefully one day `interface`s will benefit from type aliases!

**Comment by mprobst** [comment]
I'm wondering whether we should special case `Required<T>` to map to just
`<T>`. In TS, `Required` is not a language feature but just some code, but
on the other hand it's a builtin in the standard library, and we cannot
express the feature in Closure (not even with TTL I think). We don't have a
facility for adjustments like that yet though - we'd need to teach
`type-translator.ts` to figure out if a specific `Required` is actually the
`Required` from `lib.d.ts`. Not sure how confident we can be there, it's
all a bit mushy once file paths get involved...

**Comment by evmar** [comment]
This ends up being a dup of #888 I think.
