### ISSUE TITLE
transformers running after tsickle can receive nodes that do not have `.getSourceFile()`

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#842]
Noticed this while trying to land https://github.com/angular/angular/pull/24572. The PR just adds '!' to a number of fields in tests, but as a random side effect this caused tsickle emitted nodes to start throwing on `.getSourceFile()`.

//cc @alxhub

**Comment by mprobst** [comment]
Not sure if this is a bug in tsickle, I don't think there's a general guarantee that AST nodes have their `SourceFile` set. You might need to call `ts.getOriginalNode` to get to the source file.

**Comment by rkirov** [comment]
Also, I am shocked that just adding `!` and a comment triggers the bug. Will try to file something upstream with TS, transformers are too finicky.
