### ISSUE TITLE
build error when a method has documentation with annotations above it ie. @param #964

### ISSUE THREAD

**Issue by aykutyararbas** [angular/tsickle#863]
Please also refer to issue at: 
https://github.com/dherges/ng-packagr/issues/964#issuecomment-403762925

Type of Issue
Build error

[X] Bug Report
[ ] Feature Request
Description
Adding doc with method signature annotations causing packager to error.

LIKE
BUILD ERROR
src/app/common/featureflags.service.ts(59,3): warning TS0: the type annotation on @param is redundant with its TypeScript

Example service method

/**

Returns the service label for a given service
Returns the id , if the service is not available
@param {string} id
@returns {string}
*/
public getServiceLabel(id: string): string {
if(this.SERVICE_REGISTRY[id]) {
return this.SERVICE_REGISTRY[id].label;
} else {
return id;
}
}
How To Reproduce
Steps
1 - Add a documentation to one of your service
Like the one above start with / * * and add @param
End your documentation

2 - Run ng-packagr -p ng-package.json

Can you reproduce the error in the integration tests in ng-packagr?
If possible, take a look at the integration/samples and try to break one of >>these builds!

Is the error you faced in an application importing the library
Try to break the Angular CLI app in integration/consumers/ng-cli!

Expected Behaviour
A bug: please describe what behavior or result you expected
Build without erroring out.

Version Information
$ node_modules/.bin/ng-packagr --version
ng-packagr: 5.6.0
@angular/*: 5.2.10
typescript: ~2.6.2
"rxjs": "^5.5.11",
node: v8.11.1
npm: 5.6.0
Please include all version numbers that might be relevant, e.g. third-party libraries

Thanks and regards,

Aykut~

**Comment by evmar** [comment]
Why not remove the {string} ?

**Comment by aykutyararbas** [comment]
Well, it is the documentation portion of it, like in the Java Docs. 
When you remove that standard representation of the method's parameters you'll not be able to pass any type in the documentation, at the end any doc builders will not be able to use it.

The main issue seems to be 'context'.  When building/ compiling if you are in the documentation, you can easily ignore these lines.

**Comment by jscharett** [comment]
This "feature" seems to make it impossible to compile large angular apps/libraries that have made use of the type info.  Granted, it may be irrelevant, but for a large library, its very painful to have to go and "correct" this.  And the kicker, its just a comment, not actual code!  It would be much better to send it out as a warning vs an error.

**Comment by evmar** [comment]
As included in the original report, this is a warning, not an error:

src/app/common/featureflags.service.ts(59,3): warning TS0: the type annotation on @param is redundant with its TypeScript

I'm not clear which thing here is calling tsickle, but that layer might want to not fail the build on warnings, and perhaps also might want to ignore tsickle warnings entirely.  tsickle returns this warnings via its API, so it's the caller's responsibility to decide what to do with them.

**Comment by evmar** [comment]
Because of this, I believe this is not a bug in tsickle.  I'd be happy to be corrected if I'm wrong.

**Comment by matheusdavidson** [comment]
My solution, in angular 7, was change my ```tsconfig.lib.json``` config, 

from this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": true
    ...
    ...
}
```
to this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": false
    ...
    ...
}
```
