### ISSUE TITLE
some conditional types crash tsickle

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#865]
The following makes tsickle throw:

```typescript
export type Filter<T, U> = T extends U ? T : never;
export function ofType(): Filter<string, string> {
  return null as any;
};

```

believe it or not this is real-world code from https://github.com/ngrx/platform/pull/1183/files#diff-37851f2da2623baafce63a5976e8d86b

**Comment by evmar** [comment]
What is the return type of this function?  What is the Closure return type of this function?

**Comment by rkirov** [comment]
sorry, my repro was wrong. It should be self-contained now, turned to be simply conditional types.

**Comment by evmar** [comment]
I have the same question though -- what type should tsickle be giving to Closure in this case?

**Comment by rkirov** [comment]
`?` because it is inexpressible in the closure type system.

**Comment by rkirov** [comment]
Unless we are comfortable with declaring parts of TS off limits for g3, because tsickle_typed cannot express them?

**Comment by mprobst** [comment]
I ran into this with my transformers change, too. I think we should do `?` for the time being - though this does look like it'd be moderately easy to express in TTL.
