### ISSUE TITLE
Iterable literals have bad type annotations

### ISSUE THREAD

**Issue by jplaisted** [angular/tsickle#883]
For some reason the emitted code tries to have a type annotation with a field named `__@iterable`, which the Closure Compiler thinks is another annotation rather than a property name. Even then the type would be incorrect; the property should be `Symbol.iterator` not `__@iterable`. Though Closure doesn't really have support for symbols in literal types - however it does have a `Iterable`/`Iterator`/`IteratorIterable` externs that should probably be used instead.

TypeScript:

```
    const iterable = {
      [Symbol.iterator]() {
        const elems = ['c', 'a', 'b'];
        return {
          next() {
            return elems.length ? {value: elems.shift(), done: false} :
                                  {value: undefined, done: true};
          }
        };
      }
    };
```

Emitted Closure code:

```
/** @type {{__@iterator: function(): {next: function(): {value: string, done: boolean}}}} */
        const iterable = {
          // ...
```

Error:

```
ERROR - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
        /** @type {{__@iterator: function(): {next: function(): {value: string, done: boolean}}}} */
```

**Comment by evmar** [comment]
As a crazy coincidence, I think I just fixed this in https://github.com/angular/tsickle/pull/882 (not yet submitted).
But it just skips the property in the type, so it might have consequences elsewhere.

**Comment by evmar** [comment]
I submitted this into tsickle, trying the google3 sync now.  It seems relatively safe because we're only dropping properties that were already invalid.
