### ISSUE TITLE
TSickle doesn't handle Anonymous Classes

### ISSUE THREAD

**Issue by 12wrigja** [angular/tsickle#893]
I tried to compile the output from tsickle of a class that has an anonymous class within a function returns a type that the Closure Compiler doesn't seem to like. For example: https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/ast.ts#L135

Running tsickle against this file produces the following output:
```
/**
 * @param {!Array<!Node>} nodes
 * @param {number} position
 * @return {!tsickle_forward_declare_1.AstPath<!Node>}
 */
function findNode(nodes, position) {
    /** @type {!Array<!Node>} */
    const path = [];
    /** @type {!(Anonymous class)} */
    const visitor = new class extends RecursiveVisitor {
        /**
         * @param {!Node} ast
         * @param {?} context
         * @return {?}
         */
        visit(ast, 
```

The Closure Compiler then complains about the `@type {!(Anonymous class)}`.

Note that I ran into this problem while working internally at Google, so I'm not sure what settings were used with tsickle to produce this output.

**Comment by evmar** [comment]
This is fixed in https://github.com/angular/tsickle/pull/892 but I have to verify it doesn't break anyone.

**Comment by 12wrigja** [comment]
Awesome! Thanks Evan.
