### ISSUE TITLE
Tsickle generated code doesn't compile due to constant property reassignment

### ISSUE THREAD

**Issue by 12wrigja** [angular/tsickle#894]
While trying to compile the output from running tsickle against the Angular Upgrade module the Closure Compiler generates an error that a constant property is being assigned a value more than once. 

The source TS: https://github.com/angular/angular/blob/master/packages/upgrade/src/common/angular1.ts#L290
Specifically, the version export.

The generated JS for that line looks like this:
```
/** @type {{major: number}} */
exports.version = angular.version;
```

And the compiler error I get looks like this: 
ERROR - constant property version assigned a value more than once

**Comment by 12wrigja** [comment]
Also, much like in #893, I ran into this while doing internal development at Google, and am not sure what tsickle settings were used to generate this.

**Comment by evmar** [comment]
Sorry for not commenting earlier, but the source TS is now a 404.
