### ISSUE TITLE
"Abstract class implementing type" conversion produces error

### ISSUE THREAD

**Issue by alex-okrushko** [angular/tsickle#912]
code
```ts
export type DictionaryNum<T> = {
  [id: number]: T;
};

export abstract class Dictionary<T> implements DictionaryNum<T> {
  [id: string]: T;
}
```

produces:
```ts
/** @typedef {!Object<number,?>} */
exports.DictionaryNum;
/**
 * @abstract
 * @template T
 * @implements {__type}
 */
class Dictionary {
}
exports.Dictionary = Dictionary;
/** @typedef {{id: string, changes: ?}} */
```
which throws the error message:
```
JS did not compile successfully! ERROR:

path/to/ngrx/modules/entity/src/models.closure.js:53: ERROR - missing require: '__type'
class Dictionary {
^^^^^^^^^^^^^^^^^^
```

source is coming from OSS: [models.ts](https://github.com/ngrx/platform/blob/c024776a5122e5d961960c58e6cf5306198add2f/modules/entity/src/models.ts#L21-L27)

WORKAROUND:
Changing `export type DictionaryNum<T> = ` to `export interface DictionaryNum<T> ` works fine.

**Comment by mprobst** [comment]
I think @evmar has a fix in the works for `__type` there.

**Comment by evmar** [comment]
Yes, this is fixed in https://github.com/angular/tsickle/pull/910 , I just need to verify it doesn't break anything else.
