### ISSUE TITLE
tsickle@0.33.0 requires a peer of typescript@git://github.com/mprobst/TypeScript.git#5456479a4a

### ISSUE THREAD

**Issue by rdhelms** [angular/tsickle#919]
Using 
```
@angular/cli@7.0.1
npm@6.4.1
node@8.11.3
```

Steps to reproduce:
```
ng new example
cd example/
ng g library example-lib
```

Output:
```
CREATE projects/example/karma.conf.js (968 bytes)
CREATE projects/example/ng-package.json (156 bytes)
CREATE projects/example/package.json (167 bytes)
CREATE projects/example/tsconfig.lib.json (726 bytes)
CREATE projects/example/tsconfig.spec.json (246 bytes)
CREATE projects/example/tslint.json (317 bytes)
CREATE projects/example/src/public_api.ts (159 bytes)
CREATE projects/example/src/test.ts (700 bytes)
CREATE projects/example/src/lib/example.module.ts (229 bytes)
CREATE projects/example/src/lib/example.component.spec.ts (635 bytes)
CREATE projects/example/src/lib/example.component.ts (259 bytes)
CREATE projects/example/src/lib/example.service.spec.ts (338 bytes)
CREATE projects/example/src/lib/example.service.ts (136 bytes)
UPDATE angular.json (4971 bytes)
UPDATE package.json (1446 bytes)
UPDATE tsconfig.json (534 bytes)
npm WARN tsickle@0.33.0 requires a peer of typescript@git://github.com/mprobst/TypeScript.git#5456479a4a but none is installed. You must install peer dependencies yourself.

added 107 packages from 88 contributors in 13.226s
```

I have no idea where this is coming from, because obviously that's not the peer dependency listed in https://github.com/angular/tsickle/blob/master/package.json.

I tried doing a `npm cache clean --force` in case that was relevant, but with no effect.

**Comment by escalonn** [comment]
The release must have been done incorrectly on a different package.json.
`npm view tsickle@0.33.0 peerDependencies` reveals the repo dependency you are seeing.
There is no published `tsickle` version marked compatible with TS 3.1 and thus the dependency is unsatisfiable.

**Comment by Vaelor** [comment]
Getting the same error when using `ng update` (Updating to 7.X.X) - forcing seems to works at least.

**Comment by mprobst** [comment]
I think @alexeagle did that release, any idea what's up here?

We now do have a newer version of tsickle that works with TS 3.1, but hasn't seen a formal release.

**Comment by mprobst** [comment]
I think @alexeagle did that release, any idea what's up here?

We now do have a newer version of tsickle that works with TS 3.1, but hasn't seen a formal release.

**Comment by kishok** [comment]
I am also facing the same issue in tsickle@0.33.0 and also i can't build my schematics getting this error 
```
SourceFile' is not assignable to parameter of type 
  Types of property 'kind' are incompatible.
    Type 'ts.SyntaxKind.SourceFile' is not assignable to type 'ts.SyntaxKind.SourceFile'. Two different types with this name exist, but they are unrelated.

  const nodes = getDecoratorMetadata(source, 'NgModule', '@angular/core');
```
but it works with typescript@2.9.2 and tickle@0.32.1 but angular 7.0 requires typescript@>3.1.1  Please provide some solution asap.

**Comment by fr0** [comment]
> We now do have a newer version of tsickle that works with TS 3.1, but hasn't seen a formal release.

Not sure how to reconcile that with the Angular 7 [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md):

> @angular/core now depends on
> TypeScript 3.1
> RxJS 6.3

**Comment by alexeagle** [comment]
Angular 7 no longer has any dependency on tsickle. Maybe tsickle appears in your own package.json as a dependency of your app? In that case you should remove it.
/cc @stephenfluin

**Comment by rdhelms** [comment]
@alexeagle Angular 7 applications don't depend on tsickle, but Angular libraries still do. See the above steps to reproduce which involve using `ng g library`

Here's the schematic run by `ng g library` that adds tsickle as an npm dependency:
https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/library/index.ts#L112

And the relevant addition, along with ng-packagr:
```
      {
        type: NodeDependencyType.Dev,
        name: 'ng-packagr',
        version: '^4.2.0',
      },
      {
        type: NodeDependencyType.Dev,
        name: 'tsickle',
        version: '>=0.29.0',
      },
```

**Comment by alexeagle** [comment]
@rdhelms you're right, the bug is in angular-cli library support which writes package.json with incompatible version of tsickle.
https://github.com/angular/angular-cli/issues/12642
