### ISSUE TITLE
Please update to TypeScript 3.1.3

### ISSUE THREAD

**Issue by ToonvanStrijp** [angular/tsickle#925]
I can't update my Angular Material application since it has a dependency on tsickle. Due to this I can't update to 7.0.1 because it requires TypeScript 3.1.3 which tsickle does not support

**Comment by alexeagle** [comment]
Angular 7 no longer has any dependency on tsickle. Unless you use Closure Compiler, the fix is to remove tsickle from your dependencies.

**Comment by escalonn** [comment]
Cf. #919
