### ISSUE TITLE
Node module imports renamed with underscores

### ISSUE THREAD

**Issue by Chase-Silk** [angular/tsickle#928]
Node modules are being renamed from:
`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';`
to:
`goog.require('_.._angular.platform_browser_dynamic');` 
and cant be found by Google Closure Compiler. 

Slashes become dots and dashes become underscores. The @ is removed and prefixed with `_.._`

Is there a way to preserve node_module imports exclusively, or avoid renaming imports entirely?

tsickle script: `tsickle --typed --externs=./externs.js -- --lib es2015,es6,dom`

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "noEmitHelpers": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es6",
      "es2015",
      "dom"
    ]
  },
  "include": [
    "js/**/*.ts"
  ]
}

```
Dependencies:

```
"dependencies": {
    "@angular/common": "^6.1.9",
    "@angular/compiler": "^6.1.9",
    "@angular/core": "^6.1.9",
    "@angular/platform-browser": "^6.1.9",
    "@angular/platform-browser-dynamic": "^6.1.9",
    "@angular/upgrade": "^6.1.9",

    "rxjs": "^6.3.3"
  },
  "devDependencies": {
    "@types/angular": "^1.6.6",
    "@types/angular-resource": "^1.5.14",
    "angular-mocks": "^1.6.10",
    "clang-format": "^1.1.1",
    "google-closure-compiler": "^20171112.0.0",
    "google-closure-library": "^20171112.0.0",
    "karma-closure": "github:nckh/karma-closure",
    ...
    "tsickle": "^0.33.0",
    "typescript": "^2.7.2"
  }
```

**Comment by evmar** [comment]
@alexeagle

**Comment by mprobst** [comment]
I suspect the problem is that tsickle still does not produce the right
module names when run outside of bazel. Using slashes or something similar
won't help, the `goog.require()` name has to match the `goog.module()`
declaration in the file that's being imported.

**Comment by evmar** [comment]
This is another instance of the general 'cannot work with node_modules libraries' problem, in https://github.com/angular/tsickle/issues/1041 .
