### ISSUE TITLE
Typescript 3.2 update

### ISSUE THREAD

**Issue by IgorMinar** [angular/tsickle#937]
3.2 RC is out: https://github.com/Microsoft/TypeScript/releases/tag/v3.2-rc

Can you please update tsickle and release a new version on npm? thanks!

**Comment by evmar** [comment]
We are still working on getting past 2.9 (eek), but hopefully we can get to this soon.

**Comment by mprobst** [comment]
I've just tested, tsickle appears to work fine with TypeScript 3.2.0-rc without any chagnes.

@IgorMinar I presume you're not asking for a release based on a rc from TS, do you? What'd you like here?

**Comment by IgorMinar** [comment]
@mprobst you can release with peerDeps set to:

```
peerDependencies: "^3.2.0-rc"
```

That way we don't need to wait or create a new release once 3.2 is out in a few days unless there are new regressions.

**Comment by mprobst** [comment]
@IgorMinar PTAL, done.
