### ISSUE TITLE
tsickle@0.33.1 still depends on typescript@3.1.3

### ISSUE THREAD

**Issue by davidshen84** [angular/tsickle#938]
typescript@3.1.6 is out, but this package still depends on 3.1.3.

I got this warning when setting up my project which already has the latest typescript installed.

    npm WARN tsickle@0.33.1 requires a peer of typescript@3.1.3 but none is installed. You must install peer dependencies yourself.

I saw in issue #925, people explictly asked to update to typescript@3.1.3, and so the code really does so.

https://github.com/angular/tsickle/blob/69fd0d8db489913e66131918272d0d9f551f2f03/package.json#L20

But I think the dependency does not need to fix on minor versions. I think `^3.10` would be better.

**Comment by mprobst** [comment]
Fixed by #941.
