### ISSUE TITLE
Function declaration throws invalid rest param error

### ISSUE THREAD

**Issue by CSchulz** [angular/tsickle#944]
tsickle 0.33.1 and 0.34.0 throws "Error: invalid rest param"

```
declare function setImmediate<T extends unknown[]>(
  callback: (...args: T) => void,
  ...args: T
): number;
```

I am using it in context of Angular

<pre>
Angular CLI: 7.0.5
Node: 10.12.0
OS: darwin x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.5
@angular-devkit/build-angular      0.10.5
@angular-devkit/build-ng-packagr   0.10.5
@angular-devkit/build-optimizer    0.10.5
@angular-devkit/build-webpack      0.10.5
@angular-devkit/core               7.0.5
@angular-devkit/schematics         7.0.5
@angular/cli                       7.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.5
@schematics/angular                7.0.5
@schematics/update                 0.10.5
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
</pre>

**Comment by ggradnig** [comment]
I can confirm this error, it happens when spreading a generic array type parameter.

This works:

    function fn(...param: object[]): object[]

This doesn't:

    function fn<T extends object[]>(...param: T): T

**Comment by mprobst** [comment]
By the way, the workaround is moving the array-ness out of the constraint:

```typescript
function fn<T extends object>(...param: T[]): T[]
```

That's not quite the same thing - one allows subtypes of Array, the other doesn't, but it's probably what the author meant, and a lot more readable.
