### ISSUE TITLE
Create goog.module from module d.ts files

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#950]
When given a module d.ts file, e.g.

```
export type A = ...;
declare global {
  type B = ...;
}
```

tsickle needs to emit *two* files:

```
//////// file 1: externs
/** @externs */
/** @typedef or whatever */
const A;

/** @typedef or whatever */
const mangled$name$B;

//////// file 2: module
goog.module('module.name');
exports.B = mangled$name$B;
```

tsickle currently correctly emits the first file, but leaves out the second module file.  The second file is needed so that users that import this d.ts can refer to `module.name.B` in type annotations.

If there are any values inside the module, tsickle should just drop them for now, because there's no way to alias a value in a module.

## questions

Do we need to create an alias for each export?  Or will something like `exports = mangled$name;` be sufficient?  Will likely need an experiment.

**Comment by mprobst** [comment]
Another question: how do we handle .d.ts files that declare values, not
just types? Currently we don't generate anything and expect the user to
supply a shim.

**Comment by evmar** [comment]
This is basically a dup of the longer https://github.com/angular/tsickle/issues/1041 .
