### ISSUE TITLE
Combining tsickle with api-extractor 

### ISSUE THREAD

**Issue by DrRataplan** [angular/tsickle#970]
Hi,

We are using tsickle to convert typescript code to closure-compiler-ready code, this all works like a charm, but when we tried to integrate the [api extractor tool](https://github.com/Microsoft/web-build-tools/wiki/API-Extractor]), we ran into some issues.

Mainly, the api extractor tool expects so-called release tags to be present on public, exported api (https://api-extractor.com/pages/tsdoc/syntax/#release-tags). This tool gives a different meaning to the `@public` tag: the method/function/variable/whatever is 'stable' and should be regarded as package-public api.

When I try to annotate a part of my code as 'public', tsickle gives me a warning and returns a non-zero exit code: `TS0: @public annotations are reduntant with TypeScript equivalents` .

Would you consider to remove the `public` tag from the blacklist, or make the blacklist configurable?

The `@public` behaviour seems to be the last hurdle we need to cross to fully integrate the very powerful api extractor tool.

**Comment by mprobst** [comment]
We're reporting an error for tags like `@public` if they have special meaning in Closure Compiler and are redundant with equivalent TypeScript constructs. Sadly JSDoc is in a bit of an odd state, with lots of implementations and users, but no agreed semantics on what anything means - so things like this overloading of meaning happen a lot.

If I understand you correctly, a reasonable fix for you would be if `tsickle` would just escape tags such as `@public` and carry on, right? You don't need the `@public` to be retained in the JS output, do you?

I think that'd be a reasonable option. `main.ts` has a `shouldIgnoreWarningsForPath` function that currently never ignores, you could make that configurable to always ignore.

Does that make sense?

**Comment by evmar** [comment]
BTW, deep within tsickle this is intended to be a warning, not an error:
https://github.com/angular/tsickle/blob/f4a742640ea86a5e1d899625799e5d539680fa5f/src/jsdoc.ts#L217

It may just be bugs in the calling code that makes this causes a non-zero exit codes.

**Comment by mprobst** [comment]
@DrRataplan do you feel comfortable sending a PR for this? It'd essentially mean piping an option through to this place:
https://github.com/angular/tsickle/blob/master/src/main.ts#L166

**Comment by DrRataplan** [comment]
Sure, I'll try and send a PR. That might not be today though.

The `path` in `shouldIgnoreWarningsForPath` is a file path right? Wouldn't this mean we'd be ignoring __all__ warnings for the given path, even if they're *correct* warnings?

We could also make the warning for the `@public` tag / redundant JSDoc tags configurable, or don't make tsickle return a non-zero exit code (like @evmar said). What would your approach be?

**Comment by mprobst** [comment]
What tsickle should support for your use case is warning about `@public`
etc, e.g. by console printout, without failing, and then *not* escaping
them as `\@public`, right? I think I'd rather not have another whitelist of
tags, that seems like it'd get out of hand quickly :-)

**Comment by evmar** [comment]
Rereading this, I wonder: wouldn't it make sense to generate your API docs from the non-tsickled code?  tsickle is designed to be part of the JS emit path and does deep surgery like removing enums.  But if I followed you, you want the d.ts you're generating to be about the TS API, not the JS goop we generate.

**Comment by DrRataplan** [comment]
I'm afraid I didn't explain my problem correctly. Let me sketch out my build pipeline:

I write my code in TypeScript. This is converted with tsickle to closure-ready JavaScript. As a side-effect of this, it also generates .d.ts files (by setting the "declarations" property in my tsconfig.json). These .d.ts files are basically generated by the 'normal' TypeScript compiler, **from the original TypeScript code**.

Using these .d.ts files, I use the api-extractor-tool to generate a single .d.ts file containing all of the (externally) public API. When I publish to npm, it has two interesting files: `fontoxpath.js`, which is the minified bundle and `fontoxpath.d.ts`, which contains of all API that a user of the library can get to.

As a diagram:

```
                      ,-------> dist/tmp/**/*.ts --Api extractor tool --> dist/fontoxpath.d.ts  ----.
src/**/*.ts ----TSickle (and TSC)                                                                   |
                      ' --->  dist/tmp/**/*.js  --Google Closure Compiler ---> dist/fontoxpath.js -,|
                                                                                                    |
                                                                                                   \./
                                                                                                    '
                                                                                         FontoXPath on npm
```

My problem comes from the mixed meaning of the `@public` tag, which I need to have in my TypeScript source (the one that is used for TSickle AND the typings generated by tsc). At the moment, I can just omit the `@public` tags, but I'd love to use the [api review](https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Feature-walkthrough#the-api-review-file-apits) process that the web-build-tools also provides. As a sidenote, **I do not care for the `@public` tag to be retained** in the closure compiler-ready code. In my eyes, that JavaScript code is generated and not meant for human eyes.

My code is actually open-source at [FontoXPath](https://github.com/FontoXML/fontoxpath). An example of a externally available function is [evaluateXPathToBoolean](https://github.com/FontoXML/fontoxpath/blob/master/src/evaluateXPathToBoolean.ts). The build pipeline is contained in [build.js](https://github.com/FontoXML/fontoxpath/blob/master/build.js).

My approach for this problem would be to find out why the exit code is set to non-zero, and addressing that.

My project already has a number of warnings I can not really fix (it warns about using type intersections in [a number of subtypes for Node](https://github.com/FontoXML/fontoxpath/blob/master/src/domFacade/ConcreteNode.ts#L13)), which I'm totally OK with. As long as I'm generating valid Closure Compiler code and minifying all minifyable property names, I am totally happy.

**Comment by evmar** [comment]
Great explanation, thanks.  What I was suggesting is that you could run the API extractor tool on the the original source.  That is, don't use dist/tmp/**/*.ts for anything, because it's just an internal detail of tsickle's TS->JS pipeline.

**Comment by DrRataplan** [comment]
Ah, so that's where my explanation is lacking. The API extractor tool is ran on on `.d.ts` files, not on `.ts` or `.js` files. **These `.d.ts` are generated from the `.js` files**. I am running the tool **on the original source**. My issue is not even that the `@public` tag clashes in meaning or that tsickle warns, just that tsickle crashes.

I'm currently setting up my dev environment for tsickle. I'll try to send in a PR for the non-zero error code soon. I haven't reproduced it in a unit test though, so I'll start with that.

**Comment by evmar** [comment]
In your diagram, you have an edge from `dist/tmp/**/*.ts -- Api extractor tool`.  I'm suggesting you instead have an edge from `src/**/*.ts -- Api extractor tool`.  Another way of saying this is saying you could generate your d.ts from the original source, without tsickle.  Our mental model is that tsickle output should only ever be consumed by closure compiler.

**Comment by DrRataplan** [comment]
Ah, yeah. so that's what you mean. The edge `dist/tmp/**/*.ts -- Api extractor tool` should read `dist/tmp/**/*.d.ts -- Api extractor tool`. I'm getting these mixed up... probably a sign that my buildchain is getting out of hand. bottom line: I'm using tsc (wrapped by tsickle) to generate my typings.

Besides that, I think not using tsickle for `.d.ts` generation is a step, but it won't fix any problems, will it? In the end, TSickle will be served TypeScript with `@public` tags, or am I missing something?

**Comment by evmar** [comment]
You are right, sorry for the digression.

The way these warnings are intended to work is that you can solve them in one of two ways:
- if you are writing code intentionally for Closure compiler (like we do at Google), we make warnings like these fatal to your build, because there's no reason (in that environment) to use @public 
- if you are writing code outside of Google, we make tsickle warn about these things but then do whatever mangling is necessary to force Closure to accept it anyway (which in this case is escaping them), in which case you can just ignore the warnings

So in your case, the latter behavior is I think what you want -- tsickle is just trying to say "hey this @public is pointless for closure compiler", which is true, but uninteresting in your case.  That is why Martin was suggesting disabling the warning.

**Comment by DrRataplan** [comment]
No problem. Glad to be on the same page now. The warning is correct, I just don't care for it in my project. My only problem is the exit code.

Thanks by the way for your help! I'm aware that I'm not using tsickle for it's intended use, but I really like how it works. And with the closure compiler being one of the best optimizing minifiers, it's a really cool project!

-- still working on a pr...--

**Comment by evmar** [comment]
I kinda suspect we should make warnigns always non-fatal.  This is not the first time it's come up and it's super confusing for users.

**Comment by DrRataplan** [comment]
Now I get it! Based on your first comment, I was thinking that warnings were always non-fatal, but that something else went wrong.

To check, am I correct in saying that **currently in TSickle**, only **some** warnings are fatal, depending on the context? This would explain that **some** occurences of `@public` are just fine (iirc it only warned when I placed it on a method), but **some** occurences cause TSickle to `process.exit(1)` out?

**Comment by evmar** [comment]
I suspect maybe we are inconsistently catching the @publics.  Our intent is to catch all of them, but then for all of them to be non-fatal warnings.

**Comment by evmar** [comment]
Maybe this should just be true instead of false here:
https://github.com/angular/tsickle/blob/2306d8209df15009c30d19f828a7b02ba73c144d/src/main.ts#L166

**Comment by DrRataplan** [comment]
Oh, wow, I am finally getting what @mprobst meant. I was breaking my head on (non-fatal) warnings versus (fatal) errors the whole time, while you have fatal vs non-fatal warnings. Which makes a lot of sense in the way you guys use this at Google!

PR incoming! `tsickle --ignoreWarnings` Thanks a bunch for your time!

**Comment by evmar** [comment]
Sorry for all the confusion.  We have this warning about exactly problems like these, so we really appreciate your help working through them!

https://github.com/angular/tsickle#warning-work-in-progress
