### ISSUE TITLE
0.34.2 has incorrect peerDependencies

### ISSUE THREAD

**Issue by IgorMinar** [angular/tsickle#982]
```
warning " > tsickle@0.34.2" has incorrect peer dependency "typescript@~3.1.3 || ~3.2.0-rc".
```

Consider setting peerDeps in:

https://github.com/angular/tsickle/blob/0000dd20deb2d1305f2d0f8138bdf0075983f35a/package.json#L20

to
```
"typescript": "~3.3.1"
```

**Comment by mprobst** [comment]
Whoops.

**Comment by IgorMinar** [comment]
Can you also cut a new release and push it to npm? Thanks

Current version: https://unpkg.com/tsickle/package.json
