### ISSUE TITLE
Provide compatible drop-in transformers

### ISSUE THREAD

**Issue by cromefire** [angular/tsickle#986]
It would be nice to have an easy transformer (of one of [this styles](https://github.com/cevek/ttypescript#pluginconfigtype)) which could be used to compile a library without breaking the output.

An example for output-breaking things:
```javascript
const tsickle_forward_declare_1 = goog.forwardDeclare("[...]");
```
Because everybody else would see `goog` as undeclared.

For example it should be possible to just annotate everything with jsdoc comments and that's it.

**Comment by evmar** [comment]
Sorry, I didn't quite understand the request here.  You want tsickle to provide some alternative API?

**Comment by cromefire** [comment]
It would be good, if I could just use this as transformer in `ttypescript`, to compile the library. I just want `tsickle`to add the closure jsdoc comments

**Comment by evmar** [comment]
Can you explain more why you want the comments? tsickle's purpose is to make the code compatible with Closure, and Closure requires the forwardDeclare bits.

**Comment by cromefire** [comment]
Shouldn't closure also work with files without this? Else every file would have to have this and you couldn't import any normal files

**Comment by cromefire** [comment]
This is again about making a public library more accessible for closure. We have typescript types and certainly do not want annotate all the things with jsdoc comments by hand

**Comment by evmar** [comment]
Maybe another way of saying it: when in TypeScript you write `import ... from ...`, tsickle emits `goog.require(...)`.  What are you suggesting tsickle emits instead?

**Comment by cromefire** [comment]
`import {Bar} from "foo";`, Es imports are supported by closure

**Comment by evmar** [comment]
Ahhh got it, thanks.  I will clarify this in the documentation.

**Comment by cromefire** [comment]
But that doesn't solve the problem that there is no way to disable the rewrite of `tsickle`

**Comment by cromefire** [comment]
I would `tsickle` to just provide a (`ttypescript` compatible) transformer, that just encodes all the typescript information into jsdoc, the rest is up to the end user

**Comment by evmar** [comment]
The short answer is that tsickle generates modules using the goog.module module system, which is incompatible with ES modules.  Closure's support for ES modules still in progress (for example, last I knew, "export * from ..." doesn't work), so we don't currently have plans to produce ES modules.

We do have this internal flag
https://github.com/angular/tsickle/blob/eb3725db0e892a81b50804f2e19f5a80705fd2b2/src/tsickle.ts#L51
but it controls goog.module vs commonjs, and I don't expect things to work if you toggle it.

**Comment by evmar** [comment]
By the way, if you're looking to just get JSDoc comments from some TypeScript code, I suspect tsickle doesn't do what you want anyway, because it translates TypeScript code to Closure-specific JSDoc comments.  For example, it will use the syntax `{!Foo}` to mean "Foo, and not null" in a type declaration.

**Comment by cromefire** [comment]
I wasn't aware that closure doesn't support export from, but no it was about giving users the **option** to use clusure (but definitely not requiring it).

**Comment by cromefire** [comment]
> so we don't currently have plans to produce ES modules.

You would just need to not touch the imports/exports or even just split `export {foo} from "bar"` into `import {foo} from "bar"` and `export {foo}`

**Comment by cromefire** [comment]
Or is there any good way to recover all the information from `.js` + `.d.ts`

**Comment by evmar** [comment]
I think it's not as simple as just not touching the "import" lines.  You can look at some of our sample output to see some more of the goop we generate:

https://github.com/angular/tsickle/blob/master/test_files/export/export.js

For example note the code that adds references to the `exports` object in there.

**Comment by cromefire** [comment]
(also you might need to know that I see closure primarily as a minimizer, for the rest, I got webpack or rollup)

**Comment by cromefire** [comment]
There is also the `externs` option, but I guess that outputs extern additionally to the normal output right?

**Comment by mprobst** [comment]
It should be possible to run tsickle to add JSDoc comments, and still emit ES modules so that other JS processors can handle the code.

Practically it isn't though, I believe. The `forwardDeclare` you give is a good example - it's needed to emit correct type references for Closure:

```ts
import {TypeOnly} from './type_only';
let x: TypeOnly|null = null;
```

By TypeScript semantics, because `type_only` is only imported for its type, we must not generate a runtime import; the import line is dropped. By Closure Compiler semantics, we need to emit something to be able to reference the type, which is the `goog.forwardDeclare` (or now `goog.requireType`).

That's the module system, but there are many more specific situations, for example around enums, externs handling with `declare`, etc.

I think currently for anything but the most trivial examples, Closure-style JavaScript is its own language subset, and largely incompatible with other JavaScript or the regular JavaScript toolchain. I believe you cannot emit code that has good fidelity for Closure without depending on many Closure-isms, such as the standard library and `goog.requireType` etc.

**Comment by cromefire** [comment]
Also isn't there a way of doing something like `./type_only.TypeOnly`?

And is there a way to only generate `externs` or recover the information from `.d.ts`. If that is the case then that would be a good solution.

**Comment by mprobst** [comment]
Not that I know of.

**Comment by cromefire** [comment]
There it is, took some time to find: https://github.com/google/closure-compiler/wiki/JS-Modules#type-references

**Comment by cromefire** [comment]
Or you could simply add the import again

**Comment by mprobst** [comment]
You cannot import again, as that'd change load order semantics. Re type references, that looks roughly like the right feature, though doesn't seem to spell out how to handle root relative or absolute module paths.

This might work for the type references, but you'd still have all the other problems. I don't think we'll get around to working on that anytime soon; finding a good solution there is probably substantial work and outside of our use case.

**Comment by cromefire** [comment]
> And is there a way to only generate `externs` or recover the information from `.d.ts.` If that is the case then that would be a good solution.

Is that an option?

**Comment by cromefire** [comment]
> It depends on what you're really trying to achieve.

Good compression, nothing more.

**Comment by mprobst** [comment]
Externs will prevent renaming, which goes against the compression goal.

Overall I think my comment from above stands - it's hard to make things work with Closure Compiler outside a very controlled environment (including use of the Closure base library), and it's outside of scope for us.

If you're interesting in working on this, you could try to fork and build a minimum viable demo or so, and then we could see if it works in tsickle. We have no plans to work on such a thing at the moment though, so I'll close this issue in the scope of this project.

**Comment by cromefire** [comment]
Well then I have to wait until some on builds a minifier that works with the typescript typing
