### ISSUE TITLE
@enum and JSDoc handling

### ISSUE THREAD

**Issue by rkirov** [angular/tsickle#998]
@enum is in our list of banned jsdocs - https://github.com/angular/tsickle/blob/master/src/jsdoc.ts#L148
but they still appear in our codebase. This is because, we completely remove the original comment along with the node as part of the enum rewriting part of tsickle - https://github.com/angular/tsickle/blob/master/src/enum_transformer.ts#L158

and then there is nothing to catch and error in the second phase. Also the original comment text (even if it has no @enum) is not kept in the output.

**Comment by mprobst** [comment]
Internal issue at b/144256857.
